package com.firstCapacity.business.test_automation.entity;

public class automationUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Tue Sep 12 09:58:28 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.test1
     *
     * @mbg.generated Tue Sep 12 09:58:28 CST 2017
     */
    private String test1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.test2
     *
     * @mbg.generated Tue Sep 12 09:58:28 CST 2017
     */
    private String test2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.test3
     *
     * @mbg.generated Tue Sep 12 09:58:28 CST 2017
     */
    private String test3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Tue Sep 12 09:58:28 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Tue Sep 12 09:58:28 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.test1
     *
     * @return the value of user.test1
     *
     * @mbg.generated Tue Sep 12 09:58:28 CST 2017
     */
    public String getTest1() {
        return test1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.test1
     *
     * @param test1 the value for user.test1
     *
     * @mbg.generated Tue Sep 12 09:58:28 CST 2017
     */
    public void setTest1(String test1) {
        this.test1 = test1 == null ? null : test1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.test2
     *
     * @return the value of user.test2
     *
     * @mbg.generated Tue Sep 12 09:58:28 CST 2017
     */
    public String getTest2() {
        return test2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.test2
     *
     * @param test2 the value for user.test2
     *
     * @mbg.generated Tue Sep 12 09:58:28 CST 2017
     */
    public void setTest2(String test2) {
        this.test2 = test2 == null ? null : test2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.test3
     *
     * @return the value of user.test3
     *
     * @mbg.generated Tue Sep 12 09:58:28 CST 2017
     */
    public String getTest3() {
        return test3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.test3
     *
     * @param test3 the value for user.test3
     *
     * @mbg.generated Tue Sep 12 09:58:28 CST 2017
     */
    public void setTest3(String test3) {
        this.test3 = test3 == null ? null : test3.trim();
    }
}