package com.firstCapacity.business.HeFeiPower.entity;

import java.io.Serializable;
import java.util.Date;

public class HF_hy_04 implements Serializable{
	
	private static final long serialVersionUID = 1L;
	
    private String startTime;
    
    private String endTime;
    
    private String timeNew;
	
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.Time
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_fd
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11Fd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_t3
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11T3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_h1
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11H1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_t4
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11T4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_h2
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11H2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_co2
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11Co2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_d1
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11D1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_d3
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11D3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_ffs5
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11Ffs5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_ffs6
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11Ffs6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_pfk
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11Pfk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_pfg
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11Pfg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_hfs5
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11Hfs5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_hfs6
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11Hfs6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_sf5
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11Sf5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_sf6
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11Sf6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_js2
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11Js2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_s1
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11S1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_s2
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11S2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_s3
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11S3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_s4
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11S4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_p1
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11P1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_p2
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11P2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_p3
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11P3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_p4
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11P4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_pg
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11Pg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_fmax
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11Fmax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_fmin
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11Fmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_jssx
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11Jssx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_jsxx
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11Jsxx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_xfmax
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11Xfmax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_xfmin
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11Xfmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_hfmax
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11Hfmax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_hfmin
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11Hfmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_sfsd
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11Sfsd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_p
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11P;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_i
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11I;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_d
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11D;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_co2_sd
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11Co2Sd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_1p
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B111p;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_1i
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B111i;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_1d
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B111d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_hfts
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11Hfts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_2p
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B112p;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_2i
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B112i;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1_2d
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B112d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1jsqdt
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11jsqdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1jstzt
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11jstzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1zlzr_am
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11zlzrAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1ys_am
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11ysAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1ddf_am
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11ddfAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1sjam
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11sjam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1djam
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11djam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1xff_am
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11xffAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1hff_am
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11hffAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_04.t2_b1_1jst_s
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    private Float t2B11jstS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.Time
     *
     * @return the value of HF_hy_04.Time
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.Time
     *
     * @param time the value for HF_hy_04.Time
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_fd
     *
     * @return the value of HF_hy_04.t2_b1_1_fd
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11Fd() {
        return t2B11Fd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_fd
     *
     * @param t2B11Fd the value for HF_hy_04.t2_b1_1_fd
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11Fd(Float t2B11Fd) {
        this.t2B11Fd = t2B11Fd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_t3
     *
     * @return the value of HF_hy_04.t2_b1_1_t3
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11T3() {
        return t2B11T3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_t3
     *
     * @param t2B11T3 the value for HF_hy_04.t2_b1_1_t3
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11T3(Float t2B11T3) {
        this.t2B11T3 = t2B11T3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_h1
     *
     * @return the value of HF_hy_04.t2_b1_1_h1
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11H1() {
        return t2B11H1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_h1
     *
     * @param t2B11H1 the value for HF_hy_04.t2_b1_1_h1
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11H1(Float t2B11H1) {
        this.t2B11H1 = t2B11H1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_t4
     *
     * @return the value of HF_hy_04.t2_b1_1_t4
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11T4() {
        return t2B11T4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_t4
     *
     * @param t2B11T4 the value for HF_hy_04.t2_b1_1_t4
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11T4(Float t2B11T4) {
        this.t2B11T4 = t2B11T4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_h2
     *
     * @return the value of HF_hy_04.t2_b1_1_h2
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11H2() {
        return t2B11H2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_h2
     *
     * @param t2B11H2 the value for HF_hy_04.t2_b1_1_h2
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11H2(Float t2B11H2) {
        this.t2B11H2 = t2B11H2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_co2
     *
     * @return the value of HF_hy_04.t2_b1_1_co2
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11Co2() {
        return t2B11Co2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_co2
     *
     * @param t2B11Co2 the value for HF_hy_04.t2_b1_1_co2
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11Co2(Float t2B11Co2) {
        this.t2B11Co2 = t2B11Co2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_d1
     *
     * @return the value of HF_hy_04.t2_b1_1_d1
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11D1() {
        return t2B11D1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_d1
     *
     * @param t2B11D1 the value for HF_hy_04.t2_b1_1_d1
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11D1(Float t2B11D1) {
        this.t2B11D1 = t2B11D1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_d3
     *
     * @return the value of HF_hy_04.t2_b1_1_d3
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11D3() {
        return t2B11D3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_d3
     *
     * @param t2B11D3 the value for HF_hy_04.t2_b1_1_d3
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11D3(Float t2B11D3) {
        this.t2B11D3 = t2B11D3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_ffs5
     *
     * @return the value of HF_hy_04.t2_b1_1_ffs5
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11Ffs5() {
        return t2B11Ffs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_ffs5
     *
     * @param t2B11Ffs5 the value for HF_hy_04.t2_b1_1_ffs5
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11Ffs5(Float t2B11Ffs5) {
        this.t2B11Ffs5 = t2B11Ffs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_ffs6
     *
     * @return the value of HF_hy_04.t2_b1_1_ffs6
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11Ffs6() {
        return t2B11Ffs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_ffs6
     *
     * @param t2B11Ffs6 the value for HF_hy_04.t2_b1_1_ffs6
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11Ffs6(Float t2B11Ffs6) {
        this.t2B11Ffs6 = t2B11Ffs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_pfk
     *
     * @return the value of HF_hy_04.t2_b1_1_pfk
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11Pfk() {
        return t2B11Pfk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_pfk
     *
     * @param t2B11Pfk the value for HF_hy_04.t2_b1_1_pfk
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11Pfk(Float t2B11Pfk) {
        this.t2B11Pfk = t2B11Pfk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_pfg
     *
     * @return the value of HF_hy_04.t2_b1_1_pfg
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11Pfg() {
        return t2B11Pfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_pfg
     *
     * @param t2B11Pfg the value for HF_hy_04.t2_b1_1_pfg
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11Pfg(Float t2B11Pfg) {
        this.t2B11Pfg = t2B11Pfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_hfs5
     *
     * @return the value of HF_hy_04.t2_b1_1_hfs5
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11Hfs5() {
        return t2B11Hfs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_hfs5
     *
     * @param t2B11Hfs5 the value for HF_hy_04.t2_b1_1_hfs5
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11Hfs5(Float t2B11Hfs5) {
        this.t2B11Hfs5 = t2B11Hfs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_hfs6
     *
     * @return the value of HF_hy_04.t2_b1_1_hfs6
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11Hfs6() {
        return t2B11Hfs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_hfs6
     *
     * @param t2B11Hfs6 the value for HF_hy_04.t2_b1_1_hfs6
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11Hfs6(Float t2B11Hfs6) {
        this.t2B11Hfs6 = t2B11Hfs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_sf5
     *
     * @return the value of HF_hy_04.t2_b1_1_sf5
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11Sf5() {
        return t2B11Sf5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_sf5
     *
     * @param t2B11Sf5 the value for HF_hy_04.t2_b1_1_sf5
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11Sf5(Float t2B11Sf5) {
        this.t2B11Sf5 = t2B11Sf5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_sf6
     *
     * @return the value of HF_hy_04.t2_b1_1_sf6
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11Sf6() {
        return t2B11Sf6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_sf6
     *
     * @param t2B11Sf6 the value for HF_hy_04.t2_b1_1_sf6
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11Sf6(Float t2B11Sf6) {
        this.t2B11Sf6 = t2B11Sf6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_js2
     *
     * @return the value of HF_hy_04.t2_b1_1_js2
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11Js2() {
        return t2B11Js2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_js2
     *
     * @param t2B11Js2 the value for HF_hy_04.t2_b1_1_js2
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11Js2(Float t2B11Js2) {
        this.t2B11Js2 = t2B11Js2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_s1
     *
     * @return the value of HF_hy_04.t2_b1_1_s1
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11S1() {
        return t2B11S1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_s1
     *
     * @param t2B11S1 the value for HF_hy_04.t2_b1_1_s1
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11S1(Float t2B11S1) {
        this.t2B11S1 = t2B11S1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_s2
     *
     * @return the value of HF_hy_04.t2_b1_1_s2
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11S2() {
        return t2B11S2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_s2
     *
     * @param t2B11S2 the value for HF_hy_04.t2_b1_1_s2
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11S2(Float t2B11S2) {
        this.t2B11S2 = t2B11S2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_s3
     *
     * @return the value of HF_hy_04.t2_b1_1_s3
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11S3() {
        return t2B11S3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_s3
     *
     * @param t2B11S3 the value for HF_hy_04.t2_b1_1_s3
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11S3(Float t2B11S3) {
        this.t2B11S3 = t2B11S3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_s4
     *
     * @return the value of HF_hy_04.t2_b1_1_s4
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11S4() {
        return t2B11S4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_s4
     *
     * @param t2B11S4 the value for HF_hy_04.t2_b1_1_s4
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11S4(Float t2B11S4) {
        this.t2B11S4 = t2B11S4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_p1
     *
     * @return the value of HF_hy_04.t2_b1_1_p1
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11P1() {
        return t2B11P1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_p1
     *
     * @param t2B11P1 the value for HF_hy_04.t2_b1_1_p1
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11P1(Float t2B11P1) {
        this.t2B11P1 = t2B11P1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_p2
     *
     * @return the value of HF_hy_04.t2_b1_1_p2
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11P2() {
        return t2B11P2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_p2
     *
     * @param t2B11P2 the value for HF_hy_04.t2_b1_1_p2
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11P2(Float t2B11P2) {
        this.t2B11P2 = t2B11P2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_p3
     *
     * @return the value of HF_hy_04.t2_b1_1_p3
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11P3() {
        return t2B11P3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_p3
     *
     * @param t2B11P3 the value for HF_hy_04.t2_b1_1_p3
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11P3(Float t2B11P3) {
        this.t2B11P3 = t2B11P3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_p4
     *
     * @return the value of HF_hy_04.t2_b1_1_p4
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11P4() {
        return t2B11P4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_p4
     *
     * @param t2B11P4 the value for HF_hy_04.t2_b1_1_p4
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11P4(Float t2B11P4) {
        this.t2B11P4 = t2B11P4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_pg
     *
     * @return the value of HF_hy_04.t2_b1_1_pg
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11Pg() {
        return t2B11Pg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_pg
     *
     * @param t2B11Pg the value for HF_hy_04.t2_b1_1_pg
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11Pg(Float t2B11Pg) {
        this.t2B11Pg = t2B11Pg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_fmax
     *
     * @return the value of HF_hy_04.t2_b1_1_fmax
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11Fmax() {
        return t2B11Fmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_fmax
     *
     * @param t2B11Fmax the value for HF_hy_04.t2_b1_1_fmax
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11Fmax(Float t2B11Fmax) {
        this.t2B11Fmax = t2B11Fmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_fmin
     *
     * @return the value of HF_hy_04.t2_b1_1_fmin
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11Fmin() {
        return t2B11Fmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_fmin
     *
     * @param t2B11Fmin the value for HF_hy_04.t2_b1_1_fmin
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11Fmin(Float t2B11Fmin) {
        this.t2B11Fmin = t2B11Fmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_jssx
     *
     * @return the value of HF_hy_04.t2_b1_1_jssx
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11Jssx() {
        return t2B11Jssx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_jssx
     *
     * @param t2B11Jssx the value for HF_hy_04.t2_b1_1_jssx
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11Jssx(Float t2B11Jssx) {
        this.t2B11Jssx = t2B11Jssx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_jsxx
     *
     * @return the value of HF_hy_04.t2_b1_1_jsxx
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11Jsxx() {
        return t2B11Jsxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_jsxx
     *
     * @param t2B11Jsxx the value for HF_hy_04.t2_b1_1_jsxx
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11Jsxx(Float t2B11Jsxx) {
        this.t2B11Jsxx = t2B11Jsxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_xfmax
     *
     * @return the value of HF_hy_04.t2_b1_1_xfmax
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11Xfmax() {
        return t2B11Xfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_xfmax
     *
     * @param t2B11Xfmax the value for HF_hy_04.t2_b1_1_xfmax
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11Xfmax(Float t2B11Xfmax) {
        this.t2B11Xfmax = t2B11Xfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_xfmin
     *
     * @return the value of HF_hy_04.t2_b1_1_xfmin
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11Xfmin() {
        return t2B11Xfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_xfmin
     *
     * @param t2B11Xfmin the value for HF_hy_04.t2_b1_1_xfmin
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11Xfmin(Float t2B11Xfmin) {
        this.t2B11Xfmin = t2B11Xfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_hfmax
     *
     * @return the value of HF_hy_04.t2_b1_1_hfmax
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11Hfmax() {
        return t2B11Hfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_hfmax
     *
     * @param t2B11Hfmax the value for HF_hy_04.t2_b1_1_hfmax
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11Hfmax(Float t2B11Hfmax) {
        this.t2B11Hfmax = t2B11Hfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_hfmin
     *
     * @return the value of HF_hy_04.t2_b1_1_hfmin
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11Hfmin() {
        return t2B11Hfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_hfmin
     *
     * @param t2B11Hfmin the value for HF_hy_04.t2_b1_1_hfmin
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11Hfmin(Float t2B11Hfmin) {
        this.t2B11Hfmin = t2B11Hfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_sfsd
     *
     * @return the value of HF_hy_04.t2_b1_1_sfsd
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11Sfsd() {
        return t2B11Sfsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_sfsd
     *
     * @param t2B11Sfsd the value for HF_hy_04.t2_b1_1_sfsd
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11Sfsd(Float t2B11Sfsd) {
        this.t2B11Sfsd = t2B11Sfsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_p
     *
     * @return the value of HF_hy_04.t2_b1_1_p
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11P() {
        return t2B11P;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_p
     *
     * @param t2B11P the value for HF_hy_04.t2_b1_1_p
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11P(Float t2B11P) {
        this.t2B11P = t2B11P;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_i
     *
     * @return the value of HF_hy_04.t2_b1_1_i
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11I() {
        return t2B11I;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_i
     *
     * @param t2B11I the value for HF_hy_04.t2_b1_1_i
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11I(Float t2B11I) {
        this.t2B11I = t2B11I;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_d
     *
     * @return the value of HF_hy_04.t2_b1_1_d
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11D() {
        return t2B11D;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_d
     *
     * @param t2B11D the value for HF_hy_04.t2_b1_1_d
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11D(Float t2B11D) {
        this.t2B11D = t2B11D;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_co2_sd
     *
     * @return the value of HF_hy_04.t2_b1_1_co2_sd
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11Co2Sd() {
        return t2B11Co2Sd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_co2_sd
     *
     * @param t2B11Co2Sd the value for HF_hy_04.t2_b1_1_co2_sd
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11Co2Sd(Float t2B11Co2Sd) {
        this.t2B11Co2Sd = t2B11Co2Sd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_1p
     *
     * @return the value of HF_hy_04.t2_b1_1_1p
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B111p() {
        return t2B111p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_1p
     *
     * @param t2B111p the value for HF_hy_04.t2_b1_1_1p
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B111p(Float t2B111p) {
        this.t2B111p = t2B111p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_1i
     *
     * @return the value of HF_hy_04.t2_b1_1_1i
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B111i() {
        return t2B111i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_1i
     *
     * @param t2B111i the value for HF_hy_04.t2_b1_1_1i
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B111i(Float t2B111i) {
        this.t2B111i = t2B111i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_1d
     *
     * @return the value of HF_hy_04.t2_b1_1_1d
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B111d() {
        return t2B111d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_1d
     *
     * @param t2B111d the value for HF_hy_04.t2_b1_1_1d
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B111d(Float t2B111d) {
        this.t2B111d = t2B111d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_hfts
     *
     * @return the value of HF_hy_04.t2_b1_1_hfts
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11Hfts() {
        return t2B11Hfts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_hfts
     *
     * @param t2B11Hfts the value for HF_hy_04.t2_b1_1_hfts
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11Hfts(Float t2B11Hfts) {
        this.t2B11Hfts = t2B11Hfts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_2p
     *
     * @return the value of HF_hy_04.t2_b1_1_2p
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B112p() {
        return t2B112p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_2p
     *
     * @param t2B112p the value for HF_hy_04.t2_b1_1_2p
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B112p(Float t2B112p) {
        this.t2B112p = t2B112p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_2i
     *
     * @return the value of HF_hy_04.t2_b1_1_2i
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B112i() {
        return t2B112i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_2i
     *
     * @param t2B112i the value for HF_hy_04.t2_b1_1_2i
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B112i(Float t2B112i) {
        this.t2B112i = t2B112i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1_2d
     *
     * @return the value of HF_hy_04.t2_b1_1_2d
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B112d() {
        return t2B112d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1_2d
     *
     * @param t2B112d the value for HF_hy_04.t2_b1_1_2d
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B112d(Float t2B112d) {
        this.t2B112d = t2B112d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1jsqdt
     *
     * @return the value of HF_hy_04.t2_b1_1jsqdt
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11jsqdt() {
        return t2B11jsqdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1jsqdt
     *
     * @param t2B11jsqdt the value for HF_hy_04.t2_b1_1jsqdt
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11jsqdt(Float t2B11jsqdt) {
        this.t2B11jsqdt = t2B11jsqdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1jstzt
     *
     * @return the value of HF_hy_04.t2_b1_1jstzt
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11jstzt() {
        return t2B11jstzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1jstzt
     *
     * @param t2B11jstzt the value for HF_hy_04.t2_b1_1jstzt
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11jstzt(Float t2B11jstzt) {
        this.t2B11jstzt = t2B11jstzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1zlzr_am
     *
     * @return the value of HF_hy_04.t2_b1_1zlzr_am
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11zlzrAm() {
        return t2B11zlzrAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1zlzr_am
     *
     * @param t2B11zlzrAm the value for HF_hy_04.t2_b1_1zlzr_am
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11zlzrAm(Float t2B11zlzrAm) {
        this.t2B11zlzrAm = t2B11zlzrAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1ys_am
     *
     * @return the value of HF_hy_04.t2_b1_1ys_am
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11ysAm() {
        return t2B11ysAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1ys_am
     *
     * @param t2B11ysAm the value for HF_hy_04.t2_b1_1ys_am
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11ysAm(Float t2B11ysAm) {
        this.t2B11ysAm = t2B11ysAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1ddf_am
     *
     * @return the value of HF_hy_04.t2_b1_1ddf_am
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11ddfAm() {
        return t2B11ddfAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1ddf_am
     *
     * @param t2B11ddfAm the value for HF_hy_04.t2_b1_1ddf_am
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11ddfAm(Float t2B11ddfAm) {
        this.t2B11ddfAm = t2B11ddfAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1sjam
     *
     * @return the value of HF_hy_04.t2_b1_1sjam
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11sjam() {
        return t2B11sjam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1sjam
     *
     * @param t2B11sjam the value for HF_hy_04.t2_b1_1sjam
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11sjam(Float t2B11sjam) {
        this.t2B11sjam = t2B11sjam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1djam
     *
     * @return the value of HF_hy_04.t2_b1_1djam
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11djam() {
        return t2B11djam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1djam
     *
     * @param t2B11djam the value for HF_hy_04.t2_b1_1djam
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11djam(Float t2B11djam) {
        this.t2B11djam = t2B11djam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1xff_am
     *
     * @return the value of HF_hy_04.t2_b1_1xff_am
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11xffAm() {
        return t2B11xffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1xff_am
     *
     * @param t2B11xffAm the value for HF_hy_04.t2_b1_1xff_am
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11xffAm(Float t2B11xffAm) {
        this.t2B11xffAm = t2B11xffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1hff_am
     *
     * @return the value of HF_hy_04.t2_b1_1hff_am
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11hffAm() {
        return t2B11hffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1hff_am
     *
     * @param t2B11hffAm the value for HF_hy_04.t2_b1_1hff_am
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11hffAm(Float t2B11hffAm) {
        this.t2B11hffAm = t2B11hffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_04.t2_b1_1jst_s
     *
     * @return the value of HF_hy_04.t2_b1_1jst_s
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public Float getT2B11jstS() {
        return t2B11jstS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_04.t2_b1_1jst_s
     *
     * @param t2B11jstS the value for HF_hy_04.t2_b1_1jst_s
     *
     * @mbg.generated Wed Oct 11 14:15:41 CST 2017
     */
    public void setT2B11jstS(Float t2B11jstS) {
        this.t2B11jstS = t2B11jstS;
    }

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getTimeNew() {
		return timeNew;
	}

	public void setTimeNew(String timeNew) {
		this.timeNew = timeNew;
	}
    
    
    
    
}