package com.firstCapacity.business.HeFeiPower.entity;

import java.io.Serializable;
import java.util.Date;

public class HF_hy_10 implements Serializable{
	
	private static final long serialVersionUID = 1L;
	
	
    private String startTime;
    
    private String endTime;
    
    private String timeNew;
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.Time
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_fd
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11Fd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_t3
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11T3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_h1
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11H1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_t4
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11T4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_h2
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11H2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_co2
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11Co2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_d3
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11D3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_ffs5
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11Ffs5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_ffs6
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11Ffs6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_pfk
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11Pfk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_pfg
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11Pfg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_hfs5
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11Hfs5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_hfs6
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11Hfs6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_sf5
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11Sf5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_sf6
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11Sf6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_js2
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11Js2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_s1
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11S1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_s2
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11S2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_s3
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11S3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_s4
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11S4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_p1
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11P1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_p2
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11P2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_p3
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11P3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_p4
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11P4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_pg
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11Pg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_fmax
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11Fmax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_fmin
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11Fmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_jssx
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11Jssx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_jsxx
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11Jsxx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_xfmax
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11Xfmax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_xfmin
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11Xfmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_hfmax
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11Hfmax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_hfmin
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11Hfmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_sfsd
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11Sfsd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_p
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11P;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_i
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11I;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_d
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11D;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_co2_sd
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11Co2Sd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_1p
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B111p;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_1i
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B111i;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_1d
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B111d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_hfts
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11Hfts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_2p
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B112p;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_2i
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B112i;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_2d
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B112d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1jsqdt
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11jsqdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1jstzt
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11jstzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1zlzr_am
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11zlzrAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1ys_am
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11ysAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1ddf_am
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11ddfAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1sjam
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11sjam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1djam
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11djam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1xff_am
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11xffAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1hff_am
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11hffAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1jst_s
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11jstS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_10.t5_b1_1_d1
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    private Float t5B11D1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.Time
     *
     * @return the value of HF_hy_10.Time
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.Time
     *
     * @param time the value for HF_hy_10.Time
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_fd
     *
     * @return the value of HF_hy_10.t5_b1_1_fd
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11Fd() {
        return t5B11Fd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_fd
     *
     * @param t5B11Fd the value for HF_hy_10.t5_b1_1_fd
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11Fd(Float t5B11Fd) {
        this.t5B11Fd = t5B11Fd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_t3
     *
     * @return the value of HF_hy_10.t5_b1_1_t3
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11T3() {
        return t5B11T3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_t3
     *
     * @param t5B11T3 the value for HF_hy_10.t5_b1_1_t3
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11T3(Float t5B11T3) {
        this.t5B11T3 = t5B11T3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_h1
     *
     * @return the value of HF_hy_10.t5_b1_1_h1
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11H1() {
        return t5B11H1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_h1
     *
     * @param t5B11H1 the value for HF_hy_10.t5_b1_1_h1
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11H1(Float t5B11H1) {
        this.t5B11H1 = t5B11H1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_t4
     *
     * @return the value of HF_hy_10.t5_b1_1_t4
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11T4() {
        return t5B11T4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_t4
     *
     * @param t5B11T4 the value for HF_hy_10.t5_b1_1_t4
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11T4(Float t5B11T4) {
        this.t5B11T4 = t5B11T4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_h2
     *
     * @return the value of HF_hy_10.t5_b1_1_h2
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11H2() {
        return t5B11H2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_h2
     *
     * @param t5B11H2 the value for HF_hy_10.t5_b1_1_h2
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11H2(Float t5B11H2) {
        this.t5B11H2 = t5B11H2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_co2
     *
     * @return the value of HF_hy_10.t5_b1_1_co2
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11Co2() {
        return t5B11Co2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_co2
     *
     * @param t5B11Co2 the value for HF_hy_10.t5_b1_1_co2
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11Co2(Float t5B11Co2) {
        this.t5B11Co2 = t5B11Co2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_d3
     *
     * @return the value of HF_hy_10.t5_b1_1_d3
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11D3() {
        return t5B11D3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_d3
     *
     * @param t5B11D3 the value for HF_hy_10.t5_b1_1_d3
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11D3(Float t5B11D3) {
        this.t5B11D3 = t5B11D3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_ffs5
     *
     * @return the value of HF_hy_10.t5_b1_1_ffs5
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11Ffs5() {
        return t5B11Ffs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_ffs5
     *
     * @param t5B11Ffs5 the value for HF_hy_10.t5_b1_1_ffs5
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11Ffs5(Float t5B11Ffs5) {
        this.t5B11Ffs5 = t5B11Ffs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_ffs6
     *
     * @return the value of HF_hy_10.t5_b1_1_ffs6
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11Ffs6() {
        return t5B11Ffs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_ffs6
     *
     * @param t5B11Ffs6 the value for HF_hy_10.t5_b1_1_ffs6
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11Ffs6(Float t5B11Ffs6) {
        this.t5B11Ffs6 = t5B11Ffs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_pfk
     *
     * @return the value of HF_hy_10.t5_b1_1_pfk
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11Pfk() {
        return t5B11Pfk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_pfk
     *
     * @param t5B11Pfk the value for HF_hy_10.t5_b1_1_pfk
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11Pfk(Float t5B11Pfk) {
        this.t5B11Pfk = t5B11Pfk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_pfg
     *
     * @return the value of HF_hy_10.t5_b1_1_pfg
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11Pfg() {
        return t5B11Pfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_pfg
     *
     * @param t5B11Pfg the value for HF_hy_10.t5_b1_1_pfg
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11Pfg(Float t5B11Pfg) {
        this.t5B11Pfg = t5B11Pfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_hfs5
     *
     * @return the value of HF_hy_10.t5_b1_1_hfs5
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11Hfs5() {
        return t5B11Hfs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_hfs5
     *
     * @param t5B11Hfs5 the value for HF_hy_10.t5_b1_1_hfs5
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11Hfs5(Float t5B11Hfs5) {
        this.t5B11Hfs5 = t5B11Hfs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_hfs6
     *
     * @return the value of HF_hy_10.t5_b1_1_hfs6
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11Hfs6() {
        return t5B11Hfs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_hfs6
     *
     * @param t5B11Hfs6 the value for HF_hy_10.t5_b1_1_hfs6
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11Hfs6(Float t5B11Hfs6) {
        this.t5B11Hfs6 = t5B11Hfs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_sf5
     *
     * @return the value of HF_hy_10.t5_b1_1_sf5
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11Sf5() {
        return t5B11Sf5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_sf5
     *
     * @param t5B11Sf5 the value for HF_hy_10.t5_b1_1_sf5
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11Sf5(Float t5B11Sf5) {
        this.t5B11Sf5 = t5B11Sf5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_sf6
     *
     * @return the value of HF_hy_10.t5_b1_1_sf6
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11Sf6() {
        return t5B11Sf6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_sf6
     *
     * @param t5B11Sf6 the value for HF_hy_10.t5_b1_1_sf6
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11Sf6(Float t5B11Sf6) {
        this.t5B11Sf6 = t5B11Sf6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_js2
     *
     * @return the value of HF_hy_10.t5_b1_1_js2
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11Js2() {
        return t5B11Js2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_js2
     *
     * @param t5B11Js2 the value for HF_hy_10.t5_b1_1_js2
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11Js2(Float t5B11Js2) {
        this.t5B11Js2 = t5B11Js2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_s1
     *
     * @return the value of HF_hy_10.t5_b1_1_s1
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11S1() {
        return t5B11S1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_s1
     *
     * @param t5B11S1 the value for HF_hy_10.t5_b1_1_s1
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11S1(Float t5B11S1) {
        this.t5B11S1 = t5B11S1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_s2
     *
     * @return the value of HF_hy_10.t5_b1_1_s2
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11S2() {
        return t5B11S2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_s2
     *
     * @param t5B11S2 the value for HF_hy_10.t5_b1_1_s2
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11S2(Float t5B11S2) {
        this.t5B11S2 = t5B11S2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_s3
     *
     * @return the value of HF_hy_10.t5_b1_1_s3
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11S3() {
        return t5B11S3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_s3
     *
     * @param t5B11S3 the value for HF_hy_10.t5_b1_1_s3
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11S3(Float t5B11S3) {
        this.t5B11S3 = t5B11S3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_s4
     *
     * @return the value of HF_hy_10.t5_b1_1_s4
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11S4() {
        return t5B11S4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_s4
     *
     * @param t5B11S4 the value for HF_hy_10.t5_b1_1_s4
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11S4(Float t5B11S4) {
        this.t5B11S4 = t5B11S4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_p1
     *
     * @return the value of HF_hy_10.t5_b1_1_p1
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11P1() {
        return t5B11P1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_p1
     *
     * @param t5B11P1 the value for HF_hy_10.t5_b1_1_p1
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11P1(Float t5B11P1) {
        this.t5B11P1 = t5B11P1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_p2
     *
     * @return the value of HF_hy_10.t5_b1_1_p2
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11P2() {
        return t5B11P2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_p2
     *
     * @param t5B11P2 the value for HF_hy_10.t5_b1_1_p2
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11P2(Float t5B11P2) {
        this.t5B11P2 = t5B11P2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_p3
     *
     * @return the value of HF_hy_10.t5_b1_1_p3
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11P3() {
        return t5B11P3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_p3
     *
     * @param t5B11P3 the value for HF_hy_10.t5_b1_1_p3
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11P3(Float t5B11P3) {
        this.t5B11P3 = t5B11P3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_p4
     *
     * @return the value of HF_hy_10.t5_b1_1_p4
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11P4() {
        return t5B11P4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_p4
     *
     * @param t5B11P4 the value for HF_hy_10.t5_b1_1_p4
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11P4(Float t5B11P4) {
        this.t5B11P4 = t5B11P4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_pg
     *
     * @return the value of HF_hy_10.t5_b1_1_pg
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11Pg() {
        return t5B11Pg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_pg
     *
     * @param t5B11Pg the value for HF_hy_10.t5_b1_1_pg
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11Pg(Float t5B11Pg) {
        this.t5B11Pg = t5B11Pg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_fmax
     *
     * @return the value of HF_hy_10.t5_b1_1_fmax
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11Fmax() {
        return t5B11Fmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_fmax
     *
     * @param t5B11Fmax the value for HF_hy_10.t5_b1_1_fmax
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11Fmax(Float t5B11Fmax) {
        this.t5B11Fmax = t5B11Fmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_fmin
     *
     * @return the value of HF_hy_10.t5_b1_1_fmin
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11Fmin() {
        return t5B11Fmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_fmin
     *
     * @param t5B11Fmin the value for HF_hy_10.t5_b1_1_fmin
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11Fmin(Float t5B11Fmin) {
        this.t5B11Fmin = t5B11Fmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_jssx
     *
     * @return the value of HF_hy_10.t5_b1_1_jssx
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11Jssx() {
        return t5B11Jssx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_jssx
     *
     * @param t5B11Jssx the value for HF_hy_10.t5_b1_1_jssx
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11Jssx(Float t5B11Jssx) {
        this.t5B11Jssx = t5B11Jssx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_jsxx
     *
     * @return the value of HF_hy_10.t5_b1_1_jsxx
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11Jsxx() {
        return t5B11Jsxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_jsxx
     *
     * @param t5B11Jsxx the value for HF_hy_10.t5_b1_1_jsxx
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11Jsxx(Float t5B11Jsxx) {
        this.t5B11Jsxx = t5B11Jsxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_xfmax
     *
     * @return the value of HF_hy_10.t5_b1_1_xfmax
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11Xfmax() {
        return t5B11Xfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_xfmax
     *
     * @param t5B11Xfmax the value for HF_hy_10.t5_b1_1_xfmax
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11Xfmax(Float t5B11Xfmax) {
        this.t5B11Xfmax = t5B11Xfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_xfmin
     *
     * @return the value of HF_hy_10.t5_b1_1_xfmin
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11Xfmin() {
        return t5B11Xfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_xfmin
     *
     * @param t5B11Xfmin the value for HF_hy_10.t5_b1_1_xfmin
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11Xfmin(Float t5B11Xfmin) {
        this.t5B11Xfmin = t5B11Xfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_hfmax
     *
     * @return the value of HF_hy_10.t5_b1_1_hfmax
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11Hfmax() {
        return t5B11Hfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_hfmax
     *
     * @param t5B11Hfmax the value for HF_hy_10.t5_b1_1_hfmax
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11Hfmax(Float t5B11Hfmax) {
        this.t5B11Hfmax = t5B11Hfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_hfmin
     *
     * @return the value of HF_hy_10.t5_b1_1_hfmin
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11Hfmin() {
        return t5B11Hfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_hfmin
     *
     * @param t5B11Hfmin the value for HF_hy_10.t5_b1_1_hfmin
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11Hfmin(Float t5B11Hfmin) {
        this.t5B11Hfmin = t5B11Hfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_sfsd
     *
     * @return the value of HF_hy_10.t5_b1_1_sfsd
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11Sfsd() {
        return t5B11Sfsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_sfsd
     *
     * @param t5B11Sfsd the value for HF_hy_10.t5_b1_1_sfsd
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11Sfsd(Float t5B11Sfsd) {
        this.t5B11Sfsd = t5B11Sfsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_p
     *
     * @return the value of HF_hy_10.t5_b1_1_p
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11P() {
        return t5B11P;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_p
     *
     * @param t5B11P the value for HF_hy_10.t5_b1_1_p
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11P(Float t5B11P) {
        this.t5B11P = t5B11P;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_i
     *
     * @return the value of HF_hy_10.t5_b1_1_i
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11I() {
        return t5B11I;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_i
     *
     * @param t5B11I the value for HF_hy_10.t5_b1_1_i
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11I(Float t5B11I) {
        this.t5B11I = t5B11I;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_d
     *
     * @return the value of HF_hy_10.t5_b1_1_d
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11D() {
        return t5B11D;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_d
     *
     * @param t5B11D the value for HF_hy_10.t5_b1_1_d
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11D(Float t5B11D) {
        this.t5B11D = t5B11D;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_co2_sd
     *
     * @return the value of HF_hy_10.t5_b1_1_co2_sd
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11Co2Sd() {
        return t5B11Co2Sd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_co2_sd
     *
     * @param t5B11Co2Sd the value for HF_hy_10.t5_b1_1_co2_sd
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11Co2Sd(Float t5B11Co2Sd) {
        this.t5B11Co2Sd = t5B11Co2Sd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_1p
     *
     * @return the value of HF_hy_10.t5_b1_1_1p
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B111p() {
        return t5B111p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_1p
     *
     * @param t5B111p the value for HF_hy_10.t5_b1_1_1p
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B111p(Float t5B111p) {
        this.t5B111p = t5B111p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_1i
     *
     * @return the value of HF_hy_10.t5_b1_1_1i
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B111i() {
        return t5B111i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_1i
     *
     * @param t5B111i the value for HF_hy_10.t5_b1_1_1i
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B111i(Float t5B111i) {
        this.t5B111i = t5B111i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_1d
     *
     * @return the value of HF_hy_10.t5_b1_1_1d
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B111d() {
        return t5B111d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_1d
     *
     * @param t5B111d the value for HF_hy_10.t5_b1_1_1d
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B111d(Float t5B111d) {
        this.t5B111d = t5B111d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_hfts
     *
     * @return the value of HF_hy_10.t5_b1_1_hfts
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11Hfts() {
        return t5B11Hfts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_hfts
     *
     * @param t5B11Hfts the value for HF_hy_10.t5_b1_1_hfts
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11Hfts(Float t5B11Hfts) {
        this.t5B11Hfts = t5B11Hfts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_2p
     *
     * @return the value of HF_hy_10.t5_b1_1_2p
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B112p() {
        return t5B112p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_2p
     *
     * @param t5B112p the value for HF_hy_10.t5_b1_1_2p
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B112p(Float t5B112p) {
        this.t5B112p = t5B112p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_2i
     *
     * @return the value of HF_hy_10.t5_b1_1_2i
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B112i() {
        return t5B112i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_2i
     *
     * @param t5B112i the value for HF_hy_10.t5_b1_1_2i
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B112i(Float t5B112i) {
        this.t5B112i = t5B112i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_2d
     *
     * @return the value of HF_hy_10.t5_b1_1_2d
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B112d() {
        return t5B112d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_2d
     *
     * @param t5B112d the value for HF_hy_10.t5_b1_1_2d
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B112d(Float t5B112d) {
        this.t5B112d = t5B112d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1jsqdt
     *
     * @return the value of HF_hy_10.t5_b1_1jsqdt
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11jsqdt() {
        return t5B11jsqdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1jsqdt
     *
     * @param t5B11jsqdt the value for HF_hy_10.t5_b1_1jsqdt
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11jsqdt(Float t5B11jsqdt) {
        this.t5B11jsqdt = t5B11jsqdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1jstzt
     *
     * @return the value of HF_hy_10.t5_b1_1jstzt
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11jstzt() {
        return t5B11jstzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1jstzt
     *
     * @param t5B11jstzt the value for HF_hy_10.t5_b1_1jstzt
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11jstzt(Float t5B11jstzt) {
        this.t5B11jstzt = t5B11jstzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1zlzr_am
     *
     * @return the value of HF_hy_10.t5_b1_1zlzr_am
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11zlzrAm() {
        return t5B11zlzrAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1zlzr_am
     *
     * @param t5B11zlzrAm the value for HF_hy_10.t5_b1_1zlzr_am
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11zlzrAm(Float t5B11zlzrAm) {
        this.t5B11zlzrAm = t5B11zlzrAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1ys_am
     *
     * @return the value of HF_hy_10.t5_b1_1ys_am
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11ysAm() {
        return t5B11ysAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1ys_am
     *
     * @param t5B11ysAm the value for HF_hy_10.t5_b1_1ys_am
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11ysAm(Float t5B11ysAm) {
        this.t5B11ysAm = t5B11ysAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1ddf_am
     *
     * @return the value of HF_hy_10.t5_b1_1ddf_am
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11ddfAm() {
        return t5B11ddfAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1ddf_am
     *
     * @param t5B11ddfAm the value for HF_hy_10.t5_b1_1ddf_am
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11ddfAm(Float t5B11ddfAm) {
        this.t5B11ddfAm = t5B11ddfAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1sjam
     *
     * @return the value of HF_hy_10.t5_b1_1sjam
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11sjam() {
        return t5B11sjam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1sjam
     *
     * @param t5B11sjam the value for HF_hy_10.t5_b1_1sjam
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11sjam(Float t5B11sjam) {
        this.t5B11sjam = t5B11sjam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1djam
     *
     * @return the value of HF_hy_10.t5_b1_1djam
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11djam() {
        return t5B11djam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1djam
     *
     * @param t5B11djam the value for HF_hy_10.t5_b1_1djam
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11djam(Float t5B11djam) {
        this.t5B11djam = t5B11djam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1xff_am
     *
     * @return the value of HF_hy_10.t5_b1_1xff_am
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11xffAm() {
        return t5B11xffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1xff_am
     *
     * @param t5B11xffAm the value for HF_hy_10.t5_b1_1xff_am
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11xffAm(Float t5B11xffAm) {
        this.t5B11xffAm = t5B11xffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1hff_am
     *
     * @return the value of HF_hy_10.t5_b1_1hff_am
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11hffAm() {
        return t5B11hffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1hff_am
     *
     * @param t5B11hffAm the value for HF_hy_10.t5_b1_1hff_am
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11hffAm(Float t5B11hffAm) {
        this.t5B11hffAm = t5B11hffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1jst_s
     *
     * @return the value of HF_hy_10.t5_b1_1jst_s
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11jstS() {
        return t5B11jstS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1jst_s
     *
     * @param t5B11jstS the value for HF_hy_10.t5_b1_1jst_s
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11jstS(Float t5B11jstS) {
        this.t5B11jstS = t5B11jstS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_10.t5_b1_1_d1
     *
     * @return the value of HF_hy_10.t5_b1_1_d1
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public Float getT5B11D1() {
        return t5B11D1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_10.t5_b1_1_d1
     *
     * @param t5B11D1 the value for HF_hy_10.t5_b1_1_d1
     *
     * @mbg.generated Wed Oct 11 14:17:41 CST 2017
     */
    public void setT5B11D1(Float t5B11D1) {
        this.t5B11D1 = t5B11D1;
    }

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getTimeNew() {
		return timeNew;
	}

	public void setTimeNew(String timeNew) {
		this.timeNew = timeNew;
	}
    
    
    
	
}