package com.firstCapacity.business.HeFeiPower.entity;

import java.io.Serializable;
import java.util.Date;

public class HF_hy_27 implements Serializable{
	
	private static final long serialVersionUID = 1L;
	
	
    private String startTime;
    
    private String endTime;
    
    private String timeNew;
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.Time
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.c_t_sp_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float ctSp2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.h_t_sp_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float htSp2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.cool_lwt_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float coolLwt2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.cool_ewt_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float coolEwt2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.cond_lwt_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float condLwt2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.cond_ewt_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float condEwt2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.high_p_t1_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float highPT12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.high_p_t2_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float highPT22;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.high_p_t3_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float highPT32;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.high_p_t4_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float highPT42;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.low_p_t1_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float lowPT12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.low_p_t2_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float lowPT22;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.low_p_t3_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float lowPT32;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.low_p_t4_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float lowPT42;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.cpt_1_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float cpt12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.cpt_2_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float cpt22;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.cpt_3_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float cpt32;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.cpt_4_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float cpt42;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.ncircuits_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float ncircuits2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.ncompressors_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float ncompressors2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.typeofcp_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float typeofcp2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.unit_status_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float unitStatus2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.unit_t_status_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float unitTStatus2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.operatingmode_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float operatingmode2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.cpofforon_1_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float cpofforon12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.cpchiler_1_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float cpchiler12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.cpheatpump_1_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float cpheatpump12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.cpofforon_2_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float cpofforon22;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.cpchiler_2_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float cpchiler22;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.cpheatpump_2_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float cpheatpump22;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.cpofforon_3_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float cpofforon32;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.cpchiler_3_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float cpchiler32;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.cpheatpump_3_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float cpheatpump32;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.cpofforon_4_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float cpofforon42;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.cpchiler_4_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float cpchiler42;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.cpheatpump_4_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float cpheatpump42;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.ahcp_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float ahcp2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.c_t_d_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float ctD2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.apofct_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float apofct2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.apofct_h_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float apofctH2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.hptd_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float hptd2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.apofhpt_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float apofhpt2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.apofhpt_h_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float apofhptH2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.tlincm_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float tlincm2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_27.tlinhpm_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    private Float tlinhpm2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.Time
     *
     * @return the value of HF_hy_27.Time
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.Time
     *
     * @param time the value for HF_hy_27.Time
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.cool_lwt_2
     *
     * @return the value of HF_hy_27.cool_lwt_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getCoolLwt2() {
        return coolLwt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.cool_lwt_2
     *
     * @param coolLwt2 the value for HF_hy_27.cool_lwt_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setCoolLwt2(Float coolLwt2) {
        this.coolLwt2 = coolLwt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.cool_ewt_2
     *
     * @return the value of HF_hy_27.cool_ewt_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getCoolEwt2() {
        return coolEwt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.cool_ewt_2
     *
     * @param coolEwt2 the value for HF_hy_27.cool_ewt_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setCoolEwt2(Float coolEwt2) {
        this.coolEwt2 = coolEwt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.cond_lwt_2
     *
     * @return the value of HF_hy_27.cond_lwt_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getCondLwt2() {
        return condLwt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.cond_lwt_2
     *
     * @param condLwt2 the value for HF_hy_27.cond_lwt_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setCondLwt2(Float condLwt2) {
        this.condLwt2 = condLwt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.cond_ewt_2
     *
     * @return the value of HF_hy_27.cond_ewt_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getCondEwt2() {
        return condEwt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.cond_ewt_2
     *
     * @param condEwt2 the value for HF_hy_27.cond_ewt_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setCondEwt2(Float condEwt2) {
        this.condEwt2 = condEwt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.high_p_t1_2
     *
     * @return the value of HF_hy_27.high_p_t1_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getHighPT12() {
        return highPT12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.high_p_t1_2
     *
     * @param highPT12 the value for HF_hy_27.high_p_t1_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setHighPT12(Float highPT12) {
        this.highPT12 = highPT12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.high_p_t2_2
     *
     * @return the value of HF_hy_27.high_p_t2_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getHighPT22() {
        return highPT22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.high_p_t2_2
     *
     * @param highPT22 the value for HF_hy_27.high_p_t2_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setHighPT22(Float highPT22) {
        this.highPT22 = highPT22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.high_p_t3_2
     *
     * @return the value of HF_hy_27.high_p_t3_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getHighPT32() {
        return highPT32;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.high_p_t3_2
     *
     * @param highPT32 the value for HF_hy_27.high_p_t3_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setHighPT32(Float highPT32) {
        this.highPT32 = highPT32;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.high_p_t4_2
     *
     * @return the value of HF_hy_27.high_p_t4_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getHighPT42() {
        return highPT42;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.high_p_t4_2
     *
     * @param highPT42 the value for HF_hy_27.high_p_t4_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setHighPT42(Float highPT42) {
        this.highPT42 = highPT42;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.low_p_t1_2
     *
     * @return the value of HF_hy_27.low_p_t1_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getLowPT12() {
        return lowPT12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.low_p_t1_2
     *
     * @param lowPT12 the value for HF_hy_27.low_p_t1_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setLowPT12(Float lowPT12) {
        this.lowPT12 = lowPT12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.low_p_t2_2
     *
     * @return the value of HF_hy_27.low_p_t2_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getLowPT22() {
        return lowPT22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.low_p_t2_2
     *
     * @param lowPT22 the value for HF_hy_27.low_p_t2_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setLowPT22(Float lowPT22) {
        this.lowPT22 = lowPT22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.low_p_t3_2
     *
     * @return the value of HF_hy_27.low_p_t3_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getLowPT32() {
        return lowPT32;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.low_p_t3_2
     *
     * @param lowPT32 the value for HF_hy_27.low_p_t3_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setLowPT32(Float lowPT32) {
        this.lowPT32 = lowPT32;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.low_p_t4_2
     *
     * @return the value of HF_hy_27.low_p_t4_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getLowPT42() {
        return lowPT42;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.low_p_t4_2
     *
     * @param lowPT42 the value for HF_hy_27.low_p_t4_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setLowPT42(Float lowPT42) {
        this.lowPT42 = lowPT42;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.cpt_1_2
     *
     * @return the value of HF_hy_27.cpt_1_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getCpt12() {
        return cpt12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.cpt_1_2
     *
     * @param cpt12 the value for HF_hy_27.cpt_1_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setCpt12(Float cpt12) {
        this.cpt12 = cpt12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.cpt_2_2
     *
     * @return the value of HF_hy_27.cpt_2_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getCpt22() {
        return cpt22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.cpt_2_2
     *
     * @param cpt22 the value for HF_hy_27.cpt_2_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setCpt22(Float cpt22) {
        this.cpt22 = cpt22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.cpt_3_2
     *
     * @return the value of HF_hy_27.cpt_3_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getCpt32() {
        return cpt32;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.cpt_3_2
     *
     * @param cpt32 the value for HF_hy_27.cpt_3_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setCpt32(Float cpt32) {
        this.cpt32 = cpt32;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.cpt_4_2
     *
     * @return the value of HF_hy_27.cpt_4_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getCpt42() {
        return cpt42;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.cpt_4_2
     *
     * @param cpt42 the value for HF_hy_27.cpt_4_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setCpt42(Float cpt42) {
        this.cpt42 = cpt42;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.ncircuits_2
     *
     * @return the value of HF_hy_27.ncircuits_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getNcircuits2() {
        return ncircuits2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.ncircuits_2
     *
     * @param ncircuits2 the value for HF_hy_27.ncircuits_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setNcircuits2(Float ncircuits2) {
        this.ncircuits2 = ncircuits2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.ncompressors_2
     *
     * @return the value of HF_hy_27.ncompressors_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getNcompressors2() {
        return ncompressors2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.ncompressors_2
     *
     * @param ncompressors2 the value for HF_hy_27.ncompressors_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setNcompressors2(Float ncompressors2) {
        this.ncompressors2 = ncompressors2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.typeofcp_2
     *
     * @return the value of HF_hy_27.typeofcp_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getTypeofcp2() {
        return typeofcp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.typeofcp_2
     *
     * @param typeofcp2 the value for HF_hy_27.typeofcp_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setTypeofcp2(Float typeofcp2) {
        this.typeofcp2 = typeofcp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.unit_status_2
     *
     * @return the value of HF_hy_27.unit_status_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getUnitStatus2() {
        return unitStatus2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.unit_status_2
     *
     * @param unitStatus2 the value for HF_hy_27.unit_status_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setUnitStatus2(Float unitStatus2) {
        this.unitStatus2 = unitStatus2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.unit_t_status_2
     *
     * @return the value of HF_hy_27.unit_t_status_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getUnitTStatus2() {
        return unitTStatus2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.unit_t_status_2
     *
     * @param unitTStatus2 the value for HF_hy_27.unit_t_status_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setUnitTStatus2(Float unitTStatus2) {
        this.unitTStatus2 = unitTStatus2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.operatingmode_2
     *
     * @return the value of HF_hy_27.operatingmode_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getOperatingmode2() {
        return operatingmode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.operatingmode_2
     *
     * @param operatingmode2 the value for HF_hy_27.operatingmode_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setOperatingmode2(Float operatingmode2) {
        this.operatingmode2 = operatingmode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.cpofforon_1_2
     *
     * @return the value of HF_hy_27.cpofforon_1_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getCpofforon12() {
        return cpofforon12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.cpofforon_1_2
     *
     * @param cpofforon12 the value for HF_hy_27.cpofforon_1_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setCpofforon12(Float cpofforon12) {
        this.cpofforon12 = cpofforon12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.cpchiler_1_2
     *
     * @return the value of HF_hy_27.cpchiler_1_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getCpchiler12() {
        return cpchiler12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.cpchiler_1_2
     *
     * @param cpchiler12 the value for HF_hy_27.cpchiler_1_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setCpchiler12(Float cpchiler12) {
        this.cpchiler12 = cpchiler12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.cpheatpump_1_2
     *
     * @return the value of HF_hy_27.cpheatpump_1_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getCpheatpump12() {
        return cpheatpump12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.cpheatpump_1_2
     *
     * @param cpheatpump12 the value for HF_hy_27.cpheatpump_1_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setCpheatpump12(Float cpheatpump12) {
        this.cpheatpump12 = cpheatpump12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.cpofforon_2_2
     *
     * @return the value of HF_hy_27.cpofforon_2_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getCpofforon22() {
        return cpofforon22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.cpofforon_2_2
     *
     * @param cpofforon22 the value for HF_hy_27.cpofforon_2_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setCpofforon22(Float cpofforon22) {
        this.cpofforon22 = cpofforon22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.cpchiler_2_2
     *
     * @return the value of HF_hy_27.cpchiler_2_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getCpchiler22() {
        return cpchiler22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.cpchiler_2_2
     *
     * @param cpchiler22 the value for HF_hy_27.cpchiler_2_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setCpchiler22(Float cpchiler22) {
        this.cpchiler22 = cpchiler22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.cpheatpump_2_2
     *
     * @return the value of HF_hy_27.cpheatpump_2_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getCpheatpump22() {
        return cpheatpump22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.cpheatpump_2_2
     *
     * @param cpheatpump22 the value for HF_hy_27.cpheatpump_2_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setCpheatpump22(Float cpheatpump22) {
        this.cpheatpump22 = cpheatpump22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.cpofforon_3_2
     *
     * @return the value of HF_hy_27.cpofforon_3_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getCpofforon32() {
        return cpofforon32;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.cpofforon_3_2
     *
     * @param cpofforon32 the value for HF_hy_27.cpofforon_3_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setCpofforon32(Float cpofforon32) {
        this.cpofforon32 = cpofforon32;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.cpchiler_3_2
     *
     * @return the value of HF_hy_27.cpchiler_3_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getCpchiler32() {
        return cpchiler32;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.cpchiler_3_2
     *
     * @param cpchiler32 the value for HF_hy_27.cpchiler_3_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setCpchiler32(Float cpchiler32) {
        this.cpchiler32 = cpchiler32;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.cpheatpump_3_2
     *
     * @return the value of HF_hy_27.cpheatpump_3_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getCpheatpump32() {
        return cpheatpump32;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.cpheatpump_3_2
     *
     * @param cpheatpump32 the value for HF_hy_27.cpheatpump_3_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setCpheatpump32(Float cpheatpump32) {
        this.cpheatpump32 = cpheatpump32;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.cpofforon_4_2
     *
     * @return the value of HF_hy_27.cpofforon_4_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getCpofforon42() {
        return cpofforon42;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.cpofforon_4_2
     *
     * @param cpofforon42 the value for HF_hy_27.cpofforon_4_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setCpofforon42(Float cpofforon42) {
        this.cpofforon42 = cpofforon42;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.cpchiler_4_2
     *
     * @return the value of HF_hy_27.cpchiler_4_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getCpchiler42() {
        return cpchiler42;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.cpchiler_4_2
     *
     * @param cpchiler42 the value for HF_hy_27.cpchiler_4_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setCpchiler42(Float cpchiler42) {
        this.cpchiler42 = cpchiler42;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.cpheatpump_4_2
     *
     * @return the value of HF_hy_27.cpheatpump_4_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getCpheatpump42() {
        return cpheatpump42;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.cpheatpump_4_2
     *
     * @param cpheatpump42 the value for HF_hy_27.cpheatpump_4_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setCpheatpump42(Float cpheatpump42) {
        this.cpheatpump42 = cpheatpump42;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.ahcp_2
     *
     * @return the value of HF_hy_27.ahcp_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getAhcp2() {
        return ahcp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.ahcp_2
     *
     * @param ahcp2 the value for HF_hy_27.ahcp_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setAhcp2(Float ahcp2) {
        this.ahcp2 = ahcp2;
    }



    public Float getCtSp2() {
		return ctSp2;
	}

	public void setCtSp2(Float ctSp2) {
		this.ctSp2 = ctSp2;
	}

	public Float getHtSp2() {
		return htSp2;
	}

	public void setHtSp2(Float htSp2) {
		this.htSp2 = htSp2;
	}

	public Float getCtD2() {
		return ctD2;
	}

	public void setCtD2(Float ctD2) {
		this.ctD2 = ctD2;
	}

	public Float getApofct2() {
		return apofct2;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.apofct_2
     *
     * @param apofct2 the value for HF_hy_27.apofct_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setApofct2(Float apofct2) {
        this.apofct2 = apofct2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.apofct_h_2
     *
     * @return the value of HF_hy_27.apofct_h_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getApofctH2() {
        return apofctH2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.apofct_h_2
     *
     * @param apofctH2 the value for HF_hy_27.apofct_h_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setApofctH2(Float apofctH2) {
        this.apofctH2 = apofctH2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.hptd_2
     *
     * @return the value of HF_hy_27.hptd_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getHptd2() {
        return hptd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.hptd_2
     *
     * @param hptd2 the value for HF_hy_27.hptd_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setHptd2(Float hptd2) {
        this.hptd2 = hptd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.apofhpt_2
     *
     * @return the value of HF_hy_27.apofhpt_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getApofhpt2() {
        return apofhpt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.apofhpt_2
     *
     * @param apofhpt2 the value for HF_hy_27.apofhpt_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setApofhpt2(Float apofhpt2) {
        this.apofhpt2 = apofhpt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.apofhpt_h_2
     *
     * @return the value of HF_hy_27.apofhpt_h_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getApofhptH2() {
        return apofhptH2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.apofhpt_h_2
     *
     * @param apofhptH2 the value for HF_hy_27.apofhpt_h_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setApofhptH2(Float apofhptH2) {
        this.apofhptH2 = apofhptH2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.tlincm_2
     *
     * @return the value of HF_hy_27.tlincm_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getTlincm2() {
        return tlincm2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.tlincm_2
     *
     * @param tlincm2 the value for HF_hy_27.tlincm_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setTlincm2(Float tlincm2) {
        this.tlincm2 = tlincm2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_27.tlinhpm_2
     *
     * @return the value of HF_hy_27.tlinhpm_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public Float getTlinhpm2() {
        return tlinhpm2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_27.tlinhpm_2
     *
     * @param tlinhpm2 the value for HF_hy_27.tlinhpm_2
     *
     * @mbg.generated Wed Oct 11 14:23:53 CST 2017
     */
    public void setTlinhpm2(Float tlinhpm2) {
        this.tlinhpm2 = tlinhpm2;
    }

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getTimeNew() {
		return timeNew;
	}

	public void setTimeNew(String timeNew) {
		this.timeNew = timeNew;
	}
    
    
    
}