package com.firstCapacity.business.HeFeiPower.entity;

import java.io.Serializable;
import java.util.Date;

public class HF_hy_03 implements Serializable{
	
	private static final long serialVersionUID = 1L;
	
    private String startTime;
    
    private String endTime;
    
    private String timeNew;
	
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.Time
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_fd
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1Fd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_t3
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1T3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_h1
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1H1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_t4
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1T4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_h2
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1H2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_co2
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1Co2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_d1
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1D1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_d3
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1D3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_ffs5
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1Ffs5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_ffs6
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1Ffs6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_pfk
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1Pfk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_pfg
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1Pfg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_hfs5
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1Hfs5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_hfs6
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1Hfs6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_sf5
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1Sf5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_sf6
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1Sf6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_js2
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1Js2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_s1
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1S1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_s2
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1S2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_s3
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1S3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_s4
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1S4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_p1
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1P1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_p2
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1P2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_p3
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1P3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_p4
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1P4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_pg
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1Pg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_fmax
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1Fmax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_fmin
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1Fmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_jssx
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1Jssx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_jsxx
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1Jsxx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_xfmax
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1Xfmax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_xfmin
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1Xfmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_hfmax
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1Hfmax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_hfmin
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1Hfmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_sfsd
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1Sfsd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_p
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1P;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_i
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1I;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_d
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1D;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_co2_sd
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1Co2Sd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_1p
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf11p;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_1i
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf11i;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_1d
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf11d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_hfts
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1Hfts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_2p
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf12p;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_2i
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf12i;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1_2d
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf12d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1jsqdt
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1jsqdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1jstzt
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1jstzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1zlzr_am
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1zlzrAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1ys_am
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1ysAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1ddf_am
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1ddfAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1sjam
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1sjam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1djam
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1djam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1xff_am
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1xffAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1hff_am
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1hffAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_03.t2_rf_1jst_s
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    private Float t2Rf1jstS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.Time
     *
     * @return the value of HF_hy_03.Time
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.Time
     *
     * @param time the value for HF_hy_03.Time
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_fd
     *
     * @return the value of HF_hy_03.t2_rf_1_fd
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1Fd() {
        return t2Rf1Fd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_fd
     *
     * @param t2Rf1Fd the value for HF_hy_03.t2_rf_1_fd
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1Fd(Float t2Rf1Fd) {
        this.t2Rf1Fd = t2Rf1Fd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_t3
     *
     * @return the value of HF_hy_03.t2_rf_1_t3
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1T3() {
        return t2Rf1T3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_t3
     *
     * @param t2Rf1T3 the value for HF_hy_03.t2_rf_1_t3
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1T3(Float t2Rf1T3) {
        this.t2Rf1T3 = t2Rf1T3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_h1
     *
     * @return the value of HF_hy_03.t2_rf_1_h1
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1H1() {
        return t2Rf1H1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_h1
     *
     * @param t2Rf1H1 the value for HF_hy_03.t2_rf_1_h1
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1H1(Float t2Rf1H1) {
        this.t2Rf1H1 = t2Rf1H1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_t4
     *
     * @return the value of HF_hy_03.t2_rf_1_t4
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1T4() {
        return t2Rf1T4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_t4
     *
     * @param t2Rf1T4 the value for HF_hy_03.t2_rf_1_t4
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1T4(Float t2Rf1T4) {
        this.t2Rf1T4 = t2Rf1T4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_h2
     *
     * @return the value of HF_hy_03.t2_rf_1_h2
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1H2() {
        return t2Rf1H2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_h2
     *
     * @param t2Rf1H2 the value for HF_hy_03.t2_rf_1_h2
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1H2(Float t2Rf1H2) {
        this.t2Rf1H2 = t2Rf1H2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_co2
     *
     * @return the value of HF_hy_03.t2_rf_1_co2
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1Co2() {
        return t2Rf1Co2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_co2
     *
     * @param t2Rf1Co2 the value for HF_hy_03.t2_rf_1_co2
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1Co2(Float t2Rf1Co2) {
        this.t2Rf1Co2 = t2Rf1Co2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_d1
     *
     * @return the value of HF_hy_03.t2_rf_1_d1
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1D1() {
        return t2Rf1D1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_d1
     *
     * @param t2Rf1D1 the value for HF_hy_03.t2_rf_1_d1
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1D1(Float t2Rf1D1) {
        this.t2Rf1D1 = t2Rf1D1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_d3
     *
     * @return the value of HF_hy_03.t2_rf_1_d3
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1D3() {
        return t2Rf1D3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_d3
     *
     * @param t2Rf1D3 the value for HF_hy_03.t2_rf_1_d3
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1D3(Float t2Rf1D3) {
        this.t2Rf1D3 = t2Rf1D3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_ffs5
     *
     * @return the value of HF_hy_03.t2_rf_1_ffs5
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1Ffs5() {
        return t2Rf1Ffs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_ffs5
     *
     * @param t2Rf1Ffs5 the value for HF_hy_03.t2_rf_1_ffs5
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1Ffs5(Float t2Rf1Ffs5) {
        this.t2Rf1Ffs5 = t2Rf1Ffs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_ffs6
     *
     * @return the value of HF_hy_03.t2_rf_1_ffs6
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1Ffs6() {
        return t2Rf1Ffs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_ffs6
     *
     * @param t2Rf1Ffs6 the value for HF_hy_03.t2_rf_1_ffs6
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1Ffs6(Float t2Rf1Ffs6) {
        this.t2Rf1Ffs6 = t2Rf1Ffs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_pfk
     *
     * @return the value of HF_hy_03.t2_rf_1_pfk
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1Pfk() {
        return t2Rf1Pfk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_pfk
     *
     * @param t2Rf1Pfk the value for HF_hy_03.t2_rf_1_pfk
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1Pfk(Float t2Rf1Pfk) {
        this.t2Rf1Pfk = t2Rf1Pfk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_pfg
     *
     * @return the value of HF_hy_03.t2_rf_1_pfg
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1Pfg() {
        return t2Rf1Pfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_pfg
     *
     * @param t2Rf1Pfg the value for HF_hy_03.t2_rf_1_pfg
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1Pfg(Float t2Rf1Pfg) {
        this.t2Rf1Pfg = t2Rf1Pfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_hfs5
     *
     * @return the value of HF_hy_03.t2_rf_1_hfs5
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1Hfs5() {
        return t2Rf1Hfs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_hfs5
     *
     * @param t2Rf1Hfs5 the value for HF_hy_03.t2_rf_1_hfs5
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1Hfs5(Float t2Rf1Hfs5) {
        this.t2Rf1Hfs5 = t2Rf1Hfs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_hfs6
     *
     * @return the value of HF_hy_03.t2_rf_1_hfs6
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1Hfs6() {
        return t2Rf1Hfs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_hfs6
     *
     * @param t2Rf1Hfs6 the value for HF_hy_03.t2_rf_1_hfs6
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1Hfs6(Float t2Rf1Hfs6) {
        this.t2Rf1Hfs6 = t2Rf1Hfs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_sf5
     *
     * @return the value of HF_hy_03.t2_rf_1_sf5
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1Sf5() {
        return t2Rf1Sf5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_sf5
     *
     * @param t2Rf1Sf5 the value for HF_hy_03.t2_rf_1_sf5
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1Sf5(Float t2Rf1Sf5) {
        this.t2Rf1Sf5 = t2Rf1Sf5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_sf6
     *
     * @return the value of HF_hy_03.t2_rf_1_sf6
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1Sf6() {
        return t2Rf1Sf6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_sf6
     *
     * @param t2Rf1Sf6 the value for HF_hy_03.t2_rf_1_sf6
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1Sf6(Float t2Rf1Sf6) {
        this.t2Rf1Sf6 = t2Rf1Sf6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_js2
     *
     * @return the value of HF_hy_03.t2_rf_1_js2
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1Js2() {
        return t2Rf1Js2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_js2
     *
     * @param t2Rf1Js2 the value for HF_hy_03.t2_rf_1_js2
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1Js2(Float t2Rf1Js2) {
        this.t2Rf1Js2 = t2Rf1Js2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_s1
     *
     * @return the value of HF_hy_03.t2_rf_1_s1
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1S1() {
        return t2Rf1S1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_s1
     *
     * @param t2Rf1S1 the value for HF_hy_03.t2_rf_1_s1
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1S1(Float t2Rf1S1) {
        this.t2Rf1S1 = t2Rf1S1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_s2
     *
     * @return the value of HF_hy_03.t2_rf_1_s2
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1S2() {
        return t2Rf1S2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_s2
     *
     * @param t2Rf1S2 the value for HF_hy_03.t2_rf_1_s2
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1S2(Float t2Rf1S2) {
        this.t2Rf1S2 = t2Rf1S2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_s3
     *
     * @return the value of HF_hy_03.t2_rf_1_s3
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1S3() {
        return t2Rf1S3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_s3
     *
     * @param t2Rf1S3 the value for HF_hy_03.t2_rf_1_s3
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1S3(Float t2Rf1S3) {
        this.t2Rf1S3 = t2Rf1S3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_s4
     *
     * @return the value of HF_hy_03.t2_rf_1_s4
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1S4() {
        return t2Rf1S4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_s4
     *
     * @param t2Rf1S4 the value for HF_hy_03.t2_rf_1_s4
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1S4(Float t2Rf1S4) {
        this.t2Rf1S4 = t2Rf1S4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_p1
     *
     * @return the value of HF_hy_03.t2_rf_1_p1
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1P1() {
        return t2Rf1P1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_p1
     *
     * @param t2Rf1P1 the value for HF_hy_03.t2_rf_1_p1
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1P1(Float t2Rf1P1) {
        this.t2Rf1P1 = t2Rf1P1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_p2
     *
     * @return the value of HF_hy_03.t2_rf_1_p2
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1P2() {
        return t2Rf1P2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_p2
     *
     * @param t2Rf1P2 the value for HF_hy_03.t2_rf_1_p2
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1P2(Float t2Rf1P2) {
        this.t2Rf1P2 = t2Rf1P2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_p3
     *
     * @return the value of HF_hy_03.t2_rf_1_p3
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1P3() {
        return t2Rf1P3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_p3
     *
     * @param t2Rf1P3 the value for HF_hy_03.t2_rf_1_p3
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1P3(Float t2Rf1P3) {
        this.t2Rf1P3 = t2Rf1P3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_p4
     *
     * @return the value of HF_hy_03.t2_rf_1_p4
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1P4() {
        return t2Rf1P4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_p4
     *
     * @param t2Rf1P4 the value for HF_hy_03.t2_rf_1_p4
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1P4(Float t2Rf1P4) {
        this.t2Rf1P4 = t2Rf1P4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_pg
     *
     * @return the value of HF_hy_03.t2_rf_1_pg
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1Pg() {
        return t2Rf1Pg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_pg
     *
     * @param t2Rf1Pg the value for HF_hy_03.t2_rf_1_pg
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1Pg(Float t2Rf1Pg) {
        this.t2Rf1Pg = t2Rf1Pg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_fmax
     *
     * @return the value of HF_hy_03.t2_rf_1_fmax
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1Fmax() {
        return t2Rf1Fmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_fmax
     *
     * @param t2Rf1Fmax the value for HF_hy_03.t2_rf_1_fmax
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1Fmax(Float t2Rf1Fmax) {
        this.t2Rf1Fmax = t2Rf1Fmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_fmin
     *
     * @return the value of HF_hy_03.t2_rf_1_fmin
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1Fmin() {
        return t2Rf1Fmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_fmin
     *
     * @param t2Rf1Fmin the value for HF_hy_03.t2_rf_1_fmin
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1Fmin(Float t2Rf1Fmin) {
        this.t2Rf1Fmin = t2Rf1Fmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_jssx
     *
     * @return the value of HF_hy_03.t2_rf_1_jssx
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1Jssx() {
        return t2Rf1Jssx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_jssx
     *
     * @param t2Rf1Jssx the value for HF_hy_03.t2_rf_1_jssx
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1Jssx(Float t2Rf1Jssx) {
        this.t2Rf1Jssx = t2Rf1Jssx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_jsxx
     *
     * @return the value of HF_hy_03.t2_rf_1_jsxx
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1Jsxx() {
        return t2Rf1Jsxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_jsxx
     *
     * @param t2Rf1Jsxx the value for HF_hy_03.t2_rf_1_jsxx
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1Jsxx(Float t2Rf1Jsxx) {
        this.t2Rf1Jsxx = t2Rf1Jsxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_xfmax
     *
     * @return the value of HF_hy_03.t2_rf_1_xfmax
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1Xfmax() {
        return t2Rf1Xfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_xfmax
     *
     * @param t2Rf1Xfmax the value for HF_hy_03.t2_rf_1_xfmax
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1Xfmax(Float t2Rf1Xfmax) {
        this.t2Rf1Xfmax = t2Rf1Xfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_xfmin
     *
     * @return the value of HF_hy_03.t2_rf_1_xfmin
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1Xfmin() {
        return t2Rf1Xfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_xfmin
     *
     * @param t2Rf1Xfmin the value for HF_hy_03.t2_rf_1_xfmin
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1Xfmin(Float t2Rf1Xfmin) {
        this.t2Rf1Xfmin = t2Rf1Xfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_hfmax
     *
     * @return the value of HF_hy_03.t2_rf_1_hfmax
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1Hfmax() {
        return t2Rf1Hfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_hfmax
     *
     * @param t2Rf1Hfmax the value for HF_hy_03.t2_rf_1_hfmax
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1Hfmax(Float t2Rf1Hfmax) {
        this.t2Rf1Hfmax = t2Rf1Hfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_hfmin
     *
     * @return the value of HF_hy_03.t2_rf_1_hfmin
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1Hfmin() {
        return t2Rf1Hfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_hfmin
     *
     * @param t2Rf1Hfmin the value for HF_hy_03.t2_rf_1_hfmin
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1Hfmin(Float t2Rf1Hfmin) {
        this.t2Rf1Hfmin = t2Rf1Hfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_sfsd
     *
     * @return the value of HF_hy_03.t2_rf_1_sfsd
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1Sfsd() {
        return t2Rf1Sfsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_sfsd
     *
     * @param t2Rf1Sfsd the value for HF_hy_03.t2_rf_1_sfsd
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1Sfsd(Float t2Rf1Sfsd) {
        this.t2Rf1Sfsd = t2Rf1Sfsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_p
     *
     * @return the value of HF_hy_03.t2_rf_1_p
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1P() {
        return t2Rf1P;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_p
     *
     * @param t2Rf1P the value for HF_hy_03.t2_rf_1_p
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1P(Float t2Rf1P) {
        this.t2Rf1P = t2Rf1P;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_i
     *
     * @return the value of HF_hy_03.t2_rf_1_i
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1I() {
        return t2Rf1I;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_i
     *
     * @param t2Rf1I the value for HF_hy_03.t2_rf_1_i
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1I(Float t2Rf1I) {
        this.t2Rf1I = t2Rf1I;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_d
     *
     * @return the value of HF_hy_03.t2_rf_1_d
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1D() {
        return t2Rf1D;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_d
     *
     * @param t2Rf1D the value for HF_hy_03.t2_rf_1_d
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1D(Float t2Rf1D) {
        this.t2Rf1D = t2Rf1D;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_co2_sd
     *
     * @return the value of HF_hy_03.t2_rf_1_co2_sd
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1Co2Sd() {
        return t2Rf1Co2Sd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_co2_sd
     *
     * @param t2Rf1Co2Sd the value for HF_hy_03.t2_rf_1_co2_sd
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1Co2Sd(Float t2Rf1Co2Sd) {
        this.t2Rf1Co2Sd = t2Rf1Co2Sd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_1p
     *
     * @return the value of HF_hy_03.t2_rf_1_1p
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf11p() {
        return t2Rf11p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_1p
     *
     * @param t2Rf11p the value for HF_hy_03.t2_rf_1_1p
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf11p(Float t2Rf11p) {
        this.t2Rf11p = t2Rf11p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_1i
     *
     * @return the value of HF_hy_03.t2_rf_1_1i
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf11i() {
        return t2Rf11i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_1i
     *
     * @param t2Rf11i the value for HF_hy_03.t2_rf_1_1i
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf11i(Float t2Rf11i) {
        this.t2Rf11i = t2Rf11i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_1d
     *
     * @return the value of HF_hy_03.t2_rf_1_1d
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf11d() {
        return t2Rf11d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_1d
     *
     * @param t2Rf11d the value for HF_hy_03.t2_rf_1_1d
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf11d(Float t2Rf11d) {
        this.t2Rf11d = t2Rf11d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_hfts
     *
     * @return the value of HF_hy_03.t2_rf_1_hfts
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1Hfts() {
        return t2Rf1Hfts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_hfts
     *
     * @param t2Rf1Hfts the value for HF_hy_03.t2_rf_1_hfts
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1Hfts(Float t2Rf1Hfts) {
        this.t2Rf1Hfts = t2Rf1Hfts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_2p
     *
     * @return the value of HF_hy_03.t2_rf_1_2p
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf12p() {
        return t2Rf12p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_2p
     *
     * @param t2Rf12p the value for HF_hy_03.t2_rf_1_2p
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf12p(Float t2Rf12p) {
        this.t2Rf12p = t2Rf12p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_2i
     *
     * @return the value of HF_hy_03.t2_rf_1_2i
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf12i() {
        return t2Rf12i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_2i
     *
     * @param t2Rf12i the value for HF_hy_03.t2_rf_1_2i
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf12i(Float t2Rf12i) {
        this.t2Rf12i = t2Rf12i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1_2d
     *
     * @return the value of HF_hy_03.t2_rf_1_2d
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf12d() {
        return t2Rf12d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1_2d
     *
     * @param t2Rf12d the value for HF_hy_03.t2_rf_1_2d
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf12d(Float t2Rf12d) {
        this.t2Rf12d = t2Rf12d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1jsqdt
     *
     * @return the value of HF_hy_03.t2_rf_1jsqdt
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1jsqdt() {
        return t2Rf1jsqdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1jsqdt
     *
     * @param t2Rf1jsqdt the value for HF_hy_03.t2_rf_1jsqdt
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1jsqdt(Float t2Rf1jsqdt) {
        this.t2Rf1jsqdt = t2Rf1jsqdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1jstzt
     *
     * @return the value of HF_hy_03.t2_rf_1jstzt
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1jstzt() {
        return t2Rf1jstzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1jstzt
     *
     * @param t2Rf1jstzt the value for HF_hy_03.t2_rf_1jstzt
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1jstzt(Float t2Rf1jstzt) {
        this.t2Rf1jstzt = t2Rf1jstzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1zlzr_am
     *
     * @return the value of HF_hy_03.t2_rf_1zlzr_am
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1zlzrAm() {
        return t2Rf1zlzrAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1zlzr_am
     *
     * @param t2Rf1zlzrAm the value for HF_hy_03.t2_rf_1zlzr_am
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1zlzrAm(Float t2Rf1zlzrAm) {
        this.t2Rf1zlzrAm = t2Rf1zlzrAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1ys_am
     *
     * @return the value of HF_hy_03.t2_rf_1ys_am
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1ysAm() {
        return t2Rf1ysAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1ys_am
     *
     * @param t2Rf1ysAm the value for HF_hy_03.t2_rf_1ys_am
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1ysAm(Float t2Rf1ysAm) {
        this.t2Rf1ysAm = t2Rf1ysAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1ddf_am
     *
     * @return the value of HF_hy_03.t2_rf_1ddf_am
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1ddfAm() {
        return t2Rf1ddfAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1ddf_am
     *
     * @param t2Rf1ddfAm the value for HF_hy_03.t2_rf_1ddf_am
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1ddfAm(Float t2Rf1ddfAm) {
        this.t2Rf1ddfAm = t2Rf1ddfAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1sjam
     *
     * @return the value of HF_hy_03.t2_rf_1sjam
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1sjam() {
        return t2Rf1sjam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1sjam
     *
     * @param t2Rf1sjam the value for HF_hy_03.t2_rf_1sjam
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1sjam(Float t2Rf1sjam) {
        this.t2Rf1sjam = t2Rf1sjam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1djam
     *
     * @return the value of HF_hy_03.t2_rf_1djam
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1djam() {
        return t2Rf1djam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1djam
     *
     * @param t2Rf1djam the value for HF_hy_03.t2_rf_1djam
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1djam(Float t2Rf1djam) {
        this.t2Rf1djam = t2Rf1djam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1xff_am
     *
     * @return the value of HF_hy_03.t2_rf_1xff_am
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1xffAm() {
        return t2Rf1xffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1xff_am
     *
     * @param t2Rf1xffAm the value for HF_hy_03.t2_rf_1xff_am
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1xffAm(Float t2Rf1xffAm) {
        this.t2Rf1xffAm = t2Rf1xffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1hff_am
     *
     * @return the value of HF_hy_03.t2_rf_1hff_am
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1hffAm() {
        return t2Rf1hffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1hff_am
     *
     * @param t2Rf1hffAm the value for HF_hy_03.t2_rf_1hff_am
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1hffAm(Float t2Rf1hffAm) {
        this.t2Rf1hffAm = t2Rf1hffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_03.t2_rf_1jst_s
     *
     * @return the value of HF_hy_03.t2_rf_1jst_s
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public Float getT2Rf1jstS() {
        return t2Rf1jstS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_03.t2_rf_1jst_s
     *
     * @param t2Rf1jstS the value for HF_hy_03.t2_rf_1jst_s
     *
     * @mbg.generated Wed Oct 11 14:15:28 CST 2017
     */
    public void setT2Rf1jstS(Float t2Rf1jstS) {
        this.t2Rf1jstS = t2Rf1jstS;
    }

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getTimeNew() {
		return timeNew;
	}

	public void setTimeNew(String timeNew) {
		this.timeNew = timeNew;
	}
    
    
    
    
}