package com.firstCapacity.business.HeFeiPower.entity;

import java.io.Serializable;
import java.util.Date;

public class HF_hy_07 implements Serializable{
	
	
	private static final long serialVersionUID = 1L;
	
	
    private String startTime;
    
    private String endTime;
    
    private String timeNew;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.Time
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_fd
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1Fd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_t3
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1T3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_h1
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1H1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_t4
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1T4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_h2
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1H2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_co2
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1Co2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_d1
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1D1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_d3
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1D3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_ffs5
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1Ffs5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_ffs6
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1Ffs6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_pfk
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1Pfk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_pfg
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1Pfg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_hfs5
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1Hfs5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_hfs6
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1Hfs6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_sf5
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1Sf5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_sf6
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1Sf6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_js2
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1Js2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_s1
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1S1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_s2
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1S2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_s3
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1S3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_s4
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1S4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_p1
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1P1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_p2
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1P2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_p3
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1P3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_p4
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1P4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_pg
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1Pg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_fmax
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1Fmax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_fmin
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1Fmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_jssx
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1Jssx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_jsxx
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1Jsxx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_xfmax
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1Xfmax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_xfmin
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1Xfmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_hfmax
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1Hfmax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_hfmin
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1Hfmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_sfsd
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1Sfsd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_p
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1P;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_i
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1I;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_d
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1D;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_co2_sd
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1Co2Sd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_1p
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf11p;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_1i
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf11i;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_1d
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf11d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_hfts
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1Hfts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_2p
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf12p;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_2i
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf12i;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1_2d
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf12d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1jsqdt
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1jsqdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1jstzt
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1jstzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1zlzr_am
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1zlzrAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1ys_am
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1ysAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1ddf_am
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1ddfAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1sjam
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1sjam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1djam
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1djam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1xff_am
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1xffAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1hff_am
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1hffAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_07.t4_rf_1jst_s
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    private Float t4Rf1jstS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.Time
     *
     * @return the value of HF_hy_07.Time
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.Time
     *
     * @param time the value for HF_hy_07.Time
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_fd
     *
     * @return the value of HF_hy_07.t4_rf_1_fd
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1Fd() {
        return t4Rf1Fd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_fd
     *
     * @param t4Rf1Fd the value for HF_hy_07.t4_rf_1_fd
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1Fd(Float t4Rf1Fd) {
        this.t4Rf1Fd = t4Rf1Fd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_t3
     *
     * @return the value of HF_hy_07.t4_rf_1_t3
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1T3() {
        return t4Rf1T3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_t3
     *
     * @param t4Rf1T3 the value for HF_hy_07.t4_rf_1_t3
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1T3(Float t4Rf1T3) {
        this.t4Rf1T3 = t4Rf1T3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_h1
     *
     * @return the value of HF_hy_07.t4_rf_1_h1
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1H1() {
        return t4Rf1H1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_h1
     *
     * @param t4Rf1H1 the value for HF_hy_07.t4_rf_1_h1
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1H1(Float t4Rf1H1) {
        this.t4Rf1H1 = t4Rf1H1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_t4
     *
     * @return the value of HF_hy_07.t4_rf_1_t4
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1T4() {
        return t4Rf1T4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_t4
     *
     * @param t4Rf1T4 the value for HF_hy_07.t4_rf_1_t4
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1T4(Float t4Rf1T4) {
        this.t4Rf1T4 = t4Rf1T4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_h2
     *
     * @return the value of HF_hy_07.t4_rf_1_h2
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1H2() {
        return t4Rf1H2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_h2
     *
     * @param t4Rf1H2 the value for HF_hy_07.t4_rf_1_h2
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1H2(Float t4Rf1H2) {
        this.t4Rf1H2 = t4Rf1H2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_co2
     *
     * @return the value of HF_hy_07.t4_rf_1_co2
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1Co2() {
        return t4Rf1Co2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_co2
     *
     * @param t4Rf1Co2 the value for HF_hy_07.t4_rf_1_co2
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1Co2(Float t4Rf1Co2) {
        this.t4Rf1Co2 = t4Rf1Co2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_d1
     *
     * @return the value of HF_hy_07.t4_rf_1_d1
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1D1() {
        return t4Rf1D1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_d1
     *
     * @param t4Rf1D1 the value for HF_hy_07.t4_rf_1_d1
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1D1(Float t4Rf1D1) {
        this.t4Rf1D1 = t4Rf1D1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_d3
     *
     * @return the value of HF_hy_07.t4_rf_1_d3
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1D3() {
        return t4Rf1D3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_d3
     *
     * @param t4Rf1D3 the value for HF_hy_07.t4_rf_1_d3
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1D3(Float t4Rf1D3) {
        this.t4Rf1D3 = t4Rf1D3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_ffs5
     *
     * @return the value of HF_hy_07.t4_rf_1_ffs5
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1Ffs5() {
        return t4Rf1Ffs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_ffs5
     *
     * @param t4Rf1Ffs5 the value for HF_hy_07.t4_rf_1_ffs5
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1Ffs5(Float t4Rf1Ffs5) {
        this.t4Rf1Ffs5 = t4Rf1Ffs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_ffs6
     *
     * @return the value of HF_hy_07.t4_rf_1_ffs6
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1Ffs6() {
        return t4Rf1Ffs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_ffs6
     *
     * @param t4Rf1Ffs6 the value for HF_hy_07.t4_rf_1_ffs6
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1Ffs6(Float t4Rf1Ffs6) {
        this.t4Rf1Ffs6 = t4Rf1Ffs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_pfk
     *
     * @return the value of HF_hy_07.t4_rf_1_pfk
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1Pfk() {
        return t4Rf1Pfk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_pfk
     *
     * @param t4Rf1Pfk the value for HF_hy_07.t4_rf_1_pfk
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1Pfk(Float t4Rf1Pfk) {
        this.t4Rf1Pfk = t4Rf1Pfk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_pfg
     *
     * @return the value of HF_hy_07.t4_rf_1_pfg
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1Pfg() {
        return t4Rf1Pfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_pfg
     *
     * @param t4Rf1Pfg the value for HF_hy_07.t4_rf_1_pfg
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1Pfg(Float t4Rf1Pfg) {
        this.t4Rf1Pfg = t4Rf1Pfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_hfs5
     *
     * @return the value of HF_hy_07.t4_rf_1_hfs5
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1Hfs5() {
        return t4Rf1Hfs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_hfs5
     *
     * @param t4Rf1Hfs5 the value for HF_hy_07.t4_rf_1_hfs5
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1Hfs5(Float t4Rf1Hfs5) {
        this.t4Rf1Hfs5 = t4Rf1Hfs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_hfs6
     *
     * @return the value of HF_hy_07.t4_rf_1_hfs6
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1Hfs6() {
        return t4Rf1Hfs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_hfs6
     *
     * @param t4Rf1Hfs6 the value for HF_hy_07.t4_rf_1_hfs6
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1Hfs6(Float t4Rf1Hfs6) {
        this.t4Rf1Hfs6 = t4Rf1Hfs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_sf5
     *
     * @return the value of HF_hy_07.t4_rf_1_sf5
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1Sf5() {
        return t4Rf1Sf5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_sf5
     *
     * @param t4Rf1Sf5 the value for HF_hy_07.t4_rf_1_sf5
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1Sf5(Float t4Rf1Sf5) {
        this.t4Rf1Sf5 = t4Rf1Sf5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_sf6
     *
     * @return the value of HF_hy_07.t4_rf_1_sf6
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1Sf6() {
        return t4Rf1Sf6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_sf6
     *
     * @param t4Rf1Sf6 the value for HF_hy_07.t4_rf_1_sf6
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1Sf6(Float t4Rf1Sf6) {
        this.t4Rf1Sf6 = t4Rf1Sf6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_js2
     *
     * @return the value of HF_hy_07.t4_rf_1_js2
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1Js2() {
        return t4Rf1Js2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_js2
     *
     * @param t4Rf1Js2 the value for HF_hy_07.t4_rf_1_js2
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1Js2(Float t4Rf1Js2) {
        this.t4Rf1Js2 = t4Rf1Js2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_s1
     *
     * @return the value of HF_hy_07.t4_rf_1_s1
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1S1() {
        return t4Rf1S1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_s1
     *
     * @param t4Rf1S1 the value for HF_hy_07.t4_rf_1_s1
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1S1(Float t4Rf1S1) {
        this.t4Rf1S1 = t4Rf1S1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_s2
     *
     * @return the value of HF_hy_07.t4_rf_1_s2
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1S2() {
        return t4Rf1S2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_s2
     *
     * @param t4Rf1S2 the value for HF_hy_07.t4_rf_1_s2
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1S2(Float t4Rf1S2) {
        this.t4Rf1S2 = t4Rf1S2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_s3
     *
     * @return the value of HF_hy_07.t4_rf_1_s3
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1S3() {
        return t4Rf1S3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_s3
     *
     * @param t4Rf1S3 the value for HF_hy_07.t4_rf_1_s3
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1S3(Float t4Rf1S3) {
        this.t4Rf1S3 = t4Rf1S3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_s4
     *
     * @return the value of HF_hy_07.t4_rf_1_s4
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1S4() {
        return t4Rf1S4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_s4
     *
     * @param t4Rf1S4 the value for HF_hy_07.t4_rf_1_s4
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1S4(Float t4Rf1S4) {
        this.t4Rf1S4 = t4Rf1S4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_p1
     *
     * @return the value of HF_hy_07.t4_rf_1_p1
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1P1() {
        return t4Rf1P1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_p1
     *
     * @param t4Rf1P1 the value for HF_hy_07.t4_rf_1_p1
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1P1(Float t4Rf1P1) {
        this.t4Rf1P1 = t4Rf1P1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_p2
     *
     * @return the value of HF_hy_07.t4_rf_1_p2
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1P2() {
        return t4Rf1P2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_p2
     *
     * @param t4Rf1P2 the value for HF_hy_07.t4_rf_1_p2
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1P2(Float t4Rf1P2) {
        this.t4Rf1P2 = t4Rf1P2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_p3
     *
     * @return the value of HF_hy_07.t4_rf_1_p3
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1P3() {
        return t4Rf1P3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_p3
     *
     * @param t4Rf1P3 the value for HF_hy_07.t4_rf_1_p3
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1P3(Float t4Rf1P3) {
        this.t4Rf1P3 = t4Rf1P3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_p4
     *
     * @return the value of HF_hy_07.t4_rf_1_p4
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1P4() {
        return t4Rf1P4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_p4
     *
     * @param t4Rf1P4 the value for HF_hy_07.t4_rf_1_p4
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1P4(Float t4Rf1P4) {
        this.t4Rf1P4 = t4Rf1P4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_pg
     *
     * @return the value of HF_hy_07.t4_rf_1_pg
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1Pg() {
        return t4Rf1Pg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_pg
     *
     * @param t4Rf1Pg the value for HF_hy_07.t4_rf_1_pg
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1Pg(Float t4Rf1Pg) {
        this.t4Rf1Pg = t4Rf1Pg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_fmax
     *
     * @return the value of HF_hy_07.t4_rf_1_fmax
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1Fmax() {
        return t4Rf1Fmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_fmax
     *
     * @param t4Rf1Fmax the value for HF_hy_07.t4_rf_1_fmax
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1Fmax(Float t4Rf1Fmax) {
        this.t4Rf1Fmax = t4Rf1Fmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_fmin
     *
     * @return the value of HF_hy_07.t4_rf_1_fmin
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1Fmin() {
        return t4Rf1Fmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_fmin
     *
     * @param t4Rf1Fmin the value for HF_hy_07.t4_rf_1_fmin
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1Fmin(Float t4Rf1Fmin) {
        this.t4Rf1Fmin = t4Rf1Fmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_jssx
     *
     * @return the value of HF_hy_07.t4_rf_1_jssx
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1Jssx() {
        return t4Rf1Jssx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_jssx
     *
     * @param t4Rf1Jssx the value for HF_hy_07.t4_rf_1_jssx
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1Jssx(Float t4Rf1Jssx) {
        this.t4Rf1Jssx = t4Rf1Jssx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_jsxx
     *
     * @return the value of HF_hy_07.t4_rf_1_jsxx
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1Jsxx() {
        return t4Rf1Jsxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_jsxx
     *
     * @param t4Rf1Jsxx the value for HF_hy_07.t4_rf_1_jsxx
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1Jsxx(Float t4Rf1Jsxx) {
        this.t4Rf1Jsxx = t4Rf1Jsxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_xfmax
     *
     * @return the value of HF_hy_07.t4_rf_1_xfmax
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1Xfmax() {
        return t4Rf1Xfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_xfmax
     *
     * @param t4Rf1Xfmax the value for HF_hy_07.t4_rf_1_xfmax
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1Xfmax(Float t4Rf1Xfmax) {
        this.t4Rf1Xfmax = t4Rf1Xfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_xfmin
     *
     * @return the value of HF_hy_07.t4_rf_1_xfmin
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1Xfmin() {
        return t4Rf1Xfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_xfmin
     *
     * @param t4Rf1Xfmin the value for HF_hy_07.t4_rf_1_xfmin
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1Xfmin(Float t4Rf1Xfmin) {
        this.t4Rf1Xfmin = t4Rf1Xfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_hfmax
     *
     * @return the value of HF_hy_07.t4_rf_1_hfmax
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1Hfmax() {
        return t4Rf1Hfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_hfmax
     *
     * @param t4Rf1Hfmax the value for HF_hy_07.t4_rf_1_hfmax
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1Hfmax(Float t4Rf1Hfmax) {
        this.t4Rf1Hfmax = t4Rf1Hfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_hfmin
     *
     * @return the value of HF_hy_07.t4_rf_1_hfmin
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1Hfmin() {
        return t4Rf1Hfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_hfmin
     *
     * @param t4Rf1Hfmin the value for HF_hy_07.t4_rf_1_hfmin
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1Hfmin(Float t4Rf1Hfmin) {
        this.t4Rf1Hfmin = t4Rf1Hfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_sfsd
     *
     * @return the value of HF_hy_07.t4_rf_1_sfsd
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1Sfsd() {
        return t4Rf1Sfsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_sfsd
     *
     * @param t4Rf1Sfsd the value for HF_hy_07.t4_rf_1_sfsd
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1Sfsd(Float t4Rf1Sfsd) {
        this.t4Rf1Sfsd = t4Rf1Sfsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_p
     *
     * @return the value of HF_hy_07.t4_rf_1_p
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1P() {
        return t4Rf1P;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_p
     *
     * @param t4Rf1P the value for HF_hy_07.t4_rf_1_p
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1P(Float t4Rf1P) {
        this.t4Rf1P = t4Rf1P;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_i
     *
     * @return the value of HF_hy_07.t4_rf_1_i
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1I() {
        return t4Rf1I;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_i
     *
     * @param t4Rf1I the value for HF_hy_07.t4_rf_1_i
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1I(Float t4Rf1I) {
        this.t4Rf1I = t4Rf1I;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_d
     *
     * @return the value of HF_hy_07.t4_rf_1_d
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1D() {
        return t4Rf1D;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_d
     *
     * @param t4Rf1D the value for HF_hy_07.t4_rf_1_d
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1D(Float t4Rf1D) {
        this.t4Rf1D = t4Rf1D;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_co2_sd
     *
     * @return the value of HF_hy_07.t4_rf_1_co2_sd
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1Co2Sd() {
        return t4Rf1Co2Sd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_co2_sd
     *
     * @param t4Rf1Co2Sd the value for HF_hy_07.t4_rf_1_co2_sd
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1Co2Sd(Float t4Rf1Co2Sd) {
        this.t4Rf1Co2Sd = t4Rf1Co2Sd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_1p
     *
     * @return the value of HF_hy_07.t4_rf_1_1p
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf11p() {
        return t4Rf11p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_1p
     *
     * @param t4Rf11p the value for HF_hy_07.t4_rf_1_1p
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf11p(Float t4Rf11p) {
        this.t4Rf11p = t4Rf11p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_1i
     *
     * @return the value of HF_hy_07.t4_rf_1_1i
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf11i() {
        return t4Rf11i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_1i
     *
     * @param t4Rf11i the value for HF_hy_07.t4_rf_1_1i
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf11i(Float t4Rf11i) {
        this.t4Rf11i = t4Rf11i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_1d
     *
     * @return the value of HF_hy_07.t4_rf_1_1d
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf11d() {
        return t4Rf11d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_1d
     *
     * @param t4Rf11d the value for HF_hy_07.t4_rf_1_1d
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf11d(Float t4Rf11d) {
        this.t4Rf11d = t4Rf11d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_hfts
     *
     * @return the value of HF_hy_07.t4_rf_1_hfts
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1Hfts() {
        return t4Rf1Hfts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_hfts
     *
     * @param t4Rf1Hfts the value for HF_hy_07.t4_rf_1_hfts
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1Hfts(Float t4Rf1Hfts) {
        this.t4Rf1Hfts = t4Rf1Hfts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_2p
     *
     * @return the value of HF_hy_07.t4_rf_1_2p
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf12p() {
        return t4Rf12p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_2p
     *
     * @param t4Rf12p the value for HF_hy_07.t4_rf_1_2p
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf12p(Float t4Rf12p) {
        this.t4Rf12p = t4Rf12p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_2i
     *
     * @return the value of HF_hy_07.t4_rf_1_2i
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf12i() {
        return t4Rf12i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_2i
     *
     * @param t4Rf12i the value for HF_hy_07.t4_rf_1_2i
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf12i(Float t4Rf12i) {
        this.t4Rf12i = t4Rf12i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1_2d
     *
     * @return the value of HF_hy_07.t4_rf_1_2d
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf12d() {
        return t4Rf12d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1_2d
     *
     * @param t4Rf12d the value for HF_hy_07.t4_rf_1_2d
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf12d(Float t4Rf12d) {
        this.t4Rf12d = t4Rf12d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1jsqdt
     *
     * @return the value of HF_hy_07.t4_rf_1jsqdt
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1jsqdt() {
        return t4Rf1jsqdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1jsqdt
     *
     * @param t4Rf1jsqdt the value for HF_hy_07.t4_rf_1jsqdt
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1jsqdt(Float t4Rf1jsqdt) {
        this.t4Rf1jsqdt = t4Rf1jsqdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1jstzt
     *
     * @return the value of HF_hy_07.t4_rf_1jstzt
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1jstzt() {
        return t4Rf1jstzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1jstzt
     *
     * @param t4Rf1jstzt the value for HF_hy_07.t4_rf_1jstzt
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1jstzt(Float t4Rf1jstzt) {
        this.t4Rf1jstzt = t4Rf1jstzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1zlzr_am
     *
     * @return the value of HF_hy_07.t4_rf_1zlzr_am
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1zlzrAm() {
        return t4Rf1zlzrAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1zlzr_am
     *
     * @param t4Rf1zlzrAm the value for HF_hy_07.t4_rf_1zlzr_am
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1zlzrAm(Float t4Rf1zlzrAm) {
        this.t4Rf1zlzrAm = t4Rf1zlzrAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1ys_am
     *
     * @return the value of HF_hy_07.t4_rf_1ys_am
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1ysAm() {
        return t4Rf1ysAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1ys_am
     *
     * @param t4Rf1ysAm the value for HF_hy_07.t4_rf_1ys_am
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1ysAm(Float t4Rf1ysAm) {
        this.t4Rf1ysAm = t4Rf1ysAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1ddf_am
     *
     * @return the value of HF_hy_07.t4_rf_1ddf_am
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1ddfAm() {
        return t4Rf1ddfAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1ddf_am
     *
     * @param t4Rf1ddfAm the value for HF_hy_07.t4_rf_1ddf_am
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1ddfAm(Float t4Rf1ddfAm) {
        this.t4Rf1ddfAm = t4Rf1ddfAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1sjam
     *
     * @return the value of HF_hy_07.t4_rf_1sjam
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1sjam() {
        return t4Rf1sjam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1sjam
     *
     * @param t4Rf1sjam the value for HF_hy_07.t4_rf_1sjam
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1sjam(Float t4Rf1sjam) {
        this.t4Rf1sjam = t4Rf1sjam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1djam
     *
     * @return the value of HF_hy_07.t4_rf_1djam
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1djam() {
        return t4Rf1djam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1djam
     *
     * @param t4Rf1djam the value for HF_hy_07.t4_rf_1djam
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1djam(Float t4Rf1djam) {
        this.t4Rf1djam = t4Rf1djam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1xff_am
     *
     * @return the value of HF_hy_07.t4_rf_1xff_am
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1xffAm() {
        return t4Rf1xffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1xff_am
     *
     * @param t4Rf1xffAm the value for HF_hy_07.t4_rf_1xff_am
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1xffAm(Float t4Rf1xffAm) {
        this.t4Rf1xffAm = t4Rf1xffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1hff_am
     *
     * @return the value of HF_hy_07.t4_rf_1hff_am
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1hffAm() {
        return t4Rf1hffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1hff_am
     *
     * @param t4Rf1hffAm the value for HF_hy_07.t4_rf_1hff_am
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1hffAm(Float t4Rf1hffAm) {
        this.t4Rf1hffAm = t4Rf1hffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_07.t4_rf_1jst_s
     *
     * @return the value of HF_hy_07.t4_rf_1jst_s
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public Float getT4Rf1jstS() {
        return t4Rf1jstS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_07.t4_rf_1jst_s
     *
     * @param t4Rf1jstS the value for HF_hy_07.t4_rf_1jst_s
     *
     * @mbg.generated Wed Oct 11 14:16:48 CST 2017
     */
    public void setT4Rf1jstS(Float t4Rf1jstS) {
        this.t4Rf1jstS = t4Rf1jstS;
    }

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getTimeNew() {
		return timeNew;
	}

	public void setTimeNew(String timeNew) {
		this.timeNew = timeNew;
	}
    
    
    
}