package com.firstCapacity.business.HeFeiPower.entity;

import java.io.Serializable;
import java.util.Date;

public class HF_hy_05 implements Serializable{
	
	private static final long serialVersionUID = 1L;
	
	
    private String startTime;
    
    private String endTime;
    
    private String timeNew;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.Time
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_fd
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1Fd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_t3
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1T3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_h1
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1H1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_t4
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1T4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_h2
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1H2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_co2
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1Co2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_d1
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1D1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_d3
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1D3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_ffs5
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1Ffs5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_ffs6
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1Ffs6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_pfk
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1Pfk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_pfg
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1Pfg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_hfs5
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1Hfs5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_hfs6
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1Hfs6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_sf5
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1Sf5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_sf6
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1Sf6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_js2
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1Js2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_s1
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1S1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_s2
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1S2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_s3
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1S3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_s4
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1S4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_p1
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1P1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_p2
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1P2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_p3
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1P3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_p4
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1P4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_pg
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1Pg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_fmax
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1Fmax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_fmin
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1Fmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_jssx
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1Jssx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_jsxx
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1Jsxx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_xfmax
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1Xfmax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_xfmin
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1Xfmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_hfmax
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1Hfmax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_hfmin
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1Hfmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_sfsd
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1Sfsd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_p
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1P;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_i
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1I;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_d
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1D;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_co2_sd
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1Co2Sd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_1p
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf11p;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_1i
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf11i;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_1d
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf11d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_hfts
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1Hfts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_2p
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf12p;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_2i
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf12i;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1_2d
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf12d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1jsqdt
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1jsqdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1jstzt
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1jstzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1zlzr_am
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1zlzrAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1ys_am
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1ysAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1ddf_am
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1ddfAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1sjam
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1sjam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1djam
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1djam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1xff_am
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1xffAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1hff_am
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1hffAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_05.t3_rf_1jst_s
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    private Float t3Rf1jstS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.Time
     *
     * @return the value of HF_hy_05.Time
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.Time
     *
     * @param time the value for HF_hy_05.Time
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_fd
     *
     * @return the value of HF_hy_05.t3_rf_1_fd
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1Fd() {
        return t3Rf1Fd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_fd
     *
     * @param t3Rf1Fd the value for HF_hy_05.t3_rf_1_fd
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1Fd(Float t3Rf1Fd) {
        this.t3Rf1Fd = t3Rf1Fd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_t3
     *
     * @return the value of HF_hy_05.t3_rf_1_t3
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1T3() {
        return t3Rf1T3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_t3
     *
     * @param t3Rf1T3 the value for HF_hy_05.t3_rf_1_t3
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1T3(Float t3Rf1T3) {
        this.t3Rf1T3 = t3Rf1T3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_h1
     *
     * @return the value of HF_hy_05.t3_rf_1_h1
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1H1() {
        return t3Rf1H1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_h1
     *
     * @param t3Rf1H1 the value for HF_hy_05.t3_rf_1_h1
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1H1(Float t3Rf1H1) {
        this.t3Rf1H1 = t3Rf1H1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_t4
     *
     * @return the value of HF_hy_05.t3_rf_1_t4
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1T4() {
        return t3Rf1T4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_t4
     *
     * @param t3Rf1T4 the value for HF_hy_05.t3_rf_1_t4
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1T4(Float t3Rf1T4) {
        this.t3Rf1T4 = t3Rf1T4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_h2
     *
     * @return the value of HF_hy_05.t3_rf_1_h2
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1H2() {
        return t3Rf1H2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_h2
     *
     * @param t3Rf1H2 the value for HF_hy_05.t3_rf_1_h2
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1H2(Float t3Rf1H2) {
        this.t3Rf1H2 = t3Rf1H2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_co2
     *
     * @return the value of HF_hy_05.t3_rf_1_co2
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1Co2() {
        return t3Rf1Co2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_co2
     *
     * @param t3Rf1Co2 the value for HF_hy_05.t3_rf_1_co2
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1Co2(Float t3Rf1Co2) {
        this.t3Rf1Co2 = t3Rf1Co2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_d1
     *
     * @return the value of HF_hy_05.t3_rf_1_d1
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1D1() {
        return t3Rf1D1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_d1
     *
     * @param t3Rf1D1 the value for HF_hy_05.t3_rf_1_d1
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1D1(Float t3Rf1D1) {
        this.t3Rf1D1 = t3Rf1D1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_d3
     *
     * @return the value of HF_hy_05.t3_rf_1_d3
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1D3() {
        return t3Rf1D3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_d3
     *
     * @param t3Rf1D3 the value for HF_hy_05.t3_rf_1_d3
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1D3(Float t3Rf1D3) {
        this.t3Rf1D3 = t3Rf1D3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_ffs5
     *
     * @return the value of HF_hy_05.t3_rf_1_ffs5
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1Ffs5() {
        return t3Rf1Ffs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_ffs5
     *
     * @param t3Rf1Ffs5 the value for HF_hy_05.t3_rf_1_ffs5
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1Ffs5(Float t3Rf1Ffs5) {
        this.t3Rf1Ffs5 = t3Rf1Ffs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_ffs6
     *
     * @return the value of HF_hy_05.t3_rf_1_ffs6
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1Ffs6() {
        return t3Rf1Ffs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_ffs6
     *
     * @param t3Rf1Ffs6 the value for HF_hy_05.t3_rf_1_ffs6
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1Ffs6(Float t3Rf1Ffs6) {
        this.t3Rf1Ffs6 = t3Rf1Ffs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_pfk
     *
     * @return the value of HF_hy_05.t3_rf_1_pfk
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1Pfk() {
        return t3Rf1Pfk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_pfk
     *
     * @param t3Rf1Pfk the value for HF_hy_05.t3_rf_1_pfk
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1Pfk(Float t3Rf1Pfk) {
        this.t3Rf1Pfk = t3Rf1Pfk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_pfg
     *
     * @return the value of HF_hy_05.t3_rf_1_pfg
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1Pfg() {
        return t3Rf1Pfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_pfg
     *
     * @param t3Rf1Pfg the value for HF_hy_05.t3_rf_1_pfg
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1Pfg(Float t3Rf1Pfg) {
        this.t3Rf1Pfg = t3Rf1Pfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_hfs5
     *
     * @return the value of HF_hy_05.t3_rf_1_hfs5
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1Hfs5() {
        return t3Rf1Hfs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_hfs5
     *
     * @param t3Rf1Hfs5 the value for HF_hy_05.t3_rf_1_hfs5
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1Hfs5(Float t3Rf1Hfs5) {
        this.t3Rf1Hfs5 = t3Rf1Hfs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_hfs6
     *
     * @return the value of HF_hy_05.t3_rf_1_hfs6
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1Hfs6() {
        return t3Rf1Hfs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_hfs6
     *
     * @param t3Rf1Hfs6 the value for HF_hy_05.t3_rf_1_hfs6
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1Hfs6(Float t3Rf1Hfs6) {
        this.t3Rf1Hfs6 = t3Rf1Hfs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_sf5
     *
     * @return the value of HF_hy_05.t3_rf_1_sf5
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1Sf5() {
        return t3Rf1Sf5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_sf5
     *
     * @param t3Rf1Sf5 the value for HF_hy_05.t3_rf_1_sf5
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1Sf5(Float t3Rf1Sf5) {
        this.t3Rf1Sf5 = t3Rf1Sf5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_sf6
     *
     * @return the value of HF_hy_05.t3_rf_1_sf6
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1Sf6() {
        return t3Rf1Sf6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_sf6
     *
     * @param t3Rf1Sf6 the value for HF_hy_05.t3_rf_1_sf6
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1Sf6(Float t3Rf1Sf6) {
        this.t3Rf1Sf6 = t3Rf1Sf6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_js2
     *
     * @return the value of HF_hy_05.t3_rf_1_js2
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1Js2() {
        return t3Rf1Js2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_js2
     *
     * @param t3Rf1Js2 the value for HF_hy_05.t3_rf_1_js2
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1Js2(Float t3Rf1Js2) {
        this.t3Rf1Js2 = t3Rf1Js2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_s1
     *
     * @return the value of HF_hy_05.t3_rf_1_s1
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1S1() {
        return t3Rf1S1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_s1
     *
     * @param t3Rf1S1 the value for HF_hy_05.t3_rf_1_s1
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1S1(Float t3Rf1S1) {
        this.t3Rf1S1 = t3Rf1S1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_s2
     *
     * @return the value of HF_hy_05.t3_rf_1_s2
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1S2() {
        return t3Rf1S2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_s2
     *
     * @param t3Rf1S2 the value for HF_hy_05.t3_rf_1_s2
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1S2(Float t3Rf1S2) {
        this.t3Rf1S2 = t3Rf1S2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_s3
     *
     * @return the value of HF_hy_05.t3_rf_1_s3
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1S3() {
        return t3Rf1S3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_s3
     *
     * @param t3Rf1S3 the value for HF_hy_05.t3_rf_1_s3
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1S3(Float t3Rf1S3) {
        this.t3Rf1S3 = t3Rf1S3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_s4
     *
     * @return the value of HF_hy_05.t3_rf_1_s4
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1S4() {
        return t3Rf1S4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_s4
     *
     * @param t3Rf1S4 the value for HF_hy_05.t3_rf_1_s4
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1S4(Float t3Rf1S4) {
        this.t3Rf1S4 = t3Rf1S4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_p1
     *
     * @return the value of HF_hy_05.t3_rf_1_p1
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1P1() {
        return t3Rf1P1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_p1
     *
     * @param t3Rf1P1 the value for HF_hy_05.t3_rf_1_p1
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1P1(Float t3Rf1P1) {
        this.t3Rf1P1 = t3Rf1P1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_p2
     *
     * @return the value of HF_hy_05.t3_rf_1_p2
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1P2() {
        return t3Rf1P2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_p2
     *
     * @param t3Rf1P2 the value for HF_hy_05.t3_rf_1_p2
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1P2(Float t3Rf1P2) {
        this.t3Rf1P2 = t3Rf1P2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_p3
     *
     * @return the value of HF_hy_05.t3_rf_1_p3
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1P3() {
        return t3Rf1P3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_p3
     *
     * @param t3Rf1P3 the value for HF_hy_05.t3_rf_1_p3
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1P3(Float t3Rf1P3) {
        this.t3Rf1P3 = t3Rf1P3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_p4
     *
     * @return the value of HF_hy_05.t3_rf_1_p4
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1P4() {
        return t3Rf1P4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_p4
     *
     * @param t3Rf1P4 the value for HF_hy_05.t3_rf_1_p4
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1P4(Float t3Rf1P4) {
        this.t3Rf1P4 = t3Rf1P4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_pg
     *
     * @return the value of HF_hy_05.t3_rf_1_pg
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1Pg() {
        return t3Rf1Pg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_pg
     *
     * @param t3Rf1Pg the value for HF_hy_05.t3_rf_1_pg
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1Pg(Float t3Rf1Pg) {
        this.t3Rf1Pg = t3Rf1Pg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_fmax
     *
     * @return the value of HF_hy_05.t3_rf_1_fmax
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1Fmax() {
        return t3Rf1Fmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_fmax
     *
     * @param t3Rf1Fmax the value for HF_hy_05.t3_rf_1_fmax
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1Fmax(Float t3Rf1Fmax) {
        this.t3Rf1Fmax = t3Rf1Fmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_fmin
     *
     * @return the value of HF_hy_05.t3_rf_1_fmin
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1Fmin() {
        return t3Rf1Fmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_fmin
     *
     * @param t3Rf1Fmin the value for HF_hy_05.t3_rf_1_fmin
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1Fmin(Float t3Rf1Fmin) {
        this.t3Rf1Fmin = t3Rf1Fmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_jssx
     *
     * @return the value of HF_hy_05.t3_rf_1_jssx
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1Jssx() {
        return t3Rf1Jssx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_jssx
     *
     * @param t3Rf1Jssx the value for HF_hy_05.t3_rf_1_jssx
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1Jssx(Float t3Rf1Jssx) {
        this.t3Rf1Jssx = t3Rf1Jssx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_jsxx
     *
     * @return the value of HF_hy_05.t3_rf_1_jsxx
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1Jsxx() {
        return t3Rf1Jsxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_jsxx
     *
     * @param t3Rf1Jsxx the value for HF_hy_05.t3_rf_1_jsxx
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1Jsxx(Float t3Rf1Jsxx) {
        this.t3Rf1Jsxx = t3Rf1Jsxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_xfmax
     *
     * @return the value of HF_hy_05.t3_rf_1_xfmax
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1Xfmax() {
        return t3Rf1Xfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_xfmax
     *
     * @param t3Rf1Xfmax the value for HF_hy_05.t3_rf_1_xfmax
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1Xfmax(Float t3Rf1Xfmax) {
        this.t3Rf1Xfmax = t3Rf1Xfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_xfmin
     *
     * @return the value of HF_hy_05.t3_rf_1_xfmin
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1Xfmin() {
        return t3Rf1Xfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_xfmin
     *
     * @param t3Rf1Xfmin the value for HF_hy_05.t3_rf_1_xfmin
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1Xfmin(Float t3Rf1Xfmin) {
        this.t3Rf1Xfmin = t3Rf1Xfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_hfmax
     *
     * @return the value of HF_hy_05.t3_rf_1_hfmax
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1Hfmax() {
        return t3Rf1Hfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_hfmax
     *
     * @param t3Rf1Hfmax the value for HF_hy_05.t3_rf_1_hfmax
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1Hfmax(Float t3Rf1Hfmax) {
        this.t3Rf1Hfmax = t3Rf1Hfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_hfmin
     *
     * @return the value of HF_hy_05.t3_rf_1_hfmin
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1Hfmin() {
        return t3Rf1Hfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_hfmin
     *
     * @param t3Rf1Hfmin the value for HF_hy_05.t3_rf_1_hfmin
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1Hfmin(Float t3Rf1Hfmin) {
        this.t3Rf1Hfmin = t3Rf1Hfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_sfsd
     *
     * @return the value of HF_hy_05.t3_rf_1_sfsd
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1Sfsd() {
        return t3Rf1Sfsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_sfsd
     *
     * @param t3Rf1Sfsd the value for HF_hy_05.t3_rf_1_sfsd
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1Sfsd(Float t3Rf1Sfsd) {
        this.t3Rf1Sfsd = t3Rf1Sfsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_p
     *
     * @return the value of HF_hy_05.t3_rf_1_p
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1P() {
        return t3Rf1P;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_p
     *
     * @param t3Rf1P the value for HF_hy_05.t3_rf_1_p
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1P(Float t3Rf1P) {
        this.t3Rf1P = t3Rf1P;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_i
     *
     * @return the value of HF_hy_05.t3_rf_1_i
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1I() {
        return t3Rf1I;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_i
     *
     * @param t3Rf1I the value for HF_hy_05.t3_rf_1_i
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1I(Float t3Rf1I) {
        this.t3Rf1I = t3Rf1I;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_d
     *
     * @return the value of HF_hy_05.t3_rf_1_d
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1D() {
        return t3Rf1D;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_d
     *
     * @param t3Rf1D the value for HF_hy_05.t3_rf_1_d
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1D(Float t3Rf1D) {
        this.t3Rf1D = t3Rf1D;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_co2_sd
     *
     * @return the value of HF_hy_05.t3_rf_1_co2_sd
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1Co2Sd() {
        return t3Rf1Co2Sd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_co2_sd
     *
     * @param t3Rf1Co2Sd the value for HF_hy_05.t3_rf_1_co2_sd
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1Co2Sd(Float t3Rf1Co2Sd) {
        this.t3Rf1Co2Sd = t3Rf1Co2Sd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_1p
     *
     * @return the value of HF_hy_05.t3_rf_1_1p
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf11p() {
        return t3Rf11p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_1p
     *
     * @param t3Rf11p the value for HF_hy_05.t3_rf_1_1p
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf11p(Float t3Rf11p) {
        this.t3Rf11p = t3Rf11p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_1i
     *
     * @return the value of HF_hy_05.t3_rf_1_1i
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf11i() {
        return t3Rf11i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_1i
     *
     * @param t3Rf11i the value for HF_hy_05.t3_rf_1_1i
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf11i(Float t3Rf11i) {
        this.t3Rf11i = t3Rf11i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_1d
     *
     * @return the value of HF_hy_05.t3_rf_1_1d
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf11d() {
        return t3Rf11d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_1d
     *
     * @param t3Rf11d the value for HF_hy_05.t3_rf_1_1d
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf11d(Float t3Rf11d) {
        this.t3Rf11d = t3Rf11d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_hfts
     *
     * @return the value of HF_hy_05.t3_rf_1_hfts
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1Hfts() {
        return t3Rf1Hfts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_hfts
     *
     * @param t3Rf1Hfts the value for HF_hy_05.t3_rf_1_hfts
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1Hfts(Float t3Rf1Hfts) {
        this.t3Rf1Hfts = t3Rf1Hfts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_2p
     *
     * @return the value of HF_hy_05.t3_rf_1_2p
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf12p() {
        return t3Rf12p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_2p
     *
     * @param t3Rf12p the value for HF_hy_05.t3_rf_1_2p
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf12p(Float t3Rf12p) {
        this.t3Rf12p = t3Rf12p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_2i
     *
     * @return the value of HF_hy_05.t3_rf_1_2i
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf12i() {
        return t3Rf12i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_2i
     *
     * @param t3Rf12i the value for HF_hy_05.t3_rf_1_2i
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf12i(Float t3Rf12i) {
        this.t3Rf12i = t3Rf12i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1_2d
     *
     * @return the value of HF_hy_05.t3_rf_1_2d
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf12d() {
        return t3Rf12d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1_2d
     *
     * @param t3Rf12d the value for HF_hy_05.t3_rf_1_2d
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf12d(Float t3Rf12d) {
        this.t3Rf12d = t3Rf12d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1jsqdt
     *
     * @return the value of HF_hy_05.t3_rf_1jsqdt
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1jsqdt() {
        return t3Rf1jsqdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1jsqdt
     *
     * @param t3Rf1jsqdt the value for HF_hy_05.t3_rf_1jsqdt
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1jsqdt(Float t3Rf1jsqdt) {
        this.t3Rf1jsqdt = t3Rf1jsqdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1jstzt
     *
     * @return the value of HF_hy_05.t3_rf_1jstzt
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1jstzt() {
        return t3Rf1jstzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1jstzt
     *
     * @param t3Rf1jstzt the value for HF_hy_05.t3_rf_1jstzt
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1jstzt(Float t3Rf1jstzt) {
        this.t3Rf1jstzt = t3Rf1jstzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1zlzr_am
     *
     * @return the value of HF_hy_05.t3_rf_1zlzr_am
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1zlzrAm() {
        return t3Rf1zlzrAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1zlzr_am
     *
     * @param t3Rf1zlzrAm the value for HF_hy_05.t3_rf_1zlzr_am
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1zlzrAm(Float t3Rf1zlzrAm) {
        this.t3Rf1zlzrAm = t3Rf1zlzrAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1ys_am
     *
     * @return the value of HF_hy_05.t3_rf_1ys_am
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1ysAm() {
        return t3Rf1ysAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1ys_am
     *
     * @param t3Rf1ysAm the value for HF_hy_05.t3_rf_1ys_am
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1ysAm(Float t3Rf1ysAm) {
        this.t3Rf1ysAm = t3Rf1ysAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1ddf_am
     *
     * @return the value of HF_hy_05.t3_rf_1ddf_am
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1ddfAm() {
        return t3Rf1ddfAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1ddf_am
     *
     * @param t3Rf1ddfAm the value for HF_hy_05.t3_rf_1ddf_am
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1ddfAm(Float t3Rf1ddfAm) {
        this.t3Rf1ddfAm = t3Rf1ddfAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1sjam
     *
     * @return the value of HF_hy_05.t3_rf_1sjam
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1sjam() {
        return t3Rf1sjam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1sjam
     *
     * @param t3Rf1sjam the value for HF_hy_05.t3_rf_1sjam
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1sjam(Float t3Rf1sjam) {
        this.t3Rf1sjam = t3Rf1sjam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1djam
     *
     * @return the value of HF_hy_05.t3_rf_1djam
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1djam() {
        return t3Rf1djam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1djam
     *
     * @param t3Rf1djam the value for HF_hy_05.t3_rf_1djam
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1djam(Float t3Rf1djam) {
        this.t3Rf1djam = t3Rf1djam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1xff_am
     *
     * @return the value of HF_hy_05.t3_rf_1xff_am
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1xffAm() {
        return t3Rf1xffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1xff_am
     *
     * @param t3Rf1xffAm the value for HF_hy_05.t3_rf_1xff_am
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1xffAm(Float t3Rf1xffAm) {
        this.t3Rf1xffAm = t3Rf1xffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1hff_am
     *
     * @return the value of HF_hy_05.t3_rf_1hff_am
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1hffAm() {
        return t3Rf1hffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1hff_am
     *
     * @param t3Rf1hffAm the value for HF_hy_05.t3_rf_1hff_am
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1hffAm(Float t3Rf1hffAm) {
        this.t3Rf1hffAm = t3Rf1hffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_05.t3_rf_1jst_s
     *
     * @return the value of HF_hy_05.t3_rf_1jst_s
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public Float getT3Rf1jstS() {
        return t3Rf1jstS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_05.t3_rf_1jst_s
     *
     * @param t3Rf1jstS the value for HF_hy_05.t3_rf_1jst_s
     *
     * @mbg.generated Wed Oct 11 14:15:55 CST 2017
     */
    public void setT3Rf1jstS(Float t3Rf1jstS) {
        this.t3Rf1jstS = t3Rf1jstS;
    }

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getTimeNew() {
		return timeNew;
	}

	public void setTimeNew(String timeNew) {
		this.timeNew = timeNew;
	}
    
    
    
    
}