package com.firstCapacity.business.HeFeiPower.entity;

import java.io.Serializable;
import java.util.Date;

public class HF_hy_26 implements Serializable{
	
	
	private static final long serialVersionUID = 1L;
	
	
    private String startTime;
    
    private String endTime; 
    
    private String timeNew;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.Time
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.c_t_sp_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float ctSp1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.h_t_sp_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float htSp1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.cool_lwt_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float coolLwt1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.cool_ewt_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float coolEwt1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.cond_lwt_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float condLwt1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.cond_ewt_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float condEwt1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.high_p_t1_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float highPT11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.high_p_t2_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float highPT21;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.high_p_t3_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float highPT31;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.high_p_t4_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float highPT41;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.low_p_t1_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float lowPT11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.low_p_t2_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float lowPT21;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.low_p_t3_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float lowPT31;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.low_p_t4_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float lowPT41;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.cpt_1_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float cpt11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.cpt_2_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float cpt21;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.cpt_3_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float cpt31;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.cpt_4_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float cpt41;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.ncircuits_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float ncircuits1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.ncompressors_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float ncompressors1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.typeofcp_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float typeofcp1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.unit_status_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float unitStatus1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.unit_t_status
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float unitTStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.operatingmode_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float operatingmode1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.cpofforon_1_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float cpofforon11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.cpchiler_1_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float cpchiler11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.cpheatpump_1_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float cpheatpump11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.cpofforon_2_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float cpofforon21;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.cpchiler_2_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float cpchiler21;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.cpheatpump_2_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float cpheatpump21;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.cpofforon_3_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float cpofforon31;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.cpchiler_3_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float cpchiler31;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.cpheatpump_3_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float cpheatpump31;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.cpofforon_4_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float cpofforon41;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.cpchiler_4_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float cpchiler41;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.cpheatpump_4_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float cpheatpump41;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.ahcp_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float ahcp1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.c_t_d_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float ctD1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.apofct_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float apofct1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.apofct_h_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float apofctH1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.hptd_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float hptd1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.apofhpt_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float apofhpt1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.apofhpt_h_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float apofhptH1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.tlincm_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float tlincm1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_26.tlinhpm_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    private Float tlinhpm1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.Time
     *
     * @return the value of HF_hy_26.Time
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.Time
     *
     * @param time the value for HF_hy_26.Time
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.h_t_sp_1
     *
     * @return the value of HF_hy_26.h_t_sp_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
   
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.cool_lwt_1
     *
     * @return the value of HF_hy_26.cool_lwt_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getCoolLwt1() {
        return coolLwt1;
    }

    public Float getCtSp1() {
		return ctSp1;
	}

	public void setCtSp1(Float ctSp1) {
		this.ctSp1 = ctSp1;
	}

	public Float getHtSp1() {
		return htSp1;
	}

	public void setHtSp1(Float htSp1) {
		this.htSp1 = htSp1;
	}

	public Float getCtD1() {
		return ctD1;
	}

	public void setCtD1(Float ctD1) {
		this.ctD1 = ctD1;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.cool_lwt_1
     *
     * @param coolLwt1 the value for HF_hy_26.cool_lwt_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setCoolLwt1(Float coolLwt1) {
        this.coolLwt1 = coolLwt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.cool_ewt_1
     *
     * @return the value of HF_hy_26.cool_ewt_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getCoolEwt1() {
        return coolEwt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.cool_ewt_1
     *
     * @param coolEwt1 the value for HF_hy_26.cool_ewt_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setCoolEwt1(Float coolEwt1) {
        this.coolEwt1 = coolEwt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.cond_lwt_1
     *
     * @return the value of HF_hy_26.cond_lwt_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getCondLwt1() {
        return condLwt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.cond_lwt_1
     *
     * @param condLwt1 the value for HF_hy_26.cond_lwt_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setCondLwt1(Float condLwt1) {
        this.condLwt1 = condLwt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.cond_ewt_1
     *
     * @return the value of HF_hy_26.cond_ewt_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getCondEwt1() {
        return condEwt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.cond_ewt_1
     *
     * @param condEwt1 the value for HF_hy_26.cond_ewt_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setCondEwt1(Float condEwt1) {
        this.condEwt1 = condEwt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.high_p_t1_1
     *
     * @return the value of HF_hy_26.high_p_t1_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getHighPT11() {
        return highPT11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.high_p_t1_1
     *
     * @param highPT11 the value for HF_hy_26.high_p_t1_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setHighPT11(Float highPT11) {
        this.highPT11 = highPT11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.high_p_t2_1
     *
     * @return the value of HF_hy_26.high_p_t2_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getHighPT21() {
        return highPT21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.high_p_t2_1
     *
     * @param highPT21 the value for HF_hy_26.high_p_t2_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setHighPT21(Float highPT21) {
        this.highPT21 = highPT21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.high_p_t3_1
     *
     * @return the value of HF_hy_26.high_p_t3_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getHighPT31() {
        return highPT31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.high_p_t3_1
     *
     * @param highPT31 the value for HF_hy_26.high_p_t3_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setHighPT31(Float highPT31) {
        this.highPT31 = highPT31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.high_p_t4_1
     *
     * @return the value of HF_hy_26.high_p_t4_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getHighPT41() {
        return highPT41;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.high_p_t4_1
     *
     * @param highPT41 the value for HF_hy_26.high_p_t4_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setHighPT41(Float highPT41) {
        this.highPT41 = highPT41;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.low_p_t1_1
     *
     * @return the value of HF_hy_26.low_p_t1_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getLowPT11() {
        return lowPT11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.low_p_t1_1
     *
     * @param lowPT11 the value for HF_hy_26.low_p_t1_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setLowPT11(Float lowPT11) {
        this.lowPT11 = lowPT11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.low_p_t2_1
     *
     * @return the value of HF_hy_26.low_p_t2_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getLowPT21() {
        return lowPT21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.low_p_t2_1
     *
     * @param lowPT21 the value for HF_hy_26.low_p_t2_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setLowPT21(Float lowPT21) {
        this.lowPT21 = lowPT21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.low_p_t3_1
     *
     * @return the value of HF_hy_26.low_p_t3_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getLowPT31() {
        return lowPT31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.low_p_t3_1
     *
     * @param lowPT31 the value for HF_hy_26.low_p_t3_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setLowPT31(Float lowPT31) {
        this.lowPT31 = lowPT31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.low_p_t4_1
     *
     * @return the value of HF_hy_26.low_p_t4_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getLowPT41() {
        return lowPT41;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.low_p_t4_1
     *
     * @param lowPT41 the value for HF_hy_26.low_p_t4_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setLowPT41(Float lowPT41) {
        this.lowPT41 = lowPT41;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.cpt_1_1
     *
     * @return the value of HF_hy_26.cpt_1_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getCpt11() {
        return cpt11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.cpt_1_1
     *
     * @param cpt11 the value for HF_hy_26.cpt_1_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setCpt11(Float cpt11) {
        this.cpt11 = cpt11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.cpt_2_1
     *
     * @return the value of HF_hy_26.cpt_2_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getCpt21() {
        return cpt21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.cpt_2_1
     *
     * @param cpt21 the value for HF_hy_26.cpt_2_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setCpt21(Float cpt21) {
        this.cpt21 = cpt21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.cpt_3_1
     *
     * @return the value of HF_hy_26.cpt_3_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getCpt31() {
        return cpt31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.cpt_3_1
     *
     * @param cpt31 the value for HF_hy_26.cpt_3_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setCpt31(Float cpt31) {
        this.cpt31 = cpt31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.cpt_4_1
     *
     * @return the value of HF_hy_26.cpt_4_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getCpt41() {
        return cpt41;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.cpt_4_1
     *
     * @param cpt41 the value for HF_hy_26.cpt_4_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setCpt41(Float cpt41) {
        this.cpt41 = cpt41;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.ncircuits_1
     *
     * @return the value of HF_hy_26.ncircuits_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getNcircuits1() {
        return ncircuits1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.ncircuits_1
     *
     * @param ncircuits1 the value for HF_hy_26.ncircuits_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setNcircuits1(Float ncircuits1) {
        this.ncircuits1 = ncircuits1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.ncompressors_1
     *
     * @return the value of HF_hy_26.ncompressors_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getNcompressors1() {
        return ncompressors1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.ncompressors_1
     *
     * @param ncompressors1 the value for HF_hy_26.ncompressors_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setNcompressors1(Float ncompressors1) {
        this.ncompressors1 = ncompressors1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.typeofcp_1
     *
     * @return the value of HF_hy_26.typeofcp_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getTypeofcp1() {
        return typeofcp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.typeofcp_1
     *
     * @param typeofcp1 the value for HF_hy_26.typeofcp_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setTypeofcp1(Float typeofcp1) {
        this.typeofcp1 = typeofcp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.unit_status_1
     *
     * @return the value of HF_hy_26.unit_status_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getUnitStatus1() {
        return unitStatus1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.unit_status_1
     *
     * @param unitStatus1 the value for HF_hy_26.unit_status_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setUnitStatus1(Float unitStatus1) {
        this.unitStatus1 = unitStatus1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.unit_t_status
     *
     * @return the value of HF_hy_26.unit_t_status
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getUnitTStatus() {
        return unitTStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.unit_t_status
     *
     * @param unitTStatus the value for HF_hy_26.unit_t_status
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setUnitTStatus(Float unitTStatus) {
        this.unitTStatus = unitTStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.operatingmode_1
     *
     * @return the value of HF_hy_26.operatingmode_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getOperatingmode1() {
        return operatingmode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.operatingmode_1
     *
     * @param operatingmode1 the value for HF_hy_26.operatingmode_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setOperatingmode1(Float operatingmode1) {
        this.operatingmode1 = operatingmode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.cpofforon_1_1
     *
     * @return the value of HF_hy_26.cpofforon_1_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getCpofforon11() {
        return cpofforon11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.cpofforon_1_1
     *
     * @param cpofforon11 the value for HF_hy_26.cpofforon_1_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setCpofforon11(Float cpofforon11) {
        this.cpofforon11 = cpofforon11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.cpchiler_1_1
     *
     * @return the value of HF_hy_26.cpchiler_1_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getCpchiler11() {
        return cpchiler11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.cpchiler_1_1
     *
     * @param cpchiler11 the value for HF_hy_26.cpchiler_1_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setCpchiler11(Float cpchiler11) {
        this.cpchiler11 = cpchiler11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.cpheatpump_1_1
     *
     * @return the value of HF_hy_26.cpheatpump_1_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getCpheatpump11() {
        return cpheatpump11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.cpheatpump_1_1
     *
     * @param cpheatpump11 the value for HF_hy_26.cpheatpump_1_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setCpheatpump11(Float cpheatpump11) {
        this.cpheatpump11 = cpheatpump11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.cpofforon_2_1
     *
     * @return the value of HF_hy_26.cpofforon_2_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getCpofforon21() {
        return cpofforon21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.cpofforon_2_1
     *
     * @param cpofforon21 the value for HF_hy_26.cpofforon_2_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setCpofforon21(Float cpofforon21) {
        this.cpofforon21 = cpofforon21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.cpchiler_2_1
     *
     * @return the value of HF_hy_26.cpchiler_2_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getCpchiler21() {
        return cpchiler21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.cpchiler_2_1
     *
     * @param cpchiler21 the value for HF_hy_26.cpchiler_2_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setCpchiler21(Float cpchiler21) {
        this.cpchiler21 = cpchiler21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.cpheatpump_2_1
     *
     * @return the value of HF_hy_26.cpheatpump_2_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getCpheatpump21() {
        return cpheatpump21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.cpheatpump_2_1
     *
     * @param cpheatpump21 the value for HF_hy_26.cpheatpump_2_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setCpheatpump21(Float cpheatpump21) {
        this.cpheatpump21 = cpheatpump21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.cpofforon_3_1
     *
     * @return the value of HF_hy_26.cpofforon_3_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getCpofforon31() {
        return cpofforon31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.cpofforon_3_1
     *
     * @param cpofforon31 the value for HF_hy_26.cpofforon_3_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setCpofforon31(Float cpofforon31) {
        this.cpofforon31 = cpofforon31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.cpchiler_3_1
     *
     * @return the value of HF_hy_26.cpchiler_3_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getCpchiler31() {
        return cpchiler31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.cpchiler_3_1
     *
     * @param cpchiler31 the value for HF_hy_26.cpchiler_3_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setCpchiler31(Float cpchiler31) {
        this.cpchiler31 = cpchiler31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.cpheatpump_3_1
     *
     * @return the value of HF_hy_26.cpheatpump_3_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getCpheatpump31() {
        return cpheatpump31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.cpheatpump_3_1
     *
     * @param cpheatpump31 the value for HF_hy_26.cpheatpump_3_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setCpheatpump31(Float cpheatpump31) {
        this.cpheatpump31 = cpheatpump31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.cpofforon_4_1
     *
     * @return the value of HF_hy_26.cpofforon_4_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getCpofforon41() {
        return cpofforon41;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.cpofforon_4_1
     *
     * @param cpofforon41 the value for HF_hy_26.cpofforon_4_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setCpofforon41(Float cpofforon41) {
        this.cpofforon41 = cpofforon41;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.cpchiler_4_1
     *
     * @return the value of HF_hy_26.cpchiler_4_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getCpchiler41() {
        return cpchiler41;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.cpchiler_4_1
     *
     * @param cpchiler41 the value for HF_hy_26.cpchiler_4_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setCpchiler41(Float cpchiler41) {
        this.cpchiler41 = cpchiler41;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.cpheatpump_4_1
     *
     * @return the value of HF_hy_26.cpheatpump_4_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getCpheatpump41() {
        return cpheatpump41;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.cpheatpump_4_1
     *
     * @param cpheatpump41 the value for HF_hy_26.cpheatpump_4_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setCpheatpump41(Float cpheatpump41) {
        this.cpheatpump41 = cpheatpump41;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.ahcp_1
     *
     * @return the value of HF_hy_26.ahcp_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getAhcp1() {
        return ahcp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.ahcp_1
     *
     * @param ahcp1 the value for HF_hy_26.ahcp_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setAhcp1(Float ahcp1) {
        this.ahcp1 = ahcp1;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.apofct_1
     *
     * @return the value of HF_hy_26.apofct_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getApofct1() {
        return apofct1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.apofct_1
     *
     * @param apofct1 the value for HF_hy_26.apofct_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setApofct1(Float apofct1) {
        this.apofct1 = apofct1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.apofct_h_1
     *
     * @return the value of HF_hy_26.apofct_h_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getApofctH1() {
        return apofctH1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.apofct_h_1
     *
     * @param apofctH1 the value for HF_hy_26.apofct_h_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setApofctH1(Float apofctH1) {
        this.apofctH1 = apofctH1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.hptd_1
     *
     * @return the value of HF_hy_26.hptd_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getHptd1() {
        return hptd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.hptd_1
     *
     * @param hptd1 the value for HF_hy_26.hptd_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setHptd1(Float hptd1) {
        this.hptd1 = hptd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.apofhpt_1
     *
     * @return the value of HF_hy_26.apofhpt_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getApofhpt1() {
        return apofhpt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.apofhpt_1
     *
     * @param apofhpt1 the value for HF_hy_26.apofhpt_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setApofhpt1(Float apofhpt1) {
        this.apofhpt1 = apofhpt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.apofhpt_h_1
     *
     * @return the value of HF_hy_26.apofhpt_h_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getApofhptH1() {
        return apofhptH1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.apofhpt_h_1
     *
     * @param apofhptH1 the value for HF_hy_26.apofhpt_h_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setApofhptH1(Float apofhptH1) {
        this.apofhptH1 = apofhptH1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.tlincm_1
     *
     * @return the value of HF_hy_26.tlincm_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getTlincm1() {
        return tlincm1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.tlincm_1
     *
     * @param tlincm1 the value for HF_hy_26.tlincm_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setTlincm1(Float tlincm1) {
        this.tlincm1 = tlincm1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_26.tlinhpm_1
     *
     * @return the value of HF_hy_26.tlinhpm_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public Float getTlinhpm1() {
        return tlinhpm1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_26.tlinhpm_1
     *
     * @param tlinhpm1 the value for HF_hy_26.tlinhpm_1
     *
     * @mbg.generated Wed Oct 11 14:23:40 CST 2017
     */
    public void setTlinhpm1(Float tlinhpm1) {
        this.tlinhpm1 = tlinhpm1;
    }

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getTimeNew() {
		return timeNew;
	}

	public void setTimeNew(String timeNew) {
		this.timeNew = timeNew;
	}
    
    
    
}