package com.firstCapacity.business.HeFeiPower.entity;

import java.io.Serializable;
import java.util.Date;

public class HF_hy_02 implements Serializable{
	
	private static final long serialVersionUID = 1L;
	
    private String startTime;
    
    private String endTime;
    
    private String timeNew;
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.Time
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_fd
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11Fd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_t3
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11T3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_h1
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11H1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_t4
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11T4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_h2
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11H2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_co2
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11Co2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_d1
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11D1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_d3
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11D3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_ffs5
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11Ffs5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_ffs6
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11Ffs6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_pfk
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11Pfk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_pfg
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11Pfg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_hfs5
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11Hfs5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_hfs6
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11Hfs6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_sf5
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11Sf5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_sf6
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11Sf6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_js2
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11Js2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_s1
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11S1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_s2
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11S2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_s3
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11S3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_s4
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11S4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_p1
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11P1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_p2
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11P2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_p3
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11P3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_p4
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11P4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_pg
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11Pg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_fmax
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11Fmax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_fmin
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11Fmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_jssx
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11Jssx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_jsxx
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11Jsxx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_xfmax
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11Xfmax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_xfmin
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11Xfmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_hfmax
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11Hfmax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_hfmin
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11Hfmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_sfsd
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11Sfsd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_p
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11P;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_i
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11I;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_d
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11D;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_co2_sd
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11Co2Sd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_1p
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B111p;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_1i
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B111i;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_1d
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B111d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_hfts
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11Hfts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_2p
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B112p;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_2i
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B112i;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1_2d
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B112d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1jsqdt
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11jsqdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1jstzt
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11jstzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1zlzr_am
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11zlzrAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1ys_am
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11ysAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1ddf_am
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11ddfAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1sjam
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11sjam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1djam
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11djam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1xff_am
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11xffAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1hff_am
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11hffAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_02.t1_b1_1jst_s
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    private Float t1B11jstS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.Time
     *
     * @return the value of HF_hy_02.Time
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.Time
     *
     * @param time the value for HF_hy_02.Time
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_fd
     *
     * @return the value of HF_hy_02.t1_b1_1_fd
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11Fd() {
        return t1B11Fd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_fd
     *
     * @param t1B11Fd the value for HF_hy_02.t1_b1_1_fd
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11Fd(Float t1B11Fd) {
        this.t1B11Fd = t1B11Fd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_t3
     *
     * @return the value of HF_hy_02.t1_b1_1_t3
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11T3() {
        return t1B11T3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_t3
     *
     * @param t1B11T3 the value for HF_hy_02.t1_b1_1_t3
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11T3(Float t1B11T3) {
        this.t1B11T3 = t1B11T3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_h1
     *
     * @return the value of HF_hy_02.t1_b1_1_h1
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11H1() {
        return t1B11H1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_h1
     *
     * @param t1B11H1 the value for HF_hy_02.t1_b1_1_h1
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11H1(Float t1B11H1) {
        this.t1B11H1 = t1B11H1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_t4
     *
     * @return the value of HF_hy_02.t1_b1_1_t4
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11T4() {
        return t1B11T4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_t4
     *
     * @param t1B11T4 the value for HF_hy_02.t1_b1_1_t4
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11T4(Float t1B11T4) {
        this.t1B11T4 = t1B11T4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_h2
     *
     * @return the value of HF_hy_02.t1_b1_1_h2
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11H2() {
        return t1B11H2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_h2
     *
     * @param t1B11H2 the value for HF_hy_02.t1_b1_1_h2
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11H2(Float t1B11H2) {
        this.t1B11H2 = t1B11H2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_co2
     *
     * @return the value of HF_hy_02.t1_b1_1_co2
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11Co2() {
        return t1B11Co2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_co2
     *
     * @param t1B11Co2 the value for HF_hy_02.t1_b1_1_co2
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11Co2(Float t1B11Co2) {
        this.t1B11Co2 = t1B11Co2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_d1
     *
     * @return the value of HF_hy_02.t1_b1_1_d1
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11D1() {
        return t1B11D1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_d1
     *
     * @param t1B11D1 the value for HF_hy_02.t1_b1_1_d1
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11D1(Float t1B11D1) {
        this.t1B11D1 = t1B11D1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_d3
     *
     * @return the value of HF_hy_02.t1_b1_1_d3
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11D3() {
        return t1B11D3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_d3
     *
     * @param t1B11D3 the value for HF_hy_02.t1_b1_1_d3
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11D3(Float t1B11D3) {
        this.t1B11D3 = t1B11D3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_ffs5
     *
     * @return the value of HF_hy_02.t1_b1_1_ffs5
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11Ffs5() {
        return t1B11Ffs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_ffs5
     *
     * @param t1B11Ffs5 the value for HF_hy_02.t1_b1_1_ffs5
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11Ffs5(Float t1B11Ffs5) {
        this.t1B11Ffs5 = t1B11Ffs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_ffs6
     *
     * @return the value of HF_hy_02.t1_b1_1_ffs6
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11Ffs6() {
        return t1B11Ffs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_ffs6
     *
     * @param t1B11Ffs6 the value for HF_hy_02.t1_b1_1_ffs6
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11Ffs6(Float t1B11Ffs6) {
        this.t1B11Ffs6 = t1B11Ffs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_pfk
     *
     * @return the value of HF_hy_02.t1_b1_1_pfk
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11Pfk() {
        return t1B11Pfk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_pfk
     *
     * @param t1B11Pfk the value for HF_hy_02.t1_b1_1_pfk
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11Pfk(Float t1B11Pfk) {
        this.t1B11Pfk = t1B11Pfk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_pfg
     *
     * @return the value of HF_hy_02.t1_b1_1_pfg
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11Pfg() {
        return t1B11Pfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_pfg
     *
     * @param t1B11Pfg the value for HF_hy_02.t1_b1_1_pfg
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11Pfg(Float t1B11Pfg) {
        this.t1B11Pfg = t1B11Pfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_hfs5
     *
     * @return the value of HF_hy_02.t1_b1_1_hfs5
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11Hfs5() {
        return t1B11Hfs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_hfs5
     *
     * @param t1B11Hfs5 the value for HF_hy_02.t1_b1_1_hfs5
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11Hfs5(Float t1B11Hfs5) {
        this.t1B11Hfs5 = t1B11Hfs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_hfs6
     *
     * @return the value of HF_hy_02.t1_b1_1_hfs6
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11Hfs6() {
        return t1B11Hfs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_hfs6
     *
     * @param t1B11Hfs6 the value for HF_hy_02.t1_b1_1_hfs6
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11Hfs6(Float t1B11Hfs6) {
        this.t1B11Hfs6 = t1B11Hfs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_sf5
     *
     * @return the value of HF_hy_02.t1_b1_1_sf5
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11Sf5() {
        return t1B11Sf5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_sf5
     *
     * @param t1B11Sf5 the value for HF_hy_02.t1_b1_1_sf5
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11Sf5(Float t1B11Sf5) {
        this.t1B11Sf5 = t1B11Sf5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_sf6
     *
     * @return the value of HF_hy_02.t1_b1_1_sf6
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11Sf6() {
        return t1B11Sf6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_sf6
     *
     * @param t1B11Sf6 the value for HF_hy_02.t1_b1_1_sf6
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11Sf6(Float t1B11Sf6) {
        this.t1B11Sf6 = t1B11Sf6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_js2
     *
     * @return the value of HF_hy_02.t1_b1_1_js2
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11Js2() {
        return t1B11Js2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_js2
     *
     * @param t1B11Js2 the value for HF_hy_02.t1_b1_1_js2
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11Js2(Float t1B11Js2) {
        this.t1B11Js2 = t1B11Js2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_s1
     *
     * @return the value of HF_hy_02.t1_b1_1_s1
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11S1() {
        return t1B11S1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_s1
     *
     * @param t1B11S1 the value for HF_hy_02.t1_b1_1_s1
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11S1(Float t1B11S1) {
        this.t1B11S1 = t1B11S1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_s2
     *
     * @return the value of HF_hy_02.t1_b1_1_s2
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11S2() {
        return t1B11S2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_s2
     *
     * @param t1B11S2 the value for HF_hy_02.t1_b1_1_s2
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11S2(Float t1B11S2) {
        this.t1B11S2 = t1B11S2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_s3
     *
     * @return the value of HF_hy_02.t1_b1_1_s3
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11S3() {
        return t1B11S3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_s3
     *
     * @param t1B11S3 the value for HF_hy_02.t1_b1_1_s3
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11S3(Float t1B11S3) {
        this.t1B11S3 = t1B11S3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_s4
     *
     * @return the value of HF_hy_02.t1_b1_1_s4
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11S4() {
        return t1B11S4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_s4
     *
     * @param t1B11S4 the value for HF_hy_02.t1_b1_1_s4
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11S4(Float t1B11S4) {
        this.t1B11S4 = t1B11S4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_p1
     *
     * @return the value of HF_hy_02.t1_b1_1_p1
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11P1() {
        return t1B11P1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_p1
     *
     * @param t1B11P1 the value for HF_hy_02.t1_b1_1_p1
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11P1(Float t1B11P1) {
        this.t1B11P1 = t1B11P1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_p2
     *
     * @return the value of HF_hy_02.t1_b1_1_p2
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11P2() {
        return t1B11P2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_p2
     *
     * @param t1B11P2 the value for HF_hy_02.t1_b1_1_p2
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11P2(Float t1B11P2) {
        this.t1B11P2 = t1B11P2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_p3
     *
     * @return the value of HF_hy_02.t1_b1_1_p3
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11P3() {
        return t1B11P3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_p3
     *
     * @param t1B11P3 the value for HF_hy_02.t1_b1_1_p3
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11P3(Float t1B11P3) {
        this.t1B11P3 = t1B11P3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_p4
     *
     * @return the value of HF_hy_02.t1_b1_1_p4
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11P4() {
        return t1B11P4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_p4
     *
     * @param t1B11P4 the value for HF_hy_02.t1_b1_1_p4
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11P4(Float t1B11P4) {
        this.t1B11P4 = t1B11P4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_pg
     *
     * @return the value of HF_hy_02.t1_b1_1_pg
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11Pg() {
        return t1B11Pg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_pg
     *
     * @param t1B11Pg the value for HF_hy_02.t1_b1_1_pg
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11Pg(Float t1B11Pg) {
        this.t1B11Pg = t1B11Pg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_fmax
     *
     * @return the value of HF_hy_02.t1_b1_1_fmax
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11Fmax() {
        return t1B11Fmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_fmax
     *
     * @param t1B11Fmax the value for HF_hy_02.t1_b1_1_fmax
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11Fmax(Float t1B11Fmax) {
        this.t1B11Fmax = t1B11Fmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_fmin
     *
     * @return the value of HF_hy_02.t1_b1_1_fmin
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11Fmin() {
        return t1B11Fmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_fmin
     *
     * @param t1B11Fmin the value for HF_hy_02.t1_b1_1_fmin
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11Fmin(Float t1B11Fmin) {
        this.t1B11Fmin = t1B11Fmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_jssx
     *
     * @return the value of HF_hy_02.t1_b1_1_jssx
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11Jssx() {
        return t1B11Jssx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_jssx
     *
     * @param t1B11Jssx the value for HF_hy_02.t1_b1_1_jssx
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11Jssx(Float t1B11Jssx) {
        this.t1B11Jssx = t1B11Jssx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_jsxx
     *
     * @return the value of HF_hy_02.t1_b1_1_jsxx
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11Jsxx() {
        return t1B11Jsxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_jsxx
     *
     * @param t1B11Jsxx the value for HF_hy_02.t1_b1_1_jsxx
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11Jsxx(Float t1B11Jsxx) {
        this.t1B11Jsxx = t1B11Jsxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_xfmax
     *
     * @return the value of HF_hy_02.t1_b1_1_xfmax
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11Xfmax() {
        return t1B11Xfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_xfmax
     *
     * @param t1B11Xfmax the value for HF_hy_02.t1_b1_1_xfmax
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11Xfmax(Float t1B11Xfmax) {
        this.t1B11Xfmax = t1B11Xfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_xfmin
     *
     * @return the value of HF_hy_02.t1_b1_1_xfmin
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11Xfmin() {
        return t1B11Xfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_xfmin
     *
     * @param t1B11Xfmin the value for HF_hy_02.t1_b1_1_xfmin
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11Xfmin(Float t1B11Xfmin) {
        this.t1B11Xfmin = t1B11Xfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_hfmax
     *
     * @return the value of HF_hy_02.t1_b1_1_hfmax
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11Hfmax() {
        return t1B11Hfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_hfmax
     *
     * @param t1B11Hfmax the value for HF_hy_02.t1_b1_1_hfmax
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11Hfmax(Float t1B11Hfmax) {
        this.t1B11Hfmax = t1B11Hfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_hfmin
     *
     * @return the value of HF_hy_02.t1_b1_1_hfmin
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11Hfmin() {
        return t1B11Hfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_hfmin
     *
     * @param t1B11Hfmin the value for HF_hy_02.t1_b1_1_hfmin
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11Hfmin(Float t1B11Hfmin) {
        this.t1B11Hfmin = t1B11Hfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_sfsd
     *
     * @return the value of HF_hy_02.t1_b1_1_sfsd
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11Sfsd() {
        return t1B11Sfsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_sfsd
     *
     * @param t1B11Sfsd the value for HF_hy_02.t1_b1_1_sfsd
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11Sfsd(Float t1B11Sfsd) {
        this.t1B11Sfsd = t1B11Sfsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_p
     *
     * @return the value of HF_hy_02.t1_b1_1_p
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11P() {
        return t1B11P;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_p
     *
     * @param t1B11P the value for HF_hy_02.t1_b1_1_p
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11P(Float t1B11P) {
        this.t1B11P = t1B11P;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_i
     *
     * @return the value of HF_hy_02.t1_b1_1_i
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11I() {
        return t1B11I;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_i
     *
     * @param t1B11I the value for HF_hy_02.t1_b1_1_i
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11I(Float t1B11I) {
        this.t1B11I = t1B11I;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_d
     *
     * @return the value of HF_hy_02.t1_b1_1_d
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11D() {
        return t1B11D;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_d
     *
     * @param t1B11D the value for HF_hy_02.t1_b1_1_d
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11D(Float t1B11D) {
        this.t1B11D = t1B11D;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_co2_sd
     *
     * @return the value of HF_hy_02.t1_b1_1_co2_sd
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11Co2Sd() {
        return t1B11Co2Sd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_co2_sd
     *
     * @param t1B11Co2Sd the value for HF_hy_02.t1_b1_1_co2_sd
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11Co2Sd(Float t1B11Co2Sd) {
        this.t1B11Co2Sd = t1B11Co2Sd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_1p
     *
     * @return the value of HF_hy_02.t1_b1_1_1p
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B111p() {
        return t1B111p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_1p
     *
     * @param t1B111p the value for HF_hy_02.t1_b1_1_1p
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B111p(Float t1B111p) {
        this.t1B111p = t1B111p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_1i
     *
     * @return the value of HF_hy_02.t1_b1_1_1i
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B111i() {
        return t1B111i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_1i
     *
     * @param t1B111i the value for HF_hy_02.t1_b1_1_1i
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B111i(Float t1B111i) {
        this.t1B111i = t1B111i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_1d
     *
     * @return the value of HF_hy_02.t1_b1_1_1d
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B111d() {
        return t1B111d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_1d
     *
     * @param t1B111d the value for HF_hy_02.t1_b1_1_1d
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B111d(Float t1B111d) {
        this.t1B111d = t1B111d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_hfts
     *
     * @return the value of HF_hy_02.t1_b1_1_hfts
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11Hfts() {
        return t1B11Hfts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_hfts
     *
     * @param t1B11Hfts the value for HF_hy_02.t1_b1_1_hfts
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11Hfts(Float t1B11Hfts) {
        this.t1B11Hfts = t1B11Hfts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_2p
     *
     * @return the value of HF_hy_02.t1_b1_1_2p
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B112p() {
        return t1B112p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_2p
     *
     * @param t1B112p the value for HF_hy_02.t1_b1_1_2p
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B112p(Float t1B112p) {
        this.t1B112p = t1B112p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_2i
     *
     * @return the value of HF_hy_02.t1_b1_1_2i
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B112i() {
        return t1B112i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_2i
     *
     * @param t1B112i the value for HF_hy_02.t1_b1_1_2i
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B112i(Float t1B112i) {
        this.t1B112i = t1B112i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1_2d
     *
     * @return the value of HF_hy_02.t1_b1_1_2d
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B112d() {
        return t1B112d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1_2d
     *
     * @param t1B112d the value for HF_hy_02.t1_b1_1_2d
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B112d(Float t1B112d) {
        this.t1B112d = t1B112d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1jsqdt
     *
     * @return the value of HF_hy_02.t1_b1_1jsqdt
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11jsqdt() {
        return t1B11jsqdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1jsqdt
     *
     * @param t1B11jsqdt the value for HF_hy_02.t1_b1_1jsqdt
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11jsqdt(Float t1B11jsqdt) {
        this.t1B11jsqdt = t1B11jsqdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1jstzt
     *
     * @return the value of HF_hy_02.t1_b1_1jstzt
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11jstzt() {
        return t1B11jstzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1jstzt
     *
     * @param t1B11jstzt the value for HF_hy_02.t1_b1_1jstzt
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11jstzt(Float t1B11jstzt) {
        this.t1B11jstzt = t1B11jstzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1zlzr_am
     *
     * @return the value of HF_hy_02.t1_b1_1zlzr_am
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11zlzrAm() {
        return t1B11zlzrAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1zlzr_am
     *
     * @param t1B11zlzrAm the value for HF_hy_02.t1_b1_1zlzr_am
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11zlzrAm(Float t1B11zlzrAm) {
        this.t1B11zlzrAm = t1B11zlzrAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1ys_am
     *
     * @return the value of HF_hy_02.t1_b1_1ys_am
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11ysAm() {
        return t1B11ysAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1ys_am
     *
     * @param t1B11ysAm the value for HF_hy_02.t1_b1_1ys_am
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11ysAm(Float t1B11ysAm) {
        this.t1B11ysAm = t1B11ysAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1ddf_am
     *
     * @return the value of HF_hy_02.t1_b1_1ddf_am
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11ddfAm() {
        return t1B11ddfAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1ddf_am
     *
     * @param t1B11ddfAm the value for HF_hy_02.t1_b1_1ddf_am
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11ddfAm(Float t1B11ddfAm) {
        this.t1B11ddfAm = t1B11ddfAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1sjam
     *
     * @return the value of HF_hy_02.t1_b1_1sjam
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11sjam() {
        return t1B11sjam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1sjam
     *
     * @param t1B11sjam the value for HF_hy_02.t1_b1_1sjam
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11sjam(Float t1B11sjam) {
        this.t1B11sjam = t1B11sjam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1djam
     *
     * @return the value of HF_hy_02.t1_b1_1djam
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11djam() {
        return t1B11djam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1djam
     *
     * @param t1B11djam the value for HF_hy_02.t1_b1_1djam
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11djam(Float t1B11djam) {
        this.t1B11djam = t1B11djam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1xff_am
     *
     * @return the value of HF_hy_02.t1_b1_1xff_am
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11xffAm() {
        return t1B11xffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1xff_am
     *
     * @param t1B11xffAm the value for HF_hy_02.t1_b1_1xff_am
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11xffAm(Float t1B11xffAm) {
        this.t1B11xffAm = t1B11xffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1hff_am
     *
     * @return the value of HF_hy_02.t1_b1_1hff_am
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11hffAm() {
        return t1B11hffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1hff_am
     *
     * @param t1B11hffAm the value for HF_hy_02.t1_b1_1hff_am
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11hffAm(Float t1B11hffAm) {
        this.t1B11hffAm = t1B11hffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_02.t1_b1_1jst_s
     *
     * @return the value of HF_hy_02.t1_b1_1jst_s
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public Float getT1B11jstS() {
        return t1B11jstS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_02.t1_b1_1jst_s
     *
     * @param t1B11jstS the value for HF_hy_02.t1_b1_1jst_s
     *
     * @mbg.generated Wed Oct 11 14:15:14 CST 2017
     */
    public void setT1B11jstS(Float t1B11jstS) {
        this.t1B11jstS = t1B11jstS;
    }

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getTimeNew() {
		return timeNew;
	}

	public void setTimeNew(String timeNew) {
		this.timeNew = timeNew;
	}
    
    
    
    
}