package com.firstCapacity.business.HeFeiPower.entity;

import java.io.Serializable;
import java.util.Date;

public class HF_hy_01 implements Serializable{
	
	private static final long serialVersionUID = 1L;
	
    private String startTime;
    
    private String endTime;
    
    private String timeNew;
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.Time
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_fd
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1Fd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_t3
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1T3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_h1
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1H1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_t4
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1T4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_h2
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1H2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_d1
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1D1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_d3
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1D3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_ffs5
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1Ffs5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_ffs6
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1Ffs6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_pfk
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1Pfk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_pfg
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1Pfg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_hfs5
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1Hfs5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_hfs6
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1Hfs6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_sf5
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1Sf5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_sf6
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1Sf6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_js2
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1Js2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_s1
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1S1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_s2
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1S2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_s3
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1S3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_s4
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1S4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_p1
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1P1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_p2
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1P2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_p3
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1P3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_p4
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1P4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_pg
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1Pg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_co2
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1Co2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_fmax
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1Fmax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_fmin
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1Fmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_jssx
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1Jssx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_jsxx
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1Jsxx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_xfmax
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1Xfmax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_xfmin
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1Xfmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_hfmax
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1Hfmax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_hfmin
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1Hfmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_sfsd
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1Sfsd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_p
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1P;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_i
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1I;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_d
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1D;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_co2_sd
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1Co2Sd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_1p
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf11p;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_1i
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf11i;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_1d
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf11d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_hfts
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1Hfts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_2p
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf12p;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_2i
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf12i;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1_2d
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf12d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1jsqdt
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1jsqdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1jstzt
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1jstzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1zlzr_am
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1zlzrAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1ys_am
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1ysAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1ddf_am
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1ddfAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1sjam
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1sjam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1djam
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1djam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1xff_am
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1xffAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1hff_am
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1hffAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_01.t1_rf_1jst_s
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    private Float t1Rf1jstS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.Time
     *
     * @return the value of HF_hy_01.Time
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.Time
     *
     * @param time the value for HF_hy_01.Time
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_fd
     *
     * @return the value of HF_hy_01.t1_rf_1_fd
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1Fd() {
        return t1Rf1Fd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_fd
     *
     * @param t1Rf1Fd the value for HF_hy_01.t1_rf_1_fd
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1Fd(Float t1Rf1Fd) {
        this.t1Rf1Fd = t1Rf1Fd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_t3
     *
     * @return the value of HF_hy_01.t1_rf_1_t3
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1T3() {
        return t1Rf1T3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_t3
     *
     * @param t1Rf1T3 the value for HF_hy_01.t1_rf_1_t3
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1T3(Float t1Rf1T3) {
        this.t1Rf1T3 = t1Rf1T3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_h1
     *
     * @return the value of HF_hy_01.t1_rf_1_h1
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1H1() {
        return t1Rf1H1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_h1
     *
     * @param t1Rf1H1 the value for HF_hy_01.t1_rf_1_h1
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1H1(Float t1Rf1H1) {
        this.t1Rf1H1 = t1Rf1H1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_t4
     *
     * @return the value of HF_hy_01.t1_rf_1_t4
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1T4() {
        return t1Rf1T4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_t4
     *
     * @param t1Rf1T4 the value for HF_hy_01.t1_rf_1_t4
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1T4(Float t1Rf1T4) {
        this.t1Rf1T4 = t1Rf1T4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_h2
     *
     * @return the value of HF_hy_01.t1_rf_1_h2
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1H2() {
        return t1Rf1H2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_h2
     *
     * @param t1Rf1H2 the value for HF_hy_01.t1_rf_1_h2
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1H2(Float t1Rf1H2) {
        this.t1Rf1H2 = t1Rf1H2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_d1
     *
     * @return the value of HF_hy_01.t1_rf_1_d1
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1D1() {
        return t1Rf1D1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_d1
     *
     * @param t1Rf1D1 the value for HF_hy_01.t1_rf_1_d1
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1D1(Float t1Rf1D1) {
        this.t1Rf1D1 = t1Rf1D1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_d3
     *
     * @return the value of HF_hy_01.t1_rf_1_d3
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1D3() {
        return t1Rf1D3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_d3
     *
     * @param t1Rf1D3 the value for HF_hy_01.t1_rf_1_d3
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1D3(Float t1Rf1D3) {
        this.t1Rf1D3 = t1Rf1D3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_ffs5
     *
     * @return the value of HF_hy_01.t1_rf_1_ffs5
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1Ffs5() {
        return t1Rf1Ffs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_ffs5
     *
     * @param t1Rf1Ffs5 the value for HF_hy_01.t1_rf_1_ffs5
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1Ffs5(Float t1Rf1Ffs5) {
        this.t1Rf1Ffs5 = t1Rf1Ffs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_ffs6
     *
     * @return the value of HF_hy_01.t1_rf_1_ffs6
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1Ffs6() {
        return t1Rf1Ffs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_ffs6
     *
     * @param t1Rf1Ffs6 the value for HF_hy_01.t1_rf_1_ffs6
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1Ffs6(Float t1Rf1Ffs6) {
        this.t1Rf1Ffs6 = t1Rf1Ffs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_pfk
     *
     * @return the value of HF_hy_01.t1_rf_1_pfk
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1Pfk() {
        return t1Rf1Pfk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_pfk
     *
     * @param t1Rf1Pfk the value for HF_hy_01.t1_rf_1_pfk
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1Pfk(Float t1Rf1Pfk) {
        this.t1Rf1Pfk = t1Rf1Pfk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_pfg
     *
     * @return the value of HF_hy_01.t1_rf_1_pfg
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1Pfg() {
        return t1Rf1Pfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_pfg
     *
     * @param t1Rf1Pfg the value for HF_hy_01.t1_rf_1_pfg
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1Pfg(Float t1Rf1Pfg) {
        this.t1Rf1Pfg = t1Rf1Pfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_hfs5
     *
     * @return the value of HF_hy_01.t1_rf_1_hfs5
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1Hfs5() {
        return t1Rf1Hfs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_hfs5
     *
     * @param t1Rf1Hfs5 the value for HF_hy_01.t1_rf_1_hfs5
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1Hfs5(Float t1Rf1Hfs5) {
        this.t1Rf1Hfs5 = t1Rf1Hfs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_hfs6
     *
     * @return the value of HF_hy_01.t1_rf_1_hfs6
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1Hfs6() {
        return t1Rf1Hfs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_hfs6
     *
     * @param t1Rf1Hfs6 the value for HF_hy_01.t1_rf_1_hfs6
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1Hfs6(Float t1Rf1Hfs6) {
        this.t1Rf1Hfs6 = t1Rf1Hfs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_sf5
     *
     * @return the value of HF_hy_01.t1_rf_1_sf5
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1Sf5() {
        return t1Rf1Sf5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_sf5
     *
     * @param t1Rf1Sf5 the value for HF_hy_01.t1_rf_1_sf5
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1Sf5(Float t1Rf1Sf5) {
        this.t1Rf1Sf5 = t1Rf1Sf5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_sf6
     *
     * @return the value of HF_hy_01.t1_rf_1_sf6
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1Sf6() {
        return t1Rf1Sf6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_sf6
     *
     * @param t1Rf1Sf6 the value for HF_hy_01.t1_rf_1_sf6
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1Sf6(Float t1Rf1Sf6) {
        this.t1Rf1Sf6 = t1Rf1Sf6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_js2
     *
     * @return the value of HF_hy_01.t1_rf_1_js2
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1Js2() {
        return t1Rf1Js2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_js2
     *
     * @param t1Rf1Js2 the value for HF_hy_01.t1_rf_1_js2
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1Js2(Float t1Rf1Js2) {
        this.t1Rf1Js2 = t1Rf1Js2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_s1
     *
     * @return the value of HF_hy_01.t1_rf_1_s1
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1S1() {
        return t1Rf1S1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_s1
     *
     * @param t1Rf1S1 the value for HF_hy_01.t1_rf_1_s1
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1S1(Float t1Rf1S1) {
        this.t1Rf1S1 = t1Rf1S1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_s2
     *
     * @return the value of HF_hy_01.t1_rf_1_s2
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1S2() {
        return t1Rf1S2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_s2
     *
     * @param t1Rf1S2 the value for HF_hy_01.t1_rf_1_s2
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1S2(Float t1Rf1S2) {
        this.t1Rf1S2 = t1Rf1S2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_s3
     *
     * @return the value of HF_hy_01.t1_rf_1_s3
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1S3() {
        return t1Rf1S3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_s3
     *
     * @param t1Rf1S3 the value for HF_hy_01.t1_rf_1_s3
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1S3(Float t1Rf1S3) {
        this.t1Rf1S3 = t1Rf1S3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_s4
     *
     * @return the value of HF_hy_01.t1_rf_1_s4
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1S4() {
        return t1Rf1S4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_s4
     *
     * @param t1Rf1S4 the value for HF_hy_01.t1_rf_1_s4
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1S4(Float t1Rf1S4) {
        this.t1Rf1S4 = t1Rf1S4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_p1
     *
     * @return the value of HF_hy_01.t1_rf_1_p1
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1P1() {
        return t1Rf1P1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_p1
     *
     * @param t1Rf1P1 the value for HF_hy_01.t1_rf_1_p1
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1P1(Float t1Rf1P1) {
        this.t1Rf1P1 = t1Rf1P1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_p2
     *
     * @return the value of HF_hy_01.t1_rf_1_p2
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1P2() {
        return t1Rf1P2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_p2
     *
     * @param t1Rf1P2 the value for HF_hy_01.t1_rf_1_p2
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1P2(Float t1Rf1P2) {
        this.t1Rf1P2 = t1Rf1P2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_p3
     *
     * @return the value of HF_hy_01.t1_rf_1_p3
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1P3() {
        return t1Rf1P3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_p3
     *
     * @param t1Rf1P3 the value for HF_hy_01.t1_rf_1_p3
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1P3(Float t1Rf1P3) {
        this.t1Rf1P3 = t1Rf1P3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_p4
     *
     * @return the value of HF_hy_01.t1_rf_1_p4
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1P4() {
        return t1Rf1P4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_p4
     *
     * @param t1Rf1P4 the value for HF_hy_01.t1_rf_1_p4
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1P4(Float t1Rf1P4) {
        this.t1Rf1P4 = t1Rf1P4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_pg
     *
     * @return the value of HF_hy_01.t1_rf_1_pg
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1Pg() {
        return t1Rf1Pg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_pg
     *
     * @param t1Rf1Pg the value for HF_hy_01.t1_rf_1_pg
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1Pg(Float t1Rf1Pg) {
        this.t1Rf1Pg = t1Rf1Pg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_co2
     *
     * @return the value of HF_hy_01.t1_rf_1_co2
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1Co2() {
        return t1Rf1Co2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_co2
     *
     * @param t1Rf1Co2 the value for HF_hy_01.t1_rf_1_co2
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1Co2(Float t1Rf1Co2) {
        this.t1Rf1Co2 = t1Rf1Co2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_fmax
     *
     * @return the value of HF_hy_01.t1_rf_1_fmax
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1Fmax() {
        return t1Rf1Fmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_fmax
     *
     * @param t1Rf1Fmax the value for HF_hy_01.t1_rf_1_fmax
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1Fmax(Float t1Rf1Fmax) {
        this.t1Rf1Fmax = t1Rf1Fmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_fmin
     *
     * @return the value of HF_hy_01.t1_rf_1_fmin
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1Fmin() {
        return t1Rf1Fmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_fmin
     *
     * @param t1Rf1Fmin the value for HF_hy_01.t1_rf_1_fmin
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1Fmin(Float t1Rf1Fmin) {
        this.t1Rf1Fmin = t1Rf1Fmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_jssx
     *
     * @return the value of HF_hy_01.t1_rf_1_jssx
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1Jssx() {
        return t1Rf1Jssx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_jssx
     *
     * @param t1Rf1Jssx the value for HF_hy_01.t1_rf_1_jssx
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1Jssx(Float t1Rf1Jssx) {
        this.t1Rf1Jssx = t1Rf1Jssx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_jsxx
     *
     * @return the value of HF_hy_01.t1_rf_1_jsxx
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1Jsxx() {
        return t1Rf1Jsxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_jsxx
     *
     * @param t1Rf1Jsxx the value for HF_hy_01.t1_rf_1_jsxx
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1Jsxx(Float t1Rf1Jsxx) {
        this.t1Rf1Jsxx = t1Rf1Jsxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_xfmax
     *
     * @return the value of HF_hy_01.t1_rf_1_xfmax
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1Xfmax() {
        return t1Rf1Xfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_xfmax
     *
     * @param t1Rf1Xfmax the value for HF_hy_01.t1_rf_1_xfmax
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1Xfmax(Float t1Rf1Xfmax) {
        this.t1Rf1Xfmax = t1Rf1Xfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_xfmin
     *
     * @return the value of HF_hy_01.t1_rf_1_xfmin
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1Xfmin() {
        return t1Rf1Xfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_xfmin
     *
     * @param t1Rf1Xfmin the value for HF_hy_01.t1_rf_1_xfmin
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1Xfmin(Float t1Rf1Xfmin) {
        this.t1Rf1Xfmin = t1Rf1Xfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_hfmax
     *
     * @return the value of HF_hy_01.t1_rf_1_hfmax
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1Hfmax() {
        return t1Rf1Hfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_hfmax
     *
     * @param t1Rf1Hfmax the value for HF_hy_01.t1_rf_1_hfmax
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1Hfmax(Float t1Rf1Hfmax) {
        this.t1Rf1Hfmax = t1Rf1Hfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_hfmin
     *
     * @return the value of HF_hy_01.t1_rf_1_hfmin
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1Hfmin() {
        return t1Rf1Hfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_hfmin
     *
     * @param t1Rf1Hfmin the value for HF_hy_01.t1_rf_1_hfmin
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1Hfmin(Float t1Rf1Hfmin) {
        this.t1Rf1Hfmin = t1Rf1Hfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_sfsd
     *
     * @return the value of HF_hy_01.t1_rf_1_sfsd
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1Sfsd() {
        return t1Rf1Sfsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_sfsd
     *
     * @param t1Rf1Sfsd the value for HF_hy_01.t1_rf_1_sfsd
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1Sfsd(Float t1Rf1Sfsd) {
        this.t1Rf1Sfsd = t1Rf1Sfsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_p
     *
     * @return the value of HF_hy_01.t1_rf_1_p
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1P() {
        return t1Rf1P;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_p
     *
     * @param t1Rf1P the value for HF_hy_01.t1_rf_1_p
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1P(Float t1Rf1P) {
        this.t1Rf1P = t1Rf1P;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_i
     *
     * @return the value of HF_hy_01.t1_rf_1_i
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1I() {
        return t1Rf1I;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_i
     *
     * @param t1Rf1I the value for HF_hy_01.t1_rf_1_i
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1I(Float t1Rf1I) {
        this.t1Rf1I = t1Rf1I;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_d
     *
     * @return the value of HF_hy_01.t1_rf_1_d
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1D() {
        return t1Rf1D;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_d
     *
     * @param t1Rf1D the value for HF_hy_01.t1_rf_1_d
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1D(Float t1Rf1D) {
        this.t1Rf1D = t1Rf1D;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_co2_sd
     *
     * @return the value of HF_hy_01.t1_rf_1_co2_sd
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1Co2Sd() {
        return t1Rf1Co2Sd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_co2_sd
     *
     * @param t1Rf1Co2Sd the value for HF_hy_01.t1_rf_1_co2_sd
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1Co2Sd(Float t1Rf1Co2Sd) {
        this.t1Rf1Co2Sd = t1Rf1Co2Sd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_1p
     *
     * @return the value of HF_hy_01.t1_rf_1_1p
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf11p() {
        return t1Rf11p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_1p
     *
     * @param t1Rf11p the value for HF_hy_01.t1_rf_1_1p
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf11p(Float t1Rf11p) {
        this.t1Rf11p = t1Rf11p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_1i
     *
     * @return the value of HF_hy_01.t1_rf_1_1i
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf11i() {
        return t1Rf11i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_1i
     *
     * @param t1Rf11i the value for HF_hy_01.t1_rf_1_1i
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf11i(Float t1Rf11i) {
        this.t1Rf11i = t1Rf11i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_1d
     *
     * @return the value of HF_hy_01.t1_rf_1_1d
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf11d() {
        return t1Rf11d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_1d
     *
     * @param t1Rf11d the value for HF_hy_01.t1_rf_1_1d
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf11d(Float t1Rf11d) {
        this.t1Rf11d = t1Rf11d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_hfts
     *
     * @return the value of HF_hy_01.t1_rf_1_hfts
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1Hfts() {
        return t1Rf1Hfts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_hfts
     *
     * @param t1Rf1Hfts the value for HF_hy_01.t1_rf_1_hfts
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1Hfts(Float t1Rf1Hfts) {
        this.t1Rf1Hfts = t1Rf1Hfts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_2p
     *
     * @return the value of HF_hy_01.t1_rf_1_2p
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf12p() {
        return t1Rf12p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_2p
     *
     * @param t1Rf12p the value for HF_hy_01.t1_rf_1_2p
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf12p(Float t1Rf12p) {
        this.t1Rf12p = t1Rf12p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_2i
     *
     * @return the value of HF_hy_01.t1_rf_1_2i
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf12i() {
        return t1Rf12i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_2i
     *
     * @param t1Rf12i the value for HF_hy_01.t1_rf_1_2i
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf12i(Float t1Rf12i) {
        this.t1Rf12i = t1Rf12i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1_2d
     *
     * @return the value of HF_hy_01.t1_rf_1_2d
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf12d() {
        return t1Rf12d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1_2d
     *
     * @param t1Rf12d the value for HF_hy_01.t1_rf_1_2d
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf12d(Float t1Rf12d) {
        this.t1Rf12d = t1Rf12d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1jsqdt
     *
     * @return the value of HF_hy_01.t1_rf_1jsqdt
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1jsqdt() {
        return t1Rf1jsqdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1jsqdt
     *
     * @param t1Rf1jsqdt the value for HF_hy_01.t1_rf_1jsqdt
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1jsqdt(Float t1Rf1jsqdt) {
        this.t1Rf1jsqdt = t1Rf1jsqdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1jstzt
     *
     * @return the value of HF_hy_01.t1_rf_1jstzt
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1jstzt() {
        return t1Rf1jstzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1jstzt
     *
     * @param t1Rf1jstzt the value for HF_hy_01.t1_rf_1jstzt
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1jstzt(Float t1Rf1jstzt) {
        this.t1Rf1jstzt = t1Rf1jstzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1zlzr_am
     *
     * @return the value of HF_hy_01.t1_rf_1zlzr_am
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1zlzrAm() {
        return t1Rf1zlzrAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1zlzr_am
     *
     * @param t1Rf1zlzrAm the value for HF_hy_01.t1_rf_1zlzr_am
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1zlzrAm(Float t1Rf1zlzrAm) {
        this.t1Rf1zlzrAm = t1Rf1zlzrAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1ys_am
     *
     * @return the value of HF_hy_01.t1_rf_1ys_am
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1ysAm() {
        return t1Rf1ysAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1ys_am
     *
     * @param t1Rf1ysAm the value for HF_hy_01.t1_rf_1ys_am
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1ysAm(Float t1Rf1ysAm) {
        this.t1Rf1ysAm = t1Rf1ysAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1ddf_am
     *
     * @return the value of HF_hy_01.t1_rf_1ddf_am
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1ddfAm() {
        return t1Rf1ddfAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1ddf_am
     *
     * @param t1Rf1ddfAm the value for HF_hy_01.t1_rf_1ddf_am
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1ddfAm(Float t1Rf1ddfAm) {
        this.t1Rf1ddfAm = t1Rf1ddfAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1sjam
     *
     * @return the value of HF_hy_01.t1_rf_1sjam
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1sjam() {
        return t1Rf1sjam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1sjam
     *
     * @param t1Rf1sjam the value for HF_hy_01.t1_rf_1sjam
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1sjam(Float t1Rf1sjam) {
        this.t1Rf1sjam = t1Rf1sjam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1djam
     *
     * @return the value of HF_hy_01.t1_rf_1djam
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1djam() {
        return t1Rf1djam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1djam
     *
     * @param t1Rf1djam the value for HF_hy_01.t1_rf_1djam
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1djam(Float t1Rf1djam) {
        this.t1Rf1djam = t1Rf1djam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1xff_am
     *
     * @return the value of HF_hy_01.t1_rf_1xff_am
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1xffAm() {
        return t1Rf1xffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1xff_am
     *
     * @param t1Rf1xffAm the value for HF_hy_01.t1_rf_1xff_am
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1xffAm(Float t1Rf1xffAm) {
        this.t1Rf1xffAm = t1Rf1xffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1hff_am
     *
     * @return the value of HF_hy_01.t1_rf_1hff_am
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1hffAm() {
        return t1Rf1hffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1hff_am
     *
     * @param t1Rf1hffAm the value for HF_hy_01.t1_rf_1hff_am
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1hffAm(Float t1Rf1hffAm) {
        this.t1Rf1hffAm = t1Rf1hffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_01.t1_rf_1jst_s
     *
     * @return the value of HF_hy_01.t1_rf_1jst_s
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public Float getT1Rf1jstS() {
        return t1Rf1jstS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_01.t1_rf_1jst_s
     *
     * @param t1Rf1jstS the value for HF_hy_01.t1_rf_1jst_s
     *
     * @mbg.generated Wed Oct 11 14:14:41 CST 2017
     */
    public void setT1Rf1jstS(Float t1Rf1jstS) {
        this.t1Rf1jstS = t1Rf1jstS;
    }

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getTimeNew() {
		return timeNew;
	}

	public void setTimeNew(String timeNew) {
		this.timeNew = timeNew;
	}
    
    
    
    
    
    
}