package com.firstCapacity.business.HeFeiPower.entity;

import java.io.Serializable;
import java.util.Date;

public class HF_hy_11 implements Serializable{
	
	
	private static final long serialVersionUID = 1L;
	
	
    private String startTime;
    
    private String endTime;
    
    private String timeNew;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.Time
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.l1dyj_a_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float l1dyjAT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.l1dyj_b_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float l1dyjBT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.l1dyj_c_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float l1dyjCT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.l1dyj_d_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float l1dyjDT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.l1dyj_e_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float l1dyjET;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.l1dyb_a_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float l1dybAT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.l1dyb_b_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float l1dybBT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.l1dyb_c_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float l1dybCT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.l1tpb_a_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float l1tpbAT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.l1tpb_b_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float l1tpbBT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.l1tpb_c_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float l1tpbCT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.l1xfb_a_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float l1xfbAT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.l1xfb_b_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float l1xfbBT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.l1xfb_c_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float l1xfbCT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.l1lqb_a_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float l1lqbAT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.l1lqb_b_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float l1lqbBT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.l1x_bsb_a_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float l1xBsbAT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.l1x_bsb_b_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float l1xBsbBT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.l1t_bsb_a_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float l1tBsbAT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.l1t_bsb_b_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float l1tBsbBT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.l1ltfj_a_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float l1ltfjAT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.l1ltfj_b_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float l1ltfjBT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t1_rf_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t1Rf1Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t1_rf_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t1Rf1St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t1_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t1B11Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t1_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t1B11St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t2_rf_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t2Rf1Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t2_rf_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t2Rf1St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t2_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t2B11Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t2_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t2B11St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t3_rf_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t3Rf1Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t3_rf_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t3Rf1St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t3_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t3B11Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t3_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t3B11St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t4_rf_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t4Rf1Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t4_rf_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t4Rf1St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t4_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t4B11Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t4_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t4B11St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t5_rf_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t5Rf1Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t5_rf_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t5Rf1St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t5_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t5B11Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t5_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t5B11St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t6_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t6B11Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t6_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t6B11St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t6_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t6B12Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t6_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t6B12St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t7_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t7B11Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t7_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t7B11St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t7_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t7B12Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t7_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t7B12St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t8_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t8B11Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t8_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t8B11St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t8_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t8B12Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t8_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t8B12St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t9_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t9B11Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t9_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t9B11St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t9_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t9B12Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t9_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t9B12St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t10_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t10B11Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t10_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t10B11St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t10_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t10B12Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t10_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t10B12St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t11_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t11B11Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t11_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t11B11St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t11_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t11B12Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t11_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t11B12St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t12_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t12B11Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t12_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t12B11St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t12_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t12B12Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t12_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t12B12St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t13_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t13B11Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t13_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t13B11St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t13_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t13B12Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t13_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t13B12St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t14_rf_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t14Rf1Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t14_rf_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t14Rf1St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t14_rf_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t14Rf2Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t14_rf_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t14Rf2St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t14_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t14B11Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t14_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t14B11St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t14_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t14B12Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t14_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t14B12St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t15_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t15B11Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t15_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t15B11St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t15_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t15B12Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t15_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t15B12St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t16_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t16B11Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t16_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t16B11St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t16_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t16B12Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t16_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t16B12St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t17_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t17B11Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t17_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t17B11St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t17_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t17B12Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t17_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t17B12St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t18_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t18B11Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t18_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t18B11St;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t18_rf_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t18Rf1Ht;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_11.t18_rf_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    private Float t18Rf1St;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.Time
     *
     * @return the value of HF_hy_11.Time
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.Time
     *
     * @param time the value for HF_hy_11.Time
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.l1dyj_a_t
     *
     * @return the value of HF_hy_11.l1dyj_a_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getL1dyjAT() {
        return l1dyjAT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.l1dyj_a_t
     *
     * @param l1dyjAT the value for HF_hy_11.l1dyj_a_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setL1dyjAT(Float l1dyjAT) {
        this.l1dyjAT = l1dyjAT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.l1dyj_b_t
     *
     * @return the value of HF_hy_11.l1dyj_b_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getL1dyjBT() {
        return l1dyjBT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.l1dyj_b_t
     *
     * @param l1dyjBT the value for HF_hy_11.l1dyj_b_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setL1dyjBT(Float l1dyjBT) {
        this.l1dyjBT = l1dyjBT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.l1dyj_c_t
     *
     * @return the value of HF_hy_11.l1dyj_c_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getL1dyjCT() {
        return l1dyjCT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.l1dyj_c_t
     *
     * @param l1dyjCT the value for HF_hy_11.l1dyj_c_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setL1dyjCT(Float l1dyjCT) {
        this.l1dyjCT = l1dyjCT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.l1dyj_d_t
     *
     * @return the value of HF_hy_11.l1dyj_d_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getL1dyjDT() {
        return l1dyjDT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.l1dyj_d_t
     *
     * @param l1dyjDT the value for HF_hy_11.l1dyj_d_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setL1dyjDT(Float l1dyjDT) {
        this.l1dyjDT = l1dyjDT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.l1dyj_e_t
     *
     * @return the value of HF_hy_11.l1dyj_e_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getL1dyjET() {
        return l1dyjET;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.l1dyj_e_t
     *
     * @param l1dyjET the value for HF_hy_11.l1dyj_e_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setL1dyjET(Float l1dyjET) {
        this.l1dyjET = l1dyjET;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.l1dyb_a_t
     *
     * @return the value of HF_hy_11.l1dyb_a_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getL1dybAT() {
        return l1dybAT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.l1dyb_a_t
     *
     * @param l1dybAT the value for HF_hy_11.l1dyb_a_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setL1dybAT(Float l1dybAT) {
        this.l1dybAT = l1dybAT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.l1dyb_b_t
     *
     * @return the value of HF_hy_11.l1dyb_b_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getL1dybBT() {
        return l1dybBT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.l1dyb_b_t
     *
     * @param l1dybBT the value for HF_hy_11.l1dyb_b_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setL1dybBT(Float l1dybBT) {
        this.l1dybBT = l1dybBT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.l1dyb_c_t
     *
     * @return the value of HF_hy_11.l1dyb_c_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getL1dybCT() {
        return l1dybCT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.l1dyb_c_t
     *
     * @param l1dybCT the value for HF_hy_11.l1dyb_c_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setL1dybCT(Float l1dybCT) {
        this.l1dybCT = l1dybCT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.l1tpb_a_t
     *
     * @return the value of HF_hy_11.l1tpb_a_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getL1tpbAT() {
        return l1tpbAT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.l1tpb_a_t
     *
     * @param l1tpbAT the value for HF_hy_11.l1tpb_a_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setL1tpbAT(Float l1tpbAT) {
        this.l1tpbAT = l1tpbAT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.l1tpb_b_t
     *
     * @return the value of HF_hy_11.l1tpb_b_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getL1tpbBT() {
        return l1tpbBT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.l1tpb_b_t
     *
     * @param l1tpbBT the value for HF_hy_11.l1tpb_b_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setL1tpbBT(Float l1tpbBT) {
        this.l1tpbBT = l1tpbBT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.l1tpb_c_t
     *
     * @return the value of HF_hy_11.l1tpb_c_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getL1tpbCT() {
        return l1tpbCT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.l1tpb_c_t
     *
     * @param l1tpbCT the value for HF_hy_11.l1tpb_c_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setL1tpbCT(Float l1tpbCT) {
        this.l1tpbCT = l1tpbCT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.l1xfb_a_t
     *
     * @return the value of HF_hy_11.l1xfb_a_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getL1xfbAT() {
        return l1xfbAT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.l1xfb_a_t
     *
     * @param l1xfbAT the value for HF_hy_11.l1xfb_a_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setL1xfbAT(Float l1xfbAT) {
        this.l1xfbAT = l1xfbAT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.l1xfb_b_t
     *
     * @return the value of HF_hy_11.l1xfb_b_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getL1xfbBT() {
        return l1xfbBT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.l1xfb_b_t
     *
     * @param l1xfbBT the value for HF_hy_11.l1xfb_b_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setL1xfbBT(Float l1xfbBT) {
        this.l1xfbBT = l1xfbBT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.l1xfb_c_t
     *
     * @return the value of HF_hy_11.l1xfb_c_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getL1xfbCT() {
        return l1xfbCT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.l1xfb_c_t
     *
     * @param l1xfbCT the value for HF_hy_11.l1xfb_c_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setL1xfbCT(Float l1xfbCT) {
        this.l1xfbCT = l1xfbCT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.l1lqb_a_t
     *
     * @return the value of HF_hy_11.l1lqb_a_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getL1lqbAT() {
        return l1lqbAT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.l1lqb_a_t
     *
     * @param l1lqbAT the value for HF_hy_11.l1lqb_a_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setL1lqbAT(Float l1lqbAT) {
        this.l1lqbAT = l1lqbAT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.l1lqb_b_t
     *
     * @return the value of HF_hy_11.l1lqb_b_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getL1lqbBT() {
        return l1lqbBT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.l1lqb_b_t
     *
     * @param l1lqbBT the value for HF_hy_11.l1lqb_b_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setL1lqbBT(Float l1lqbBT) {
        this.l1lqbBT = l1lqbBT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.l1x_bsb_a_t
     *
     * @return the value of HF_hy_11.l1x_bsb_a_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getL1xBsbAT() {
        return l1xBsbAT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.l1x_bsb_a_t
     *
     * @param l1xBsbAT the value for HF_hy_11.l1x_bsb_a_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setL1xBsbAT(Float l1xBsbAT) {
        this.l1xBsbAT = l1xBsbAT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.l1x_bsb_b_t
     *
     * @return the value of HF_hy_11.l1x_bsb_b_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getL1xBsbBT() {
        return l1xBsbBT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.l1x_bsb_b_t
     *
     * @param l1xBsbBT the value for HF_hy_11.l1x_bsb_b_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setL1xBsbBT(Float l1xBsbBT) {
        this.l1xBsbBT = l1xBsbBT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.l1t_bsb_a_t
     *
     * @return the value of HF_hy_11.l1t_bsb_a_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getL1tBsbAT() {
        return l1tBsbAT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.l1t_bsb_a_t
     *
     * @param l1tBsbAT the value for HF_hy_11.l1t_bsb_a_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setL1tBsbAT(Float l1tBsbAT) {
        this.l1tBsbAT = l1tBsbAT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.l1t_bsb_b_t
     *
     * @return the value of HF_hy_11.l1t_bsb_b_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getL1tBsbBT() {
        return l1tBsbBT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.l1t_bsb_b_t
     *
     * @param l1tBsbBT the value for HF_hy_11.l1t_bsb_b_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setL1tBsbBT(Float l1tBsbBT) {
        this.l1tBsbBT = l1tBsbBT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.l1ltfj_a_t
     *
     * @return the value of HF_hy_11.l1ltfj_a_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getL1ltfjAT() {
        return l1ltfjAT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.l1ltfj_a_t
     *
     * @param l1ltfjAT the value for HF_hy_11.l1ltfj_a_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setL1ltfjAT(Float l1ltfjAT) {
        this.l1ltfjAT = l1ltfjAT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.l1ltfj_b_t
     *
     * @return the value of HF_hy_11.l1ltfj_b_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getL1ltfjBT() {
        return l1ltfjBT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.l1ltfj_b_t
     *
     * @param l1ltfjBT the value for HF_hy_11.l1ltfj_b_t
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setL1ltfjBT(Float l1ltfjBT) {
        this.l1ltfjBT = l1ltfjBT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t1_rf_1_ht
     *
     * @return the value of HF_hy_11.t1_rf_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT1Rf1Ht() {
        return t1Rf1Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t1_rf_1_ht
     *
     * @param t1Rf1Ht the value for HF_hy_11.t1_rf_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT1Rf1Ht(Float t1Rf1Ht) {
        this.t1Rf1Ht = t1Rf1Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t1_rf_1_st
     *
     * @return the value of HF_hy_11.t1_rf_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT1Rf1St() {
        return t1Rf1St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t1_rf_1_st
     *
     * @param t1Rf1St the value for HF_hy_11.t1_rf_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT1Rf1St(Float t1Rf1St) {
        this.t1Rf1St = t1Rf1St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t1_b1_1_ht
     *
     * @return the value of HF_hy_11.t1_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT1B11Ht() {
        return t1B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t1_b1_1_ht
     *
     * @param t1B11Ht the value for HF_hy_11.t1_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT1B11Ht(Float t1B11Ht) {
        this.t1B11Ht = t1B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t1_b1_1_st
     *
     * @return the value of HF_hy_11.t1_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT1B11St() {
        return t1B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t1_b1_1_st
     *
     * @param t1B11St the value for HF_hy_11.t1_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT1B11St(Float t1B11St) {
        this.t1B11St = t1B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t2_rf_1_ht
     *
     * @return the value of HF_hy_11.t2_rf_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT2Rf1Ht() {
        return t2Rf1Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t2_rf_1_ht
     *
     * @param t2Rf1Ht the value for HF_hy_11.t2_rf_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT2Rf1Ht(Float t2Rf1Ht) {
        this.t2Rf1Ht = t2Rf1Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t2_rf_1_st
     *
     * @return the value of HF_hy_11.t2_rf_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT2Rf1St() {
        return t2Rf1St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t2_rf_1_st
     *
     * @param t2Rf1St the value for HF_hy_11.t2_rf_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT2Rf1St(Float t2Rf1St) {
        this.t2Rf1St = t2Rf1St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t2_b1_1_ht
     *
     * @return the value of HF_hy_11.t2_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT2B11Ht() {
        return t2B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t2_b1_1_ht
     *
     * @param t2B11Ht the value for HF_hy_11.t2_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT2B11Ht(Float t2B11Ht) {
        this.t2B11Ht = t2B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t2_b1_1_st
     *
     * @return the value of HF_hy_11.t2_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT2B11St() {
        return t2B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t2_b1_1_st
     *
     * @param t2B11St the value for HF_hy_11.t2_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT2B11St(Float t2B11St) {
        this.t2B11St = t2B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t3_rf_1_ht
     *
     * @return the value of HF_hy_11.t3_rf_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT3Rf1Ht() {
        return t3Rf1Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t3_rf_1_ht
     *
     * @param t3Rf1Ht the value for HF_hy_11.t3_rf_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT3Rf1Ht(Float t3Rf1Ht) {
        this.t3Rf1Ht = t3Rf1Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t3_rf_1_st
     *
     * @return the value of HF_hy_11.t3_rf_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT3Rf1St() {
        return t3Rf1St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t3_rf_1_st
     *
     * @param t3Rf1St the value for HF_hy_11.t3_rf_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT3Rf1St(Float t3Rf1St) {
        this.t3Rf1St = t3Rf1St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t3_b1_1_ht
     *
     * @return the value of HF_hy_11.t3_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT3B11Ht() {
        return t3B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t3_b1_1_ht
     *
     * @param t3B11Ht the value for HF_hy_11.t3_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT3B11Ht(Float t3B11Ht) {
        this.t3B11Ht = t3B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t3_b1_1_st
     *
     * @return the value of HF_hy_11.t3_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT3B11St() {
        return t3B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t3_b1_1_st
     *
     * @param t3B11St the value for HF_hy_11.t3_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT3B11St(Float t3B11St) {
        this.t3B11St = t3B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t4_rf_1_ht
     *
     * @return the value of HF_hy_11.t4_rf_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT4Rf1Ht() {
        return t4Rf1Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t4_rf_1_ht
     *
     * @param t4Rf1Ht the value for HF_hy_11.t4_rf_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT4Rf1Ht(Float t4Rf1Ht) {
        this.t4Rf1Ht = t4Rf1Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t4_rf_1_st
     *
     * @return the value of HF_hy_11.t4_rf_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT4Rf1St() {
        return t4Rf1St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t4_rf_1_st
     *
     * @param t4Rf1St the value for HF_hy_11.t4_rf_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT4Rf1St(Float t4Rf1St) {
        this.t4Rf1St = t4Rf1St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t4_b1_1_ht
     *
     * @return the value of HF_hy_11.t4_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT4B11Ht() {
        return t4B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t4_b1_1_ht
     *
     * @param t4B11Ht the value for HF_hy_11.t4_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT4B11Ht(Float t4B11Ht) {
        this.t4B11Ht = t4B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t4_b1_1_st
     *
     * @return the value of HF_hy_11.t4_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT4B11St() {
        return t4B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t4_b1_1_st
     *
     * @param t4B11St the value for HF_hy_11.t4_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT4B11St(Float t4B11St) {
        this.t4B11St = t4B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t5_rf_1_ht
     *
     * @return the value of HF_hy_11.t5_rf_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT5Rf1Ht() {
        return t5Rf1Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t5_rf_1_ht
     *
     * @param t5Rf1Ht the value for HF_hy_11.t5_rf_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT5Rf1Ht(Float t5Rf1Ht) {
        this.t5Rf1Ht = t5Rf1Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t5_rf_1_st
     *
     * @return the value of HF_hy_11.t5_rf_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT5Rf1St() {
        return t5Rf1St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t5_rf_1_st
     *
     * @param t5Rf1St the value for HF_hy_11.t5_rf_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT5Rf1St(Float t5Rf1St) {
        this.t5Rf1St = t5Rf1St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t5_b1_1_ht
     *
     * @return the value of HF_hy_11.t5_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT5B11Ht() {
        return t5B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t5_b1_1_ht
     *
     * @param t5B11Ht the value for HF_hy_11.t5_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT5B11Ht(Float t5B11Ht) {
        this.t5B11Ht = t5B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t5_b1_1_st
     *
     * @return the value of HF_hy_11.t5_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT5B11St() {
        return t5B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t5_b1_1_st
     *
     * @param t5B11St the value for HF_hy_11.t5_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT5B11St(Float t5B11St) {
        this.t5B11St = t5B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t6_b1_1_ht
     *
     * @return the value of HF_hy_11.t6_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT6B11Ht() {
        return t6B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t6_b1_1_ht
     *
     * @param t6B11Ht the value for HF_hy_11.t6_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT6B11Ht(Float t6B11Ht) {
        this.t6B11Ht = t6B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t6_b1_1_st
     *
     * @return the value of HF_hy_11.t6_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT6B11St() {
        return t6B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t6_b1_1_st
     *
     * @param t6B11St the value for HF_hy_11.t6_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT6B11St(Float t6B11St) {
        this.t6B11St = t6B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t6_b1_2_ht
     *
     * @return the value of HF_hy_11.t6_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT6B12Ht() {
        return t6B12Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t6_b1_2_ht
     *
     * @param t6B12Ht the value for HF_hy_11.t6_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT6B12Ht(Float t6B12Ht) {
        this.t6B12Ht = t6B12Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t6_b1_2_st
     *
     * @return the value of HF_hy_11.t6_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT6B12St() {
        return t6B12St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t6_b1_2_st
     *
     * @param t6B12St the value for HF_hy_11.t6_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT6B12St(Float t6B12St) {
        this.t6B12St = t6B12St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t7_b1_1_ht
     *
     * @return the value of HF_hy_11.t7_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT7B11Ht() {
        return t7B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t7_b1_1_ht
     *
     * @param t7B11Ht the value for HF_hy_11.t7_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT7B11Ht(Float t7B11Ht) {
        this.t7B11Ht = t7B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t7_b1_1_st
     *
     * @return the value of HF_hy_11.t7_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT7B11St() {
        return t7B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t7_b1_1_st
     *
     * @param t7B11St the value for HF_hy_11.t7_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT7B11St(Float t7B11St) {
        this.t7B11St = t7B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t7_b1_2_ht
     *
     * @return the value of HF_hy_11.t7_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT7B12Ht() {
        return t7B12Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t7_b1_2_ht
     *
     * @param t7B12Ht the value for HF_hy_11.t7_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT7B12Ht(Float t7B12Ht) {
        this.t7B12Ht = t7B12Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t7_b1_2_st
     *
     * @return the value of HF_hy_11.t7_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT7B12St() {
        return t7B12St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t7_b1_2_st
     *
     * @param t7B12St the value for HF_hy_11.t7_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT7B12St(Float t7B12St) {
        this.t7B12St = t7B12St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t8_b1_1_ht
     *
     * @return the value of HF_hy_11.t8_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT8B11Ht() {
        return t8B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t8_b1_1_ht
     *
     * @param t8B11Ht the value for HF_hy_11.t8_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT8B11Ht(Float t8B11Ht) {
        this.t8B11Ht = t8B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t8_b1_1_st
     *
     * @return the value of HF_hy_11.t8_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT8B11St() {
        return t8B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t8_b1_1_st
     *
     * @param t8B11St the value for HF_hy_11.t8_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT8B11St(Float t8B11St) {
        this.t8B11St = t8B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t8_b1_2_ht
     *
     * @return the value of HF_hy_11.t8_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT8B12Ht() {
        return t8B12Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t8_b1_2_ht
     *
     * @param t8B12Ht the value for HF_hy_11.t8_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT8B12Ht(Float t8B12Ht) {
        this.t8B12Ht = t8B12Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t8_b1_2_st
     *
     * @return the value of HF_hy_11.t8_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT8B12St() {
        return t8B12St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t8_b1_2_st
     *
     * @param t8B12St the value for HF_hy_11.t8_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT8B12St(Float t8B12St) {
        this.t8B12St = t8B12St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t9_b1_1_ht
     *
     * @return the value of HF_hy_11.t9_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT9B11Ht() {
        return t9B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t9_b1_1_ht
     *
     * @param t9B11Ht the value for HF_hy_11.t9_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT9B11Ht(Float t9B11Ht) {
        this.t9B11Ht = t9B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t9_b1_1_st
     *
     * @return the value of HF_hy_11.t9_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT9B11St() {
        return t9B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t9_b1_1_st
     *
     * @param t9B11St the value for HF_hy_11.t9_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT9B11St(Float t9B11St) {
        this.t9B11St = t9B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t9_b1_2_ht
     *
     * @return the value of HF_hy_11.t9_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT9B12Ht() {
        return t9B12Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t9_b1_2_ht
     *
     * @param t9B12Ht the value for HF_hy_11.t9_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT9B12Ht(Float t9B12Ht) {
        this.t9B12Ht = t9B12Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t9_b1_2_st
     *
     * @return the value of HF_hy_11.t9_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT9B12St() {
        return t9B12St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t9_b1_2_st
     *
     * @param t9B12St the value for HF_hy_11.t9_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT9B12St(Float t9B12St) {
        this.t9B12St = t9B12St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t10_b1_1_ht
     *
     * @return the value of HF_hy_11.t10_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT10B11Ht() {
        return t10B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t10_b1_1_ht
     *
     * @param t10B11Ht the value for HF_hy_11.t10_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT10B11Ht(Float t10B11Ht) {
        this.t10B11Ht = t10B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t10_b1_1_st
     *
     * @return the value of HF_hy_11.t10_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT10B11St() {
        return t10B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t10_b1_1_st
     *
     * @param t10B11St the value for HF_hy_11.t10_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT10B11St(Float t10B11St) {
        this.t10B11St = t10B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t10_b1_2_ht
     *
     * @return the value of HF_hy_11.t10_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT10B12Ht() {
        return t10B12Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t10_b1_2_ht
     *
     * @param t10B12Ht the value for HF_hy_11.t10_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT10B12Ht(Float t10B12Ht) {
        this.t10B12Ht = t10B12Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t10_b1_2_st
     *
     * @return the value of HF_hy_11.t10_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT10B12St() {
        return t10B12St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t10_b1_2_st
     *
     * @param t10B12St the value for HF_hy_11.t10_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT10B12St(Float t10B12St) {
        this.t10B12St = t10B12St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t11_b1_1_ht
     *
     * @return the value of HF_hy_11.t11_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT11B11Ht() {
        return t11B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t11_b1_1_ht
     *
     * @param t11B11Ht the value for HF_hy_11.t11_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT11B11Ht(Float t11B11Ht) {
        this.t11B11Ht = t11B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t11_b1_1_st
     *
     * @return the value of HF_hy_11.t11_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT11B11St() {
        return t11B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t11_b1_1_st
     *
     * @param t11B11St the value for HF_hy_11.t11_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT11B11St(Float t11B11St) {
        this.t11B11St = t11B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t11_b1_2_ht
     *
     * @return the value of HF_hy_11.t11_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT11B12Ht() {
        return t11B12Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t11_b1_2_ht
     *
     * @param t11B12Ht the value for HF_hy_11.t11_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT11B12Ht(Float t11B12Ht) {
        this.t11B12Ht = t11B12Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t11_b1_2_st
     *
     * @return the value of HF_hy_11.t11_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT11B12St() {
        return t11B12St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t11_b1_2_st
     *
     * @param t11B12St the value for HF_hy_11.t11_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT11B12St(Float t11B12St) {
        this.t11B12St = t11B12St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t12_b1_1_ht
     *
     * @return the value of HF_hy_11.t12_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT12B11Ht() {
        return t12B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t12_b1_1_ht
     *
     * @param t12B11Ht the value for HF_hy_11.t12_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT12B11Ht(Float t12B11Ht) {
        this.t12B11Ht = t12B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t12_b1_1_st
     *
     * @return the value of HF_hy_11.t12_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT12B11St() {
        return t12B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t12_b1_1_st
     *
     * @param t12B11St the value for HF_hy_11.t12_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT12B11St(Float t12B11St) {
        this.t12B11St = t12B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t12_b1_2_ht
     *
     * @return the value of HF_hy_11.t12_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT12B12Ht() {
        return t12B12Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t12_b1_2_ht
     *
     * @param t12B12Ht the value for HF_hy_11.t12_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT12B12Ht(Float t12B12Ht) {
        this.t12B12Ht = t12B12Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t12_b1_2_st
     *
     * @return the value of HF_hy_11.t12_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT12B12St() {
        return t12B12St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t12_b1_2_st
     *
     * @param t12B12St the value for HF_hy_11.t12_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT12B12St(Float t12B12St) {
        this.t12B12St = t12B12St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t13_b1_1_ht
     *
     * @return the value of HF_hy_11.t13_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT13B11Ht() {
        return t13B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t13_b1_1_ht
     *
     * @param t13B11Ht the value for HF_hy_11.t13_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT13B11Ht(Float t13B11Ht) {
        this.t13B11Ht = t13B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t13_b1_1_st
     *
     * @return the value of HF_hy_11.t13_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT13B11St() {
        return t13B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t13_b1_1_st
     *
     * @param t13B11St the value for HF_hy_11.t13_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT13B11St(Float t13B11St) {
        this.t13B11St = t13B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t13_b1_2_ht
     *
     * @return the value of HF_hy_11.t13_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT13B12Ht() {
        return t13B12Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t13_b1_2_ht
     *
     * @param t13B12Ht the value for HF_hy_11.t13_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT13B12Ht(Float t13B12Ht) {
        this.t13B12Ht = t13B12Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t13_b1_2_st
     *
     * @return the value of HF_hy_11.t13_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT13B12St() {
        return t13B12St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t13_b1_2_st
     *
     * @param t13B12St the value for HF_hy_11.t13_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT13B12St(Float t13B12St) {
        this.t13B12St = t13B12St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t14_rf_1_ht
     *
     * @return the value of HF_hy_11.t14_rf_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT14Rf1Ht() {
        return t14Rf1Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t14_rf_1_ht
     *
     * @param t14Rf1Ht the value for HF_hy_11.t14_rf_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT14Rf1Ht(Float t14Rf1Ht) {
        this.t14Rf1Ht = t14Rf1Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t14_rf_1_st
     *
     * @return the value of HF_hy_11.t14_rf_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT14Rf1St() {
        return t14Rf1St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t14_rf_1_st
     *
     * @param t14Rf1St the value for HF_hy_11.t14_rf_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT14Rf1St(Float t14Rf1St) {
        this.t14Rf1St = t14Rf1St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t14_rf_2_ht
     *
     * @return the value of HF_hy_11.t14_rf_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT14Rf2Ht() {
        return t14Rf2Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t14_rf_2_ht
     *
     * @param t14Rf2Ht the value for HF_hy_11.t14_rf_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT14Rf2Ht(Float t14Rf2Ht) {
        this.t14Rf2Ht = t14Rf2Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t14_rf_2_st
     *
     * @return the value of HF_hy_11.t14_rf_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT14Rf2St() {
        return t14Rf2St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t14_rf_2_st
     *
     * @param t14Rf2St the value for HF_hy_11.t14_rf_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT14Rf2St(Float t14Rf2St) {
        this.t14Rf2St = t14Rf2St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t14_b1_1_ht
     *
     * @return the value of HF_hy_11.t14_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT14B11Ht() {
        return t14B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t14_b1_1_ht
     *
     * @param t14B11Ht the value for HF_hy_11.t14_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT14B11Ht(Float t14B11Ht) {
        this.t14B11Ht = t14B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t14_b1_1_st
     *
     * @return the value of HF_hy_11.t14_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT14B11St() {
        return t14B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t14_b1_1_st
     *
     * @param t14B11St the value for HF_hy_11.t14_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT14B11St(Float t14B11St) {
        this.t14B11St = t14B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t14_b1_2_ht
     *
     * @return the value of HF_hy_11.t14_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT14B12Ht() {
        return t14B12Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t14_b1_2_ht
     *
     * @param t14B12Ht the value for HF_hy_11.t14_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT14B12Ht(Float t14B12Ht) {
        this.t14B12Ht = t14B12Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t14_b1_2_st
     *
     * @return the value of HF_hy_11.t14_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT14B12St() {
        return t14B12St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t14_b1_2_st
     *
     * @param t14B12St the value for HF_hy_11.t14_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT14B12St(Float t14B12St) {
        this.t14B12St = t14B12St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t15_b1_1_ht
     *
     * @return the value of HF_hy_11.t15_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT15B11Ht() {
        return t15B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t15_b1_1_ht
     *
     * @param t15B11Ht the value for HF_hy_11.t15_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT15B11Ht(Float t15B11Ht) {
        this.t15B11Ht = t15B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t15_b1_1_st
     *
     * @return the value of HF_hy_11.t15_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT15B11St() {
        return t15B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t15_b1_1_st
     *
     * @param t15B11St the value for HF_hy_11.t15_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT15B11St(Float t15B11St) {
        this.t15B11St = t15B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t15_b1_2_ht
     *
     * @return the value of HF_hy_11.t15_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT15B12Ht() {
        return t15B12Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t15_b1_2_ht
     *
     * @param t15B12Ht the value for HF_hy_11.t15_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT15B12Ht(Float t15B12Ht) {
        this.t15B12Ht = t15B12Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t15_b1_2_st
     *
     * @return the value of HF_hy_11.t15_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT15B12St() {
        return t15B12St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t15_b1_2_st
     *
     * @param t15B12St the value for HF_hy_11.t15_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT15B12St(Float t15B12St) {
        this.t15B12St = t15B12St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t16_b1_1_ht
     *
     * @return the value of HF_hy_11.t16_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT16B11Ht() {
        return t16B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t16_b1_1_ht
     *
     * @param t16B11Ht the value for HF_hy_11.t16_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT16B11Ht(Float t16B11Ht) {
        this.t16B11Ht = t16B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t16_b1_1_st
     *
     * @return the value of HF_hy_11.t16_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT16B11St() {
        return t16B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t16_b1_1_st
     *
     * @param t16B11St the value for HF_hy_11.t16_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT16B11St(Float t16B11St) {
        this.t16B11St = t16B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t16_b1_2_ht
     *
     * @return the value of HF_hy_11.t16_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT16B12Ht() {
        return t16B12Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t16_b1_2_ht
     *
     * @param t16B12Ht the value for HF_hy_11.t16_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT16B12Ht(Float t16B12Ht) {
        this.t16B12Ht = t16B12Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t16_b1_2_st
     *
     * @return the value of HF_hy_11.t16_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT16B12St() {
        return t16B12St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t16_b1_2_st
     *
     * @param t16B12St the value for HF_hy_11.t16_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT16B12St(Float t16B12St) {
        this.t16B12St = t16B12St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t17_b1_1_ht
     *
     * @return the value of HF_hy_11.t17_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT17B11Ht() {
        return t17B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t17_b1_1_ht
     *
     * @param t17B11Ht the value for HF_hy_11.t17_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT17B11Ht(Float t17B11Ht) {
        this.t17B11Ht = t17B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t17_b1_1_st
     *
     * @return the value of HF_hy_11.t17_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT17B11St() {
        return t17B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t17_b1_1_st
     *
     * @param t17B11St the value for HF_hy_11.t17_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT17B11St(Float t17B11St) {
        this.t17B11St = t17B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t17_b1_2_ht
     *
     * @return the value of HF_hy_11.t17_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT17B12Ht() {
        return t17B12Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t17_b1_2_ht
     *
     * @param t17B12Ht the value for HF_hy_11.t17_b1_2_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT17B12Ht(Float t17B12Ht) {
        this.t17B12Ht = t17B12Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t17_b1_2_st
     *
     * @return the value of HF_hy_11.t17_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT17B12St() {
        return t17B12St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t17_b1_2_st
     *
     * @param t17B12St the value for HF_hy_11.t17_b1_2_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT17B12St(Float t17B12St) {
        this.t17B12St = t17B12St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t18_b1_1_ht
     *
     * @return the value of HF_hy_11.t18_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT18B11Ht() {
        return t18B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t18_b1_1_ht
     *
     * @param t18B11Ht the value for HF_hy_11.t18_b1_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT18B11Ht(Float t18B11Ht) {
        this.t18B11Ht = t18B11Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t18_b1_1_st
     *
     * @return the value of HF_hy_11.t18_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT18B11St() {
        return t18B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t18_b1_1_st
     *
     * @param t18B11St the value for HF_hy_11.t18_b1_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT18B11St(Float t18B11St) {
        this.t18B11St = t18B11St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t18_rf_1_ht
     *
     * @return the value of HF_hy_11.t18_rf_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT18Rf1Ht() {
        return t18Rf1Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t18_rf_1_ht
     *
     * @param t18Rf1Ht the value for HF_hy_11.t18_rf_1_ht
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT18Rf1Ht(Float t18Rf1Ht) {
        this.t18Rf1Ht = t18Rf1Ht;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_11.t18_rf_1_st
     *
     * @return the value of HF_hy_11.t18_rf_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public Float getT18Rf1St() {
        return t18Rf1St;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_11.t18_rf_1_st
     *
     * @param t18Rf1St the value for HF_hy_11.t18_rf_1_st
     *
     * @mbg.generated Wed Oct 11 14:18:08 CST 2017
     */
    public void setT18Rf1St(Float t18Rf1St) {
        this.t18Rf1St = t18Rf1St;
    }

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getTimeNew() {
		return timeNew;
	}

	public void setTimeNew(String timeNew) {
		this.timeNew = timeNew;
	}
    
    
    
}