package com.firstCapacity.business.HeFeiPower.entity;

import java.io.Serializable;
import java.util.Date;

public class HF_hy_09 implements Serializable{
	
	
	private static final long serialVersionUID = 1L;
	
	
    private String startTime;
    
    private String endTime;
    
    private String timeNew;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.Time
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_fd
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1Fd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_t3
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1T3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_h1
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1H1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_t4
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1T4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_h2
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1H2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_co2
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1Co2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_d1
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1D1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_d3
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1D3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_ffs5
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1Ffs5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_ffs6
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1Ffs6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_pfk
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1Pfk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_pfg
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1Pfg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_hfs5
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1Hfs5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_hfs6
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1Hfs6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_sf5
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1Sf5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_sf6
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1Sf6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_js2
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1Js2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_s1
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1S1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_s2
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1S2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_s3
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1S3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_s4
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1S4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_p1
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1P1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_p2
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1P2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_p3
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1P3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_p4
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1P4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_fmax
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1Fmax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_fmin
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1Fmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_jssx
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1Jssx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_jsxx
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1Jsxx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_xfmax
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1Xfmax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_xfmin
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1Xfmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_hfmax
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1Hfmax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_hfmin
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1Hfmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_sfsd
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1Sfsd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_p
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1P;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_i
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1I;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_d
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1D;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_co2_sd
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1Co2Sd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_1p
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf11p;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_1i
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf11i;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_1d
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf11d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_hfts
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1Hfts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_2p
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf12p;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_2i
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf12i;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1_2d
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf12d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1jsqdt
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1jsqdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1jstzt
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1jstzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1zlzr_am
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1zlzrAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1ys_am
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1ysAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1ddf_am
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1ddfAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1sjam
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1sjam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1djam
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1djam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1xff_am
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1xffAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1hff_am
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1hffAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_1jst_s
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5Rf1jstS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_09.t5_rf_pg
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    private Float t5RfPg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.Time
     *
     * @return the value of HF_hy_09.Time
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.Time
     *
     * @param time the value for HF_hy_09.Time
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_fd
     *
     * @return the value of HF_hy_09.t5_rf_1_fd
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1Fd() {
        return t5Rf1Fd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_fd
     *
     * @param t5Rf1Fd the value for HF_hy_09.t5_rf_1_fd
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1Fd(Float t5Rf1Fd) {
        this.t5Rf1Fd = t5Rf1Fd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_t3
     *
     * @return the value of HF_hy_09.t5_rf_1_t3
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1T3() {
        return t5Rf1T3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_t3
     *
     * @param t5Rf1T3 the value for HF_hy_09.t5_rf_1_t3
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1T3(Float t5Rf1T3) {
        this.t5Rf1T3 = t5Rf1T3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_h1
     *
     * @return the value of HF_hy_09.t5_rf_1_h1
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1H1() {
        return t5Rf1H1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_h1
     *
     * @param t5Rf1H1 the value for HF_hy_09.t5_rf_1_h1
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1H1(Float t5Rf1H1) {
        this.t5Rf1H1 = t5Rf1H1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_t4
     *
     * @return the value of HF_hy_09.t5_rf_1_t4
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1T4() {
        return t5Rf1T4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_t4
     *
     * @param t5Rf1T4 the value for HF_hy_09.t5_rf_1_t4
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1T4(Float t5Rf1T4) {
        this.t5Rf1T4 = t5Rf1T4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_h2
     *
     * @return the value of HF_hy_09.t5_rf_1_h2
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1H2() {
        return t5Rf1H2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_h2
     *
     * @param t5Rf1H2 the value for HF_hy_09.t5_rf_1_h2
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1H2(Float t5Rf1H2) {
        this.t5Rf1H2 = t5Rf1H2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_co2
     *
     * @return the value of HF_hy_09.t5_rf_1_co2
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1Co2() {
        return t5Rf1Co2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_co2
     *
     * @param t5Rf1Co2 the value for HF_hy_09.t5_rf_1_co2
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1Co2(Float t5Rf1Co2) {
        this.t5Rf1Co2 = t5Rf1Co2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_d1
     *
     * @return the value of HF_hy_09.t5_rf_1_d1
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1D1() {
        return t5Rf1D1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_d1
     *
     * @param t5Rf1D1 the value for HF_hy_09.t5_rf_1_d1
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1D1(Float t5Rf1D1) {
        this.t5Rf1D1 = t5Rf1D1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_d3
     *
     * @return the value of HF_hy_09.t5_rf_1_d3
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1D3() {
        return t5Rf1D3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_d3
     *
     * @param t5Rf1D3 the value for HF_hy_09.t5_rf_1_d3
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1D3(Float t5Rf1D3) {
        this.t5Rf1D3 = t5Rf1D3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_ffs5
     *
     * @return the value of HF_hy_09.t5_rf_1_ffs5
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1Ffs5() {
        return t5Rf1Ffs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_ffs5
     *
     * @param t5Rf1Ffs5 the value for HF_hy_09.t5_rf_1_ffs5
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1Ffs5(Float t5Rf1Ffs5) {
        this.t5Rf1Ffs5 = t5Rf1Ffs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_ffs6
     *
     * @return the value of HF_hy_09.t5_rf_1_ffs6
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1Ffs6() {
        return t5Rf1Ffs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_ffs6
     *
     * @param t5Rf1Ffs6 the value for HF_hy_09.t5_rf_1_ffs6
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1Ffs6(Float t5Rf1Ffs6) {
        this.t5Rf1Ffs6 = t5Rf1Ffs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_pfk
     *
     * @return the value of HF_hy_09.t5_rf_1_pfk
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1Pfk() {
        return t5Rf1Pfk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_pfk
     *
     * @param t5Rf1Pfk the value for HF_hy_09.t5_rf_1_pfk
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1Pfk(Float t5Rf1Pfk) {
        this.t5Rf1Pfk = t5Rf1Pfk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_pfg
     *
     * @return the value of HF_hy_09.t5_rf_1_pfg
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1Pfg() {
        return t5Rf1Pfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_pfg
     *
     * @param t5Rf1Pfg the value for HF_hy_09.t5_rf_1_pfg
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1Pfg(Float t5Rf1Pfg) {
        this.t5Rf1Pfg = t5Rf1Pfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_hfs5
     *
     * @return the value of HF_hy_09.t5_rf_1_hfs5
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1Hfs5() {
        return t5Rf1Hfs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_hfs5
     *
     * @param t5Rf1Hfs5 the value for HF_hy_09.t5_rf_1_hfs5
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1Hfs5(Float t5Rf1Hfs5) {
        this.t5Rf1Hfs5 = t5Rf1Hfs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_hfs6
     *
     * @return the value of HF_hy_09.t5_rf_1_hfs6
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1Hfs6() {
        return t5Rf1Hfs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_hfs6
     *
     * @param t5Rf1Hfs6 the value for HF_hy_09.t5_rf_1_hfs6
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1Hfs6(Float t5Rf1Hfs6) {
        this.t5Rf1Hfs6 = t5Rf1Hfs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_sf5
     *
     * @return the value of HF_hy_09.t5_rf_1_sf5
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1Sf5() {
        return t5Rf1Sf5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_sf5
     *
     * @param t5Rf1Sf5 the value for HF_hy_09.t5_rf_1_sf5
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1Sf5(Float t5Rf1Sf5) {
        this.t5Rf1Sf5 = t5Rf1Sf5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_sf6
     *
     * @return the value of HF_hy_09.t5_rf_1_sf6
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1Sf6() {
        return t5Rf1Sf6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_sf6
     *
     * @param t5Rf1Sf6 the value for HF_hy_09.t5_rf_1_sf6
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1Sf6(Float t5Rf1Sf6) {
        this.t5Rf1Sf6 = t5Rf1Sf6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_js2
     *
     * @return the value of HF_hy_09.t5_rf_1_js2
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1Js2() {
        return t5Rf1Js2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_js2
     *
     * @param t5Rf1Js2 the value for HF_hy_09.t5_rf_1_js2
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1Js2(Float t5Rf1Js2) {
        this.t5Rf1Js2 = t5Rf1Js2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_s1
     *
     * @return the value of HF_hy_09.t5_rf_1_s1
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1S1() {
        return t5Rf1S1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_s1
     *
     * @param t5Rf1S1 the value for HF_hy_09.t5_rf_1_s1
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1S1(Float t5Rf1S1) {
        this.t5Rf1S1 = t5Rf1S1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_s2
     *
     * @return the value of HF_hy_09.t5_rf_1_s2
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1S2() {
        return t5Rf1S2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_s2
     *
     * @param t5Rf1S2 the value for HF_hy_09.t5_rf_1_s2
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1S2(Float t5Rf1S2) {
        this.t5Rf1S2 = t5Rf1S2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_s3
     *
     * @return the value of HF_hy_09.t5_rf_1_s3
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1S3() {
        return t5Rf1S3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_s3
     *
     * @param t5Rf1S3 the value for HF_hy_09.t5_rf_1_s3
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1S3(Float t5Rf1S3) {
        this.t5Rf1S3 = t5Rf1S3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_s4
     *
     * @return the value of HF_hy_09.t5_rf_1_s4
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1S4() {
        return t5Rf1S4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_s4
     *
     * @param t5Rf1S4 the value for HF_hy_09.t5_rf_1_s4
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1S4(Float t5Rf1S4) {
        this.t5Rf1S4 = t5Rf1S4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_p1
     *
     * @return the value of HF_hy_09.t5_rf_1_p1
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1P1() {
        return t5Rf1P1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_p1
     *
     * @param t5Rf1P1 the value for HF_hy_09.t5_rf_1_p1
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1P1(Float t5Rf1P1) {
        this.t5Rf1P1 = t5Rf1P1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_p2
     *
     * @return the value of HF_hy_09.t5_rf_1_p2
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1P2() {
        return t5Rf1P2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_p2
     *
     * @param t5Rf1P2 the value for HF_hy_09.t5_rf_1_p2
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1P2(Float t5Rf1P2) {
        this.t5Rf1P2 = t5Rf1P2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_p3
     *
     * @return the value of HF_hy_09.t5_rf_1_p3
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1P3() {
        return t5Rf1P3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_p3
     *
     * @param t5Rf1P3 the value for HF_hy_09.t5_rf_1_p3
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1P3(Float t5Rf1P3) {
        this.t5Rf1P3 = t5Rf1P3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_p4
     *
     * @return the value of HF_hy_09.t5_rf_1_p4
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1P4() {
        return t5Rf1P4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_p4
     *
     * @param t5Rf1P4 the value for HF_hy_09.t5_rf_1_p4
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1P4(Float t5Rf1P4) {
        this.t5Rf1P4 = t5Rf1P4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_fmax
     *
     * @return the value of HF_hy_09.t5_rf_1_fmax
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1Fmax() {
        return t5Rf1Fmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_fmax
     *
     * @param t5Rf1Fmax the value for HF_hy_09.t5_rf_1_fmax
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1Fmax(Float t5Rf1Fmax) {
        this.t5Rf1Fmax = t5Rf1Fmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_fmin
     *
     * @return the value of HF_hy_09.t5_rf_1_fmin
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1Fmin() {
        return t5Rf1Fmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_fmin
     *
     * @param t5Rf1Fmin the value for HF_hy_09.t5_rf_1_fmin
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1Fmin(Float t5Rf1Fmin) {
        this.t5Rf1Fmin = t5Rf1Fmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_jssx
     *
     * @return the value of HF_hy_09.t5_rf_1_jssx
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1Jssx() {
        return t5Rf1Jssx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_jssx
     *
     * @param t5Rf1Jssx the value for HF_hy_09.t5_rf_1_jssx
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1Jssx(Float t5Rf1Jssx) {
        this.t5Rf1Jssx = t5Rf1Jssx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_jsxx
     *
     * @return the value of HF_hy_09.t5_rf_1_jsxx
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1Jsxx() {
        return t5Rf1Jsxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_jsxx
     *
     * @param t5Rf1Jsxx the value for HF_hy_09.t5_rf_1_jsxx
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1Jsxx(Float t5Rf1Jsxx) {
        this.t5Rf1Jsxx = t5Rf1Jsxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_xfmax
     *
     * @return the value of HF_hy_09.t5_rf_1_xfmax
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1Xfmax() {
        return t5Rf1Xfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_xfmax
     *
     * @param t5Rf1Xfmax the value for HF_hy_09.t5_rf_1_xfmax
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1Xfmax(Float t5Rf1Xfmax) {
        this.t5Rf1Xfmax = t5Rf1Xfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_xfmin
     *
     * @return the value of HF_hy_09.t5_rf_1_xfmin
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1Xfmin() {
        return t5Rf1Xfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_xfmin
     *
     * @param t5Rf1Xfmin the value for HF_hy_09.t5_rf_1_xfmin
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1Xfmin(Float t5Rf1Xfmin) {
        this.t5Rf1Xfmin = t5Rf1Xfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_hfmax
     *
     * @return the value of HF_hy_09.t5_rf_1_hfmax
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1Hfmax() {
        return t5Rf1Hfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_hfmax
     *
     * @param t5Rf1Hfmax the value for HF_hy_09.t5_rf_1_hfmax
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1Hfmax(Float t5Rf1Hfmax) {
        this.t5Rf1Hfmax = t5Rf1Hfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_hfmin
     *
     * @return the value of HF_hy_09.t5_rf_1_hfmin
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1Hfmin() {
        return t5Rf1Hfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_hfmin
     *
     * @param t5Rf1Hfmin the value for HF_hy_09.t5_rf_1_hfmin
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1Hfmin(Float t5Rf1Hfmin) {
        this.t5Rf1Hfmin = t5Rf1Hfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_sfsd
     *
     * @return the value of HF_hy_09.t5_rf_1_sfsd
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1Sfsd() {
        return t5Rf1Sfsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_sfsd
     *
     * @param t5Rf1Sfsd the value for HF_hy_09.t5_rf_1_sfsd
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1Sfsd(Float t5Rf1Sfsd) {
        this.t5Rf1Sfsd = t5Rf1Sfsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_p
     *
     * @return the value of HF_hy_09.t5_rf_1_p
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1P() {
        return t5Rf1P;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_p
     *
     * @param t5Rf1P the value for HF_hy_09.t5_rf_1_p
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1P(Float t5Rf1P) {
        this.t5Rf1P = t5Rf1P;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_i
     *
     * @return the value of HF_hy_09.t5_rf_1_i
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1I() {
        return t5Rf1I;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_i
     *
     * @param t5Rf1I the value for HF_hy_09.t5_rf_1_i
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1I(Float t5Rf1I) {
        this.t5Rf1I = t5Rf1I;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_d
     *
     * @return the value of HF_hy_09.t5_rf_1_d
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1D() {
        return t5Rf1D;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_d
     *
     * @param t5Rf1D the value for HF_hy_09.t5_rf_1_d
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1D(Float t5Rf1D) {
        this.t5Rf1D = t5Rf1D;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_co2_sd
     *
     * @return the value of HF_hy_09.t5_rf_1_co2_sd
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1Co2Sd() {
        return t5Rf1Co2Sd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_co2_sd
     *
     * @param t5Rf1Co2Sd the value for HF_hy_09.t5_rf_1_co2_sd
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1Co2Sd(Float t5Rf1Co2Sd) {
        this.t5Rf1Co2Sd = t5Rf1Co2Sd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_1p
     *
     * @return the value of HF_hy_09.t5_rf_1_1p
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf11p() {
        return t5Rf11p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_1p
     *
     * @param t5Rf11p the value for HF_hy_09.t5_rf_1_1p
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf11p(Float t5Rf11p) {
        this.t5Rf11p = t5Rf11p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_1i
     *
     * @return the value of HF_hy_09.t5_rf_1_1i
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf11i() {
        return t5Rf11i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_1i
     *
     * @param t5Rf11i the value for HF_hy_09.t5_rf_1_1i
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf11i(Float t5Rf11i) {
        this.t5Rf11i = t5Rf11i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_1d
     *
     * @return the value of HF_hy_09.t5_rf_1_1d
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf11d() {
        return t5Rf11d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_1d
     *
     * @param t5Rf11d the value for HF_hy_09.t5_rf_1_1d
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf11d(Float t5Rf11d) {
        this.t5Rf11d = t5Rf11d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_hfts
     *
     * @return the value of HF_hy_09.t5_rf_1_hfts
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1Hfts() {
        return t5Rf1Hfts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_hfts
     *
     * @param t5Rf1Hfts the value for HF_hy_09.t5_rf_1_hfts
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1Hfts(Float t5Rf1Hfts) {
        this.t5Rf1Hfts = t5Rf1Hfts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_2p
     *
     * @return the value of HF_hy_09.t5_rf_1_2p
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf12p() {
        return t5Rf12p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_2p
     *
     * @param t5Rf12p the value for HF_hy_09.t5_rf_1_2p
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf12p(Float t5Rf12p) {
        this.t5Rf12p = t5Rf12p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_2i
     *
     * @return the value of HF_hy_09.t5_rf_1_2i
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf12i() {
        return t5Rf12i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_2i
     *
     * @param t5Rf12i the value for HF_hy_09.t5_rf_1_2i
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf12i(Float t5Rf12i) {
        this.t5Rf12i = t5Rf12i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1_2d
     *
     * @return the value of HF_hy_09.t5_rf_1_2d
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf12d() {
        return t5Rf12d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1_2d
     *
     * @param t5Rf12d the value for HF_hy_09.t5_rf_1_2d
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf12d(Float t5Rf12d) {
        this.t5Rf12d = t5Rf12d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1jsqdt
     *
     * @return the value of HF_hy_09.t5_rf_1jsqdt
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1jsqdt() {
        return t5Rf1jsqdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1jsqdt
     *
     * @param t5Rf1jsqdt the value for HF_hy_09.t5_rf_1jsqdt
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1jsqdt(Float t5Rf1jsqdt) {
        this.t5Rf1jsqdt = t5Rf1jsqdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1jstzt
     *
     * @return the value of HF_hy_09.t5_rf_1jstzt
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1jstzt() {
        return t5Rf1jstzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1jstzt
     *
     * @param t5Rf1jstzt the value for HF_hy_09.t5_rf_1jstzt
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1jstzt(Float t5Rf1jstzt) {
        this.t5Rf1jstzt = t5Rf1jstzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1zlzr_am
     *
     * @return the value of HF_hy_09.t5_rf_1zlzr_am
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1zlzrAm() {
        return t5Rf1zlzrAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1zlzr_am
     *
     * @param t5Rf1zlzrAm the value for HF_hy_09.t5_rf_1zlzr_am
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1zlzrAm(Float t5Rf1zlzrAm) {
        this.t5Rf1zlzrAm = t5Rf1zlzrAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1ys_am
     *
     * @return the value of HF_hy_09.t5_rf_1ys_am
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1ysAm() {
        return t5Rf1ysAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1ys_am
     *
     * @param t5Rf1ysAm the value for HF_hy_09.t5_rf_1ys_am
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1ysAm(Float t5Rf1ysAm) {
        this.t5Rf1ysAm = t5Rf1ysAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1ddf_am
     *
     * @return the value of HF_hy_09.t5_rf_1ddf_am
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1ddfAm() {
        return t5Rf1ddfAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1ddf_am
     *
     * @param t5Rf1ddfAm the value for HF_hy_09.t5_rf_1ddf_am
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1ddfAm(Float t5Rf1ddfAm) {
        this.t5Rf1ddfAm = t5Rf1ddfAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1sjam
     *
     * @return the value of HF_hy_09.t5_rf_1sjam
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1sjam() {
        return t5Rf1sjam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1sjam
     *
     * @param t5Rf1sjam the value for HF_hy_09.t5_rf_1sjam
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1sjam(Float t5Rf1sjam) {
        this.t5Rf1sjam = t5Rf1sjam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1djam
     *
     * @return the value of HF_hy_09.t5_rf_1djam
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1djam() {
        return t5Rf1djam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1djam
     *
     * @param t5Rf1djam the value for HF_hy_09.t5_rf_1djam
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1djam(Float t5Rf1djam) {
        this.t5Rf1djam = t5Rf1djam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1xff_am
     *
     * @return the value of HF_hy_09.t5_rf_1xff_am
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1xffAm() {
        return t5Rf1xffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1xff_am
     *
     * @param t5Rf1xffAm the value for HF_hy_09.t5_rf_1xff_am
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1xffAm(Float t5Rf1xffAm) {
        this.t5Rf1xffAm = t5Rf1xffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1hff_am
     *
     * @return the value of HF_hy_09.t5_rf_1hff_am
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1hffAm() {
        return t5Rf1hffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1hff_am
     *
     * @param t5Rf1hffAm the value for HF_hy_09.t5_rf_1hff_am
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1hffAm(Float t5Rf1hffAm) {
        this.t5Rf1hffAm = t5Rf1hffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_1jst_s
     *
     * @return the value of HF_hy_09.t5_rf_1jst_s
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5Rf1jstS() {
        return t5Rf1jstS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_1jst_s
     *
     * @param t5Rf1jstS the value for HF_hy_09.t5_rf_1jst_s
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5Rf1jstS(Float t5Rf1jstS) {
        this.t5Rf1jstS = t5Rf1jstS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_09.t5_rf_pg
     *
     * @return the value of HF_hy_09.t5_rf_pg
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public Float getT5RfPg() {
        return t5RfPg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_09.t5_rf_pg
     *
     * @param t5RfPg the value for HF_hy_09.t5_rf_pg
     *
     * @mbg.generated Wed Oct 11 14:17:26 CST 2017
     */
    public void setT5RfPg(Float t5RfPg) {
        this.t5RfPg = t5RfPg;
    }

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getTimeNew() {
		return timeNew;
	}

	public void setTimeNew(String timeNew) {
		this.timeNew = timeNew;
	}
    
    
    
}