package com.firstCapacity.business.HeFeiPower.entity;

import java.io.Serializable;
import java.util.Date;

public class HF_hy_28 implements Serializable{
	
	private static final long serialVersionUID = 1L;
	
	
    private String startTime;
    
    private String endTime;
    
    private String timeNew;
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.Time
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.c_t_sp_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float ctSp3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.h_t_sp_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float htSp3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.cool_lwt_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float coolLwt3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.cool_ewt_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float coolEwt3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.cond_lwt_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float condLwt3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.cond_ewt_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float condEwt3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.high_p_t1_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float highPT13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.high_p_t2_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float highPT23;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.high_p_t3_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float highPT33;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.high_p_t4_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float highPT43;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.low_p_t1_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float lowPT13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.low_p_t2_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float lowPT23;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.low_p_t3_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float lowPT33;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.low_p_t4_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float lowPT43;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.cpt_1_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float cpt13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.cpt_2_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float cpt23;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.cpt_3_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float cpt33;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.cpt_4_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float cpt43;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.ncircuits_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float ncircuits3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.ncompressors_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float ncompressors3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.typeofcp_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float typeofcp3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.unit_status_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float unitStatus3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.unit_t_status_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float unitTStatus3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.operatingmode_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float operatingmode3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.cpofforon_1_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float cpofforon13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.cpchiler_1_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float cpchiler13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.cpheatpump_1_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float cpheatpump13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.cpofforon_2_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float cpofforon23;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.cpchiler_2_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float cpchiler23;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.cpheatpump_2_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float cpheatpump23;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.cpofforon_3_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float cpofforon33;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.cpchiler_3_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float cpchiler33;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.cpheatpump_3_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float cpheatpump33;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.cpofforon_4_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float cpofforon43;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.cpchiler_4_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float cpchiler43;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.cpheatpump_4_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float cpheatpump43;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.ahcp_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float ahcp3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.c_t_d_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float ctD3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.apofct_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float apofct3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.apofct_h_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float apofctH3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.hptd_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float hptd3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.apofhpt_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float apofhpt3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.apofhpt_h_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float apofhptH3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.tlincm_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float tlincm3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_28.tlinhpm_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    private Float tlinhpm3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.Time
     *
     * @return the value of HF_hy_28.Time
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.Time
     *
     * @param time the value for HF_hy_28.Time
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }


    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.cool_lwt_3
     *
     * @return the value of HF_hy_28.cool_lwt_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getCoolLwt3() {
        return coolLwt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.cool_lwt_3
     *
     * @param coolLwt3 the value for HF_hy_28.cool_lwt_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setCoolLwt3(Float coolLwt3) {
        this.coolLwt3 = coolLwt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.cool_ewt_3
     *
     * @return the value of HF_hy_28.cool_ewt_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getCoolEwt3() {
        return coolEwt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.cool_ewt_3
     *
     * @param coolEwt3 the value for HF_hy_28.cool_ewt_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setCoolEwt3(Float coolEwt3) {
        this.coolEwt3 = coolEwt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.cond_lwt_3
     *
     * @return the value of HF_hy_28.cond_lwt_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getCondLwt3() {
        return condLwt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.cond_lwt_3
     *
     * @param condLwt3 the value for HF_hy_28.cond_lwt_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setCondLwt3(Float condLwt3) {
        this.condLwt3 = condLwt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.cond_ewt_3
     *
     * @return the value of HF_hy_28.cond_ewt_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getCondEwt3() {
        return condEwt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.cond_ewt_3
     *
     * @param condEwt3 the value for HF_hy_28.cond_ewt_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setCondEwt3(Float condEwt3) {
        this.condEwt3 = condEwt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.high_p_t1_3
     *
     * @return the value of HF_hy_28.high_p_t1_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getHighPT13() {
        return highPT13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.high_p_t1_3
     *
     * @param highPT13 the value for HF_hy_28.high_p_t1_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setHighPT13(Float highPT13) {
        this.highPT13 = highPT13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.high_p_t2_3
     *
     * @return the value of HF_hy_28.high_p_t2_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getHighPT23() {
        return highPT23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.high_p_t2_3
     *
     * @param highPT23 the value for HF_hy_28.high_p_t2_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setHighPT23(Float highPT23) {
        this.highPT23 = highPT23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.high_p_t3_3
     *
     * @return the value of HF_hy_28.high_p_t3_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getHighPT33() {
        return highPT33;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.high_p_t3_3
     *
     * @param highPT33 the value for HF_hy_28.high_p_t3_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setHighPT33(Float highPT33) {
        this.highPT33 = highPT33;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.high_p_t4_3
     *
     * @return the value of HF_hy_28.high_p_t4_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getHighPT43() {
        return highPT43;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.high_p_t4_3
     *
     * @param highPT43 the value for HF_hy_28.high_p_t4_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setHighPT43(Float highPT43) {
        this.highPT43 = highPT43;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.low_p_t1_3
     *
     * @return the value of HF_hy_28.low_p_t1_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getLowPT13() {
        return lowPT13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.low_p_t1_3
     *
     * @param lowPT13 the value for HF_hy_28.low_p_t1_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setLowPT13(Float lowPT13) {
        this.lowPT13 = lowPT13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.low_p_t2_3
     *
     * @return the value of HF_hy_28.low_p_t2_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getLowPT23() {
        return lowPT23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.low_p_t2_3
     *
     * @param lowPT23 the value for HF_hy_28.low_p_t2_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setLowPT23(Float lowPT23) {
        this.lowPT23 = lowPT23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.low_p_t3_3
     *
     * @return the value of HF_hy_28.low_p_t3_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getLowPT33() {
        return lowPT33;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.low_p_t3_3
     *
     * @param lowPT33 the value for HF_hy_28.low_p_t3_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setLowPT33(Float lowPT33) {
        this.lowPT33 = lowPT33;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.low_p_t4_3
     *
     * @return the value of HF_hy_28.low_p_t4_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getLowPT43() {
        return lowPT43;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.low_p_t4_3
     *
     * @param lowPT43 the value for HF_hy_28.low_p_t4_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setLowPT43(Float lowPT43) {
        this.lowPT43 = lowPT43;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.cpt_1_3
     *
     * @return the value of HF_hy_28.cpt_1_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getCpt13() {
        return cpt13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.cpt_1_3
     *
     * @param cpt13 the value for HF_hy_28.cpt_1_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setCpt13(Float cpt13) {
        this.cpt13 = cpt13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.cpt_2_3
     *
     * @return the value of HF_hy_28.cpt_2_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getCpt23() {
        return cpt23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.cpt_2_3
     *
     * @param cpt23 the value for HF_hy_28.cpt_2_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setCpt23(Float cpt23) {
        this.cpt23 = cpt23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.cpt_3_3
     *
     * @return the value of HF_hy_28.cpt_3_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getCpt33() {
        return cpt33;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.cpt_3_3
     *
     * @param cpt33 the value for HF_hy_28.cpt_3_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setCpt33(Float cpt33) {
        this.cpt33 = cpt33;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.cpt_4_3
     *
     * @return the value of HF_hy_28.cpt_4_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getCpt43() {
        return cpt43;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.cpt_4_3
     *
     * @param cpt43 the value for HF_hy_28.cpt_4_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setCpt43(Float cpt43) {
        this.cpt43 = cpt43;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.ncircuits_3
     *
     * @return the value of HF_hy_28.ncircuits_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getNcircuits3() {
        return ncircuits3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.ncircuits_3
     *
     * @param ncircuits3 the value for HF_hy_28.ncircuits_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setNcircuits3(Float ncircuits3) {
        this.ncircuits3 = ncircuits3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.ncompressors_3
     *
     * @return the value of HF_hy_28.ncompressors_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getNcompressors3() {
        return ncompressors3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.ncompressors_3
     *
     * @param ncompressors3 the value for HF_hy_28.ncompressors_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setNcompressors3(Float ncompressors3) {
        this.ncompressors3 = ncompressors3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.typeofcp_3
     *
     * @return the value of HF_hy_28.typeofcp_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getTypeofcp3() {
        return typeofcp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.typeofcp_3
     *
     * @param typeofcp3 the value for HF_hy_28.typeofcp_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setTypeofcp3(Float typeofcp3) {
        this.typeofcp3 = typeofcp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.unit_status_3
     *
     * @return the value of HF_hy_28.unit_status_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getUnitStatus3() {
        return unitStatus3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.unit_status_3
     *
     * @param unitStatus3 the value for HF_hy_28.unit_status_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setUnitStatus3(Float unitStatus3) {
        this.unitStatus3 = unitStatus3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.unit_t_status_3
     *
     * @return the value of HF_hy_28.unit_t_status_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getUnitTStatus3() {
        return unitTStatus3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.unit_t_status_3
     *
     * @param unitTStatus3 the value for HF_hy_28.unit_t_status_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setUnitTStatus3(Float unitTStatus3) {
        this.unitTStatus3 = unitTStatus3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.operatingmode_3
     *
     * @return the value of HF_hy_28.operatingmode_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getOperatingmode3() {
        return operatingmode3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.operatingmode_3
     *
     * @param operatingmode3 the value for HF_hy_28.operatingmode_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setOperatingmode3(Float operatingmode3) {
        this.operatingmode3 = operatingmode3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.cpofforon_1_3
     *
     * @return the value of HF_hy_28.cpofforon_1_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getCpofforon13() {
        return cpofforon13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.cpofforon_1_3
     *
     * @param cpofforon13 the value for HF_hy_28.cpofforon_1_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setCpofforon13(Float cpofforon13) {
        this.cpofforon13 = cpofforon13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.cpchiler_1_3
     *
     * @return the value of HF_hy_28.cpchiler_1_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getCpchiler13() {
        return cpchiler13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.cpchiler_1_3
     *
     * @param cpchiler13 the value for HF_hy_28.cpchiler_1_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setCpchiler13(Float cpchiler13) {
        this.cpchiler13 = cpchiler13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.cpheatpump_1_3
     *
     * @return the value of HF_hy_28.cpheatpump_1_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getCpheatpump13() {
        return cpheatpump13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.cpheatpump_1_3
     *
     * @param cpheatpump13 the value for HF_hy_28.cpheatpump_1_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setCpheatpump13(Float cpheatpump13) {
        this.cpheatpump13 = cpheatpump13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.cpofforon_2_3
     *
     * @return the value of HF_hy_28.cpofforon_2_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getCpofforon23() {
        return cpofforon23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.cpofforon_2_3
     *
     * @param cpofforon23 the value for HF_hy_28.cpofforon_2_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setCpofforon23(Float cpofforon23) {
        this.cpofforon23 = cpofforon23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.cpchiler_2_3
     *
     * @return the value of HF_hy_28.cpchiler_2_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getCpchiler23() {
        return cpchiler23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.cpchiler_2_3
     *
     * @param cpchiler23 the value for HF_hy_28.cpchiler_2_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setCpchiler23(Float cpchiler23) {
        this.cpchiler23 = cpchiler23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.cpheatpump_2_3
     *
     * @return the value of HF_hy_28.cpheatpump_2_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getCpheatpump23() {
        return cpheatpump23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.cpheatpump_2_3
     *
     * @param cpheatpump23 the value for HF_hy_28.cpheatpump_2_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setCpheatpump23(Float cpheatpump23) {
        this.cpheatpump23 = cpheatpump23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.cpofforon_3_3
     *
     * @return the value of HF_hy_28.cpofforon_3_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getCpofforon33() {
        return cpofforon33;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.cpofforon_3_3
     *
     * @param cpofforon33 the value for HF_hy_28.cpofforon_3_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setCpofforon33(Float cpofforon33) {
        this.cpofforon33 = cpofforon33;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.cpchiler_3_3
     *
     * @return the value of HF_hy_28.cpchiler_3_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getCpchiler33() {
        return cpchiler33;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.cpchiler_3_3
     *
     * @param cpchiler33 the value for HF_hy_28.cpchiler_3_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setCpchiler33(Float cpchiler33) {
        this.cpchiler33 = cpchiler33;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.cpheatpump_3_3
     *
     * @return the value of HF_hy_28.cpheatpump_3_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getCpheatpump33() {
        return cpheatpump33;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.cpheatpump_3_3
     *
     * @param cpheatpump33 the value for HF_hy_28.cpheatpump_3_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setCpheatpump33(Float cpheatpump33) {
        this.cpheatpump33 = cpheatpump33;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.cpofforon_4_3
     *
     * @return the value of HF_hy_28.cpofforon_4_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getCpofforon43() {
        return cpofforon43;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.cpofforon_4_3
     *
     * @param cpofforon43 the value for HF_hy_28.cpofforon_4_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setCpofforon43(Float cpofforon43) {
        this.cpofforon43 = cpofforon43;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.cpchiler_4_3
     *
     * @return the value of HF_hy_28.cpchiler_4_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getCpchiler43() {
        return cpchiler43;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.cpchiler_4_3
     *
     * @param cpchiler43 the value for HF_hy_28.cpchiler_4_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setCpchiler43(Float cpchiler43) {
        this.cpchiler43 = cpchiler43;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.cpheatpump_4_3
     *
     * @return the value of HF_hy_28.cpheatpump_4_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getCpheatpump43() {
        return cpheatpump43;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.cpheatpump_4_3
     *
     * @param cpheatpump43 the value for HF_hy_28.cpheatpump_4_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setCpheatpump43(Float cpheatpump43) {
        this.cpheatpump43 = cpheatpump43;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.ahcp_3
     *
     * @return the value of HF_hy_28.ahcp_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getAhcp3() {
        return ahcp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.ahcp_3
     *
     * @param ahcp3 the value for HF_hy_28.ahcp_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setAhcp3(Float ahcp3) {
        this.ahcp3 = ahcp3;
    }


    public Float getCtSp3() {
		return ctSp3;
	}

	public void setCtSp3(Float ctSp3) {
		this.ctSp3 = ctSp3;
	}

	public Float getHtSp3() {
		return htSp3;
	}

	public void setHtSp3(Float htSp3) {
		this.htSp3 = htSp3;
	}

	public Float getCtD3() {
		return ctD3;
	}

	public void setCtD3(Float ctD3) {
		this.ctD3 = ctD3;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.apofct_3
     *
     * @return the value of HF_hy_28.apofct_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getApofct3() {
        return apofct3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.apofct_3
     *
     * @param apofct3 the value for HF_hy_28.apofct_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setApofct3(Float apofct3) {
        this.apofct3 = apofct3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.apofct_h_3
     *
     * @return the value of HF_hy_28.apofct_h_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getApofctH3() {
        return apofctH3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.apofct_h_3
     *
     * @param apofctH3 the value for HF_hy_28.apofct_h_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setApofctH3(Float apofctH3) {
        this.apofctH3 = apofctH3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.hptd_3
     *
     * @return the value of HF_hy_28.hptd_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getHptd3() {
        return hptd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.hptd_3
     *
     * @param hptd3 the value for HF_hy_28.hptd_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setHptd3(Float hptd3) {
        this.hptd3 = hptd3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.apofhpt_3
     *
     * @return the value of HF_hy_28.apofhpt_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getApofhpt3() {
        return apofhpt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.apofhpt_3
     *
     * @param apofhpt3 the value for HF_hy_28.apofhpt_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setApofhpt3(Float apofhpt3) {
        this.apofhpt3 = apofhpt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.apofhpt_h_3
     *
     * @return the value of HF_hy_28.apofhpt_h_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getApofhptH3() {
        return apofhptH3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.apofhpt_h_3
     *
     * @param apofhptH3 the value for HF_hy_28.apofhpt_h_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setApofhptH3(Float apofhptH3) {
        this.apofhptH3 = apofhptH3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.tlincm_3
     *
     * @return the value of HF_hy_28.tlincm_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getTlincm3() {
        return tlincm3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.tlincm_3
     *
     * @param tlincm3 the value for HF_hy_28.tlincm_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setTlincm3(Float tlincm3) {
        this.tlincm3 = tlincm3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_28.tlinhpm_3
     *
     * @return the value of HF_hy_28.tlinhpm_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public Float getTlinhpm3() {
        return tlinhpm3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_28.tlinhpm_3
     *
     * @param tlinhpm3 the value for HF_hy_28.tlinhpm_3
     *
     * @mbg.generated Wed Oct 11 14:24:12 CST 2017
     */
    public void setTlinhpm3(Float tlinhpm3) {
        this.tlinhpm3 = tlinhpm3;
    }

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getTimeNew() {
		return timeNew;
	}

	public void setTimeNew(String timeNew) {
		this.timeNew = timeNew;
	}
    
    
    
}