package com.firstCapacity.business.HeFeiPower.entity;

import java.io.Serializable;
import java.util.Date;

public class HF_hy_08 implements Serializable{
	
	private static final long serialVersionUID = 1L;
	
	
    private String startTime;
    
    private String endTime;
    
    private String timeNew;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.Time
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_fd
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11Fd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_t3
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11T3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_h1
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11H1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_t4
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11T4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_h2
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11H2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_co2
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11Co2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_d1
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11D1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_d3
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11D3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_ffs5
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11Ffs5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_ffs6
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11Ffs6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_pfk
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11Pfk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_pfg
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11Pfg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_hfs5
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11Hfs5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_hfs6
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11Hfs6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_sf5
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11Sf5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_sf6
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11Sf6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_js2
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11Js2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_s1
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11S1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_s2
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11S2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_s3
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11S3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_s4
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11S4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_p1
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11P1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_p2
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11P2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_p3
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11P3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_p4
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11P4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_pg
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11Pg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_fmax
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11Fmax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_fmin
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11Fmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_jssx
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11Jssx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_jsxx
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11Jsxx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_xfmax
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11Xfmax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_xfmin
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11Xfmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_hfmax
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11Hfmax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_hfmin
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11Hfmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_sfsd
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11Sfsd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_p
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11P;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_i
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11I;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_d
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11D;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_co2_sd
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11Co2Sd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_1p
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B111p;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_1i
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B111i;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_1d
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B111d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_hfts
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11Hfts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_2p
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B112p;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_2i
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B112i;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1_2d
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B112d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1jsqdt
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11jsqdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1jstzt
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11jstzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1zlzr_am
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11zlzrAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1ys_am
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11ysAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1ddf_am
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11ddfAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1sjam
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11sjam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1djam
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11djam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1xff_am
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11xffAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1hff_am
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11hffAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_08.t4_b1_1jst_s
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    private Float t4B11jstS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.Time
     *
     * @return the value of HF_hy_08.Time
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.Time
     *
     * @param time the value for HF_hy_08.Time
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_fd
     *
     * @return the value of HF_hy_08.t4_b1_1_fd
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11Fd() {
        return t4B11Fd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_fd
     *
     * @param t4B11Fd the value for HF_hy_08.t4_b1_1_fd
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11Fd(Float t4B11Fd) {
        this.t4B11Fd = t4B11Fd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_t3
     *
     * @return the value of HF_hy_08.t4_b1_1_t3
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11T3() {
        return t4B11T3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_t3
     *
     * @param t4B11T3 the value for HF_hy_08.t4_b1_1_t3
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11T3(Float t4B11T3) {
        this.t4B11T3 = t4B11T3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_h1
     *
     * @return the value of HF_hy_08.t4_b1_1_h1
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11H1() {
        return t4B11H1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_h1
     *
     * @param t4B11H1 the value for HF_hy_08.t4_b1_1_h1
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11H1(Float t4B11H1) {
        this.t4B11H1 = t4B11H1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_t4
     *
     * @return the value of HF_hy_08.t4_b1_1_t4
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11T4() {
        return t4B11T4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_t4
     *
     * @param t4B11T4 the value for HF_hy_08.t4_b1_1_t4
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11T4(Float t4B11T4) {
        this.t4B11T4 = t4B11T4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_h2
     *
     * @return the value of HF_hy_08.t4_b1_1_h2
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11H2() {
        return t4B11H2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_h2
     *
     * @param t4B11H2 the value for HF_hy_08.t4_b1_1_h2
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11H2(Float t4B11H2) {
        this.t4B11H2 = t4B11H2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_co2
     *
     * @return the value of HF_hy_08.t4_b1_1_co2
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11Co2() {
        return t4B11Co2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_co2
     *
     * @param t4B11Co2 the value for HF_hy_08.t4_b1_1_co2
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11Co2(Float t4B11Co2) {
        this.t4B11Co2 = t4B11Co2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_d1
     *
     * @return the value of HF_hy_08.t4_b1_1_d1
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11D1() {
        return t4B11D1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_d1
     *
     * @param t4B11D1 the value for HF_hy_08.t4_b1_1_d1
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11D1(Float t4B11D1) {
        this.t4B11D1 = t4B11D1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_d3
     *
     * @return the value of HF_hy_08.t4_b1_1_d3
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11D3() {
        return t4B11D3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_d3
     *
     * @param t4B11D3 the value for HF_hy_08.t4_b1_1_d3
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11D3(Float t4B11D3) {
        this.t4B11D3 = t4B11D3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_ffs5
     *
     * @return the value of HF_hy_08.t4_b1_1_ffs5
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11Ffs5() {
        return t4B11Ffs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_ffs5
     *
     * @param t4B11Ffs5 the value for HF_hy_08.t4_b1_1_ffs5
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11Ffs5(Float t4B11Ffs5) {
        this.t4B11Ffs5 = t4B11Ffs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_ffs6
     *
     * @return the value of HF_hy_08.t4_b1_1_ffs6
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11Ffs6() {
        return t4B11Ffs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_ffs6
     *
     * @param t4B11Ffs6 the value for HF_hy_08.t4_b1_1_ffs6
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11Ffs6(Float t4B11Ffs6) {
        this.t4B11Ffs6 = t4B11Ffs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_pfk
     *
     * @return the value of HF_hy_08.t4_b1_1_pfk
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11Pfk() {
        return t4B11Pfk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_pfk
     *
     * @param t4B11Pfk the value for HF_hy_08.t4_b1_1_pfk
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11Pfk(Float t4B11Pfk) {
        this.t4B11Pfk = t4B11Pfk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_pfg
     *
     * @return the value of HF_hy_08.t4_b1_1_pfg
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11Pfg() {
        return t4B11Pfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_pfg
     *
     * @param t4B11Pfg the value for HF_hy_08.t4_b1_1_pfg
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11Pfg(Float t4B11Pfg) {
        this.t4B11Pfg = t4B11Pfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_hfs5
     *
     * @return the value of HF_hy_08.t4_b1_1_hfs5
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11Hfs5() {
        return t4B11Hfs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_hfs5
     *
     * @param t4B11Hfs5 the value for HF_hy_08.t4_b1_1_hfs5
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11Hfs5(Float t4B11Hfs5) {
        this.t4B11Hfs5 = t4B11Hfs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_hfs6
     *
     * @return the value of HF_hy_08.t4_b1_1_hfs6
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11Hfs6() {
        return t4B11Hfs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_hfs6
     *
     * @param t4B11Hfs6 the value for HF_hy_08.t4_b1_1_hfs6
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11Hfs6(Float t4B11Hfs6) {
        this.t4B11Hfs6 = t4B11Hfs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_sf5
     *
     * @return the value of HF_hy_08.t4_b1_1_sf5
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11Sf5() {
        return t4B11Sf5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_sf5
     *
     * @param t4B11Sf5 the value for HF_hy_08.t4_b1_1_sf5
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11Sf5(Float t4B11Sf5) {
        this.t4B11Sf5 = t4B11Sf5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_sf6
     *
     * @return the value of HF_hy_08.t4_b1_1_sf6
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11Sf6() {
        return t4B11Sf6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_sf6
     *
     * @param t4B11Sf6 the value for HF_hy_08.t4_b1_1_sf6
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11Sf6(Float t4B11Sf6) {
        this.t4B11Sf6 = t4B11Sf6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_js2
     *
     * @return the value of HF_hy_08.t4_b1_1_js2
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11Js2() {
        return t4B11Js2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_js2
     *
     * @param t4B11Js2 the value for HF_hy_08.t4_b1_1_js2
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11Js2(Float t4B11Js2) {
        this.t4B11Js2 = t4B11Js2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_s1
     *
     * @return the value of HF_hy_08.t4_b1_1_s1
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11S1() {
        return t4B11S1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_s1
     *
     * @param t4B11S1 the value for HF_hy_08.t4_b1_1_s1
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11S1(Float t4B11S1) {
        this.t4B11S1 = t4B11S1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_s2
     *
     * @return the value of HF_hy_08.t4_b1_1_s2
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11S2() {
        return t4B11S2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_s2
     *
     * @param t4B11S2 the value for HF_hy_08.t4_b1_1_s2
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11S2(Float t4B11S2) {
        this.t4B11S2 = t4B11S2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_s3
     *
     * @return the value of HF_hy_08.t4_b1_1_s3
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11S3() {
        return t4B11S3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_s3
     *
     * @param t4B11S3 the value for HF_hy_08.t4_b1_1_s3
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11S3(Float t4B11S3) {
        this.t4B11S3 = t4B11S3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_s4
     *
     * @return the value of HF_hy_08.t4_b1_1_s4
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11S4() {
        return t4B11S4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_s4
     *
     * @param t4B11S4 the value for HF_hy_08.t4_b1_1_s4
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11S4(Float t4B11S4) {
        this.t4B11S4 = t4B11S4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_p1
     *
     * @return the value of HF_hy_08.t4_b1_1_p1
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11P1() {
        return t4B11P1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_p1
     *
     * @param t4B11P1 the value for HF_hy_08.t4_b1_1_p1
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11P1(Float t4B11P1) {
        this.t4B11P1 = t4B11P1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_p2
     *
     * @return the value of HF_hy_08.t4_b1_1_p2
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11P2() {
        return t4B11P2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_p2
     *
     * @param t4B11P2 the value for HF_hy_08.t4_b1_1_p2
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11P2(Float t4B11P2) {
        this.t4B11P2 = t4B11P2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_p3
     *
     * @return the value of HF_hy_08.t4_b1_1_p3
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11P3() {
        return t4B11P3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_p3
     *
     * @param t4B11P3 the value for HF_hy_08.t4_b1_1_p3
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11P3(Float t4B11P3) {
        this.t4B11P3 = t4B11P3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_p4
     *
     * @return the value of HF_hy_08.t4_b1_1_p4
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11P4() {
        return t4B11P4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_p4
     *
     * @param t4B11P4 the value for HF_hy_08.t4_b1_1_p4
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11P4(Float t4B11P4) {
        this.t4B11P4 = t4B11P4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_pg
     *
     * @return the value of HF_hy_08.t4_b1_1_pg
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11Pg() {
        return t4B11Pg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_pg
     *
     * @param t4B11Pg the value for HF_hy_08.t4_b1_1_pg
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11Pg(Float t4B11Pg) {
        this.t4B11Pg = t4B11Pg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_fmax
     *
     * @return the value of HF_hy_08.t4_b1_1_fmax
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11Fmax() {
        return t4B11Fmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_fmax
     *
     * @param t4B11Fmax the value for HF_hy_08.t4_b1_1_fmax
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11Fmax(Float t4B11Fmax) {
        this.t4B11Fmax = t4B11Fmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_fmin
     *
     * @return the value of HF_hy_08.t4_b1_1_fmin
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11Fmin() {
        return t4B11Fmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_fmin
     *
     * @param t4B11Fmin the value for HF_hy_08.t4_b1_1_fmin
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11Fmin(Float t4B11Fmin) {
        this.t4B11Fmin = t4B11Fmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_jssx
     *
     * @return the value of HF_hy_08.t4_b1_1_jssx
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11Jssx() {
        return t4B11Jssx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_jssx
     *
     * @param t4B11Jssx the value for HF_hy_08.t4_b1_1_jssx
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11Jssx(Float t4B11Jssx) {
        this.t4B11Jssx = t4B11Jssx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_jsxx
     *
     * @return the value of HF_hy_08.t4_b1_1_jsxx
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11Jsxx() {
        return t4B11Jsxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_jsxx
     *
     * @param t4B11Jsxx the value for HF_hy_08.t4_b1_1_jsxx
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11Jsxx(Float t4B11Jsxx) {
        this.t4B11Jsxx = t4B11Jsxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_xfmax
     *
     * @return the value of HF_hy_08.t4_b1_1_xfmax
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11Xfmax() {
        return t4B11Xfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_xfmax
     *
     * @param t4B11Xfmax the value for HF_hy_08.t4_b1_1_xfmax
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11Xfmax(Float t4B11Xfmax) {
        this.t4B11Xfmax = t4B11Xfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_xfmin
     *
     * @return the value of HF_hy_08.t4_b1_1_xfmin
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11Xfmin() {
        return t4B11Xfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_xfmin
     *
     * @param t4B11Xfmin the value for HF_hy_08.t4_b1_1_xfmin
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11Xfmin(Float t4B11Xfmin) {
        this.t4B11Xfmin = t4B11Xfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_hfmax
     *
     * @return the value of HF_hy_08.t4_b1_1_hfmax
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11Hfmax() {
        return t4B11Hfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_hfmax
     *
     * @param t4B11Hfmax the value for HF_hy_08.t4_b1_1_hfmax
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11Hfmax(Float t4B11Hfmax) {
        this.t4B11Hfmax = t4B11Hfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_hfmin
     *
     * @return the value of HF_hy_08.t4_b1_1_hfmin
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11Hfmin() {
        return t4B11Hfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_hfmin
     *
     * @param t4B11Hfmin the value for HF_hy_08.t4_b1_1_hfmin
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11Hfmin(Float t4B11Hfmin) {
        this.t4B11Hfmin = t4B11Hfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_sfsd
     *
     * @return the value of HF_hy_08.t4_b1_1_sfsd
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11Sfsd() {
        return t4B11Sfsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_sfsd
     *
     * @param t4B11Sfsd the value for HF_hy_08.t4_b1_1_sfsd
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11Sfsd(Float t4B11Sfsd) {
        this.t4B11Sfsd = t4B11Sfsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_p
     *
     * @return the value of HF_hy_08.t4_b1_1_p
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11P() {
        return t4B11P;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_p
     *
     * @param t4B11P the value for HF_hy_08.t4_b1_1_p
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11P(Float t4B11P) {
        this.t4B11P = t4B11P;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_i
     *
     * @return the value of HF_hy_08.t4_b1_1_i
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11I() {
        return t4B11I;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_i
     *
     * @param t4B11I the value for HF_hy_08.t4_b1_1_i
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11I(Float t4B11I) {
        this.t4B11I = t4B11I;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_d
     *
     * @return the value of HF_hy_08.t4_b1_1_d
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11D() {
        return t4B11D;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_d
     *
     * @param t4B11D the value for HF_hy_08.t4_b1_1_d
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11D(Float t4B11D) {
        this.t4B11D = t4B11D;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_co2_sd
     *
     * @return the value of HF_hy_08.t4_b1_1_co2_sd
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11Co2Sd() {
        return t4B11Co2Sd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_co2_sd
     *
     * @param t4B11Co2Sd the value for HF_hy_08.t4_b1_1_co2_sd
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11Co2Sd(Float t4B11Co2Sd) {
        this.t4B11Co2Sd = t4B11Co2Sd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_1p
     *
     * @return the value of HF_hy_08.t4_b1_1_1p
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B111p() {
        return t4B111p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_1p
     *
     * @param t4B111p the value for HF_hy_08.t4_b1_1_1p
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B111p(Float t4B111p) {
        this.t4B111p = t4B111p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_1i
     *
     * @return the value of HF_hy_08.t4_b1_1_1i
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B111i() {
        return t4B111i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_1i
     *
     * @param t4B111i the value for HF_hy_08.t4_b1_1_1i
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B111i(Float t4B111i) {
        this.t4B111i = t4B111i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_1d
     *
     * @return the value of HF_hy_08.t4_b1_1_1d
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B111d() {
        return t4B111d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_1d
     *
     * @param t4B111d the value for HF_hy_08.t4_b1_1_1d
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B111d(Float t4B111d) {
        this.t4B111d = t4B111d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_hfts
     *
     * @return the value of HF_hy_08.t4_b1_1_hfts
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11Hfts() {
        return t4B11Hfts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_hfts
     *
     * @param t4B11Hfts the value for HF_hy_08.t4_b1_1_hfts
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11Hfts(Float t4B11Hfts) {
        this.t4B11Hfts = t4B11Hfts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_2p
     *
     * @return the value of HF_hy_08.t4_b1_1_2p
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B112p() {
        return t4B112p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_2p
     *
     * @param t4B112p the value for HF_hy_08.t4_b1_1_2p
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B112p(Float t4B112p) {
        this.t4B112p = t4B112p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_2i
     *
     * @return the value of HF_hy_08.t4_b1_1_2i
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B112i() {
        return t4B112i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_2i
     *
     * @param t4B112i the value for HF_hy_08.t4_b1_1_2i
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B112i(Float t4B112i) {
        this.t4B112i = t4B112i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1_2d
     *
     * @return the value of HF_hy_08.t4_b1_1_2d
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B112d() {
        return t4B112d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1_2d
     *
     * @param t4B112d the value for HF_hy_08.t4_b1_1_2d
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B112d(Float t4B112d) {
        this.t4B112d = t4B112d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1jsqdt
     *
     * @return the value of HF_hy_08.t4_b1_1jsqdt
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11jsqdt() {
        return t4B11jsqdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1jsqdt
     *
     * @param t4B11jsqdt the value for HF_hy_08.t4_b1_1jsqdt
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11jsqdt(Float t4B11jsqdt) {
        this.t4B11jsqdt = t4B11jsqdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1jstzt
     *
     * @return the value of HF_hy_08.t4_b1_1jstzt
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11jstzt() {
        return t4B11jstzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1jstzt
     *
     * @param t4B11jstzt the value for HF_hy_08.t4_b1_1jstzt
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11jstzt(Float t4B11jstzt) {
        this.t4B11jstzt = t4B11jstzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1zlzr_am
     *
     * @return the value of HF_hy_08.t4_b1_1zlzr_am
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11zlzrAm() {
        return t4B11zlzrAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1zlzr_am
     *
     * @param t4B11zlzrAm the value for HF_hy_08.t4_b1_1zlzr_am
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11zlzrAm(Float t4B11zlzrAm) {
        this.t4B11zlzrAm = t4B11zlzrAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1ys_am
     *
     * @return the value of HF_hy_08.t4_b1_1ys_am
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11ysAm() {
        return t4B11ysAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1ys_am
     *
     * @param t4B11ysAm the value for HF_hy_08.t4_b1_1ys_am
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11ysAm(Float t4B11ysAm) {
        this.t4B11ysAm = t4B11ysAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1ddf_am
     *
     * @return the value of HF_hy_08.t4_b1_1ddf_am
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11ddfAm() {
        return t4B11ddfAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1ddf_am
     *
     * @param t4B11ddfAm the value for HF_hy_08.t4_b1_1ddf_am
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11ddfAm(Float t4B11ddfAm) {
        this.t4B11ddfAm = t4B11ddfAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1sjam
     *
     * @return the value of HF_hy_08.t4_b1_1sjam
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11sjam() {
        return t4B11sjam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1sjam
     *
     * @param t4B11sjam the value for HF_hy_08.t4_b1_1sjam
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11sjam(Float t4B11sjam) {
        this.t4B11sjam = t4B11sjam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1djam
     *
     * @return the value of HF_hy_08.t4_b1_1djam
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11djam() {
        return t4B11djam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1djam
     *
     * @param t4B11djam the value for HF_hy_08.t4_b1_1djam
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11djam(Float t4B11djam) {
        this.t4B11djam = t4B11djam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1xff_am
     *
     * @return the value of HF_hy_08.t4_b1_1xff_am
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11xffAm() {
        return t4B11xffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1xff_am
     *
     * @param t4B11xffAm the value for HF_hy_08.t4_b1_1xff_am
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11xffAm(Float t4B11xffAm) {
        this.t4B11xffAm = t4B11xffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1hff_am
     *
     * @return the value of HF_hy_08.t4_b1_1hff_am
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11hffAm() {
        return t4B11hffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1hff_am
     *
     * @param t4B11hffAm the value for HF_hy_08.t4_b1_1hff_am
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11hffAm(Float t4B11hffAm) {
        this.t4B11hffAm = t4B11hffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_08.t4_b1_1jst_s
     *
     * @return the value of HF_hy_08.t4_b1_1jst_s
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public Float getT4B11jstS() {
        return t4B11jstS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_08.t4_b1_1jst_s
     *
     * @param t4B11jstS the value for HF_hy_08.t4_b1_1jst_s
     *
     * @mbg.generated Wed Oct 11 14:17:05 CST 2017
     */
    public void setT4B11jstS(Float t4B11jstS) {
        this.t4B11jstS = t4B11jstS;
    }

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getTimeNew() {
		return timeNew;
	}

	public void setTimeNew(String timeNew) {
		this.timeNew = timeNew;
	}
    
    
}