package com.firstCapacity.business.HeFeiPower.entity;

import java.io.Serializable;
import java.util.Date;

public class HF_hy_06 implements Serializable{
	
	private static final long serialVersionUID = 1L;
	
	
    private String startTime;
    
    private String endTime;
    
    private String timeNew;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.Time
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_fd
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11Fd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_t3
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11T3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_h1
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11H1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_t4
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11T4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_h2
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11H2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_co2
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11Co2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_d1
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11D1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_d3
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11D3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_ffs5
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11Ffs5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_ffs6
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11Ffs6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_pfk
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11Pfk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_pfg
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11Pfg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_hfs5
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11Hfs5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_hfs6
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11Hfs6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_sf5
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11Sf5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_sf6
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11Sf6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_js2
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11Js2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_s1
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11S1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_s2
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11S2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_s3
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11S3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_s4
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11S4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_p1
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11P1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_p2
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11P2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_p3
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11P3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_p4
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11P4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_pg
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11Pg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_fmax
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11Fmax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_fmin
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11Fmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_jssx
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11Jssx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_jsxx
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11Jsxx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_xfmax
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11Xfmax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_xfmin
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11Xfmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_hfmax
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11Hfmax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_hfmin
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11Hfmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_sfsd
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11Sfsd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_p
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11P;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_i
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11I;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_d
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11D;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_co2_sd
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11Co2Sd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_1p
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B111p;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_1i
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B111i;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_1d
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B111d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_hfts
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11Hfts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_2p
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B112p;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_2i
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B112i;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1_2d
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B112d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1jsqdt
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11jsqdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1jstzt
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11jstzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1zlzr_am
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11zlzrAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1ys_am
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11ysAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1ddf_am
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11ddfAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1sjam
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11sjam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1djam
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11djam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1xff_am
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11xffAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1hff_am
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11hffAm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_06.t3_b1_1jst_s
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    private Float t3B11jstS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.Time
     *
     * @return the value of HF_hy_06.Time
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.Time
     *
     * @param time the value for HF_hy_06.Time
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_fd
     *
     * @return the value of HF_hy_06.t3_b1_1_fd
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11Fd() {
        return t3B11Fd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_fd
     *
     * @param t3B11Fd the value for HF_hy_06.t3_b1_1_fd
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11Fd(Float t3B11Fd) {
        this.t3B11Fd = t3B11Fd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_t3
     *
     * @return the value of HF_hy_06.t3_b1_1_t3
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11T3() {
        return t3B11T3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_t3
     *
     * @param t3B11T3 the value for HF_hy_06.t3_b1_1_t3
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11T3(Float t3B11T3) {
        this.t3B11T3 = t3B11T3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_h1
     *
     * @return the value of HF_hy_06.t3_b1_1_h1
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11H1() {
        return t3B11H1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_h1
     *
     * @param t3B11H1 the value for HF_hy_06.t3_b1_1_h1
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11H1(Float t3B11H1) {
        this.t3B11H1 = t3B11H1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_t4
     *
     * @return the value of HF_hy_06.t3_b1_1_t4
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11T4() {
        return t3B11T4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_t4
     *
     * @param t3B11T4 the value for HF_hy_06.t3_b1_1_t4
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11T4(Float t3B11T4) {
        this.t3B11T4 = t3B11T4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_h2
     *
     * @return the value of HF_hy_06.t3_b1_1_h2
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11H2() {
        return t3B11H2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_h2
     *
     * @param t3B11H2 the value for HF_hy_06.t3_b1_1_h2
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11H2(Float t3B11H2) {
        this.t3B11H2 = t3B11H2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_co2
     *
     * @return the value of HF_hy_06.t3_b1_1_co2
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11Co2() {
        return t3B11Co2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_co2
     *
     * @param t3B11Co2 the value for HF_hy_06.t3_b1_1_co2
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11Co2(Float t3B11Co2) {
        this.t3B11Co2 = t3B11Co2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_d1
     *
     * @return the value of HF_hy_06.t3_b1_1_d1
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11D1() {
        return t3B11D1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_d1
     *
     * @param t3B11D1 the value for HF_hy_06.t3_b1_1_d1
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11D1(Float t3B11D1) {
        this.t3B11D1 = t3B11D1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_d3
     *
     * @return the value of HF_hy_06.t3_b1_1_d3
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11D3() {
        return t3B11D3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_d3
     *
     * @param t3B11D3 the value for HF_hy_06.t3_b1_1_d3
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11D3(Float t3B11D3) {
        this.t3B11D3 = t3B11D3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_ffs5
     *
     * @return the value of HF_hy_06.t3_b1_1_ffs5
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11Ffs5() {
        return t3B11Ffs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_ffs5
     *
     * @param t3B11Ffs5 the value for HF_hy_06.t3_b1_1_ffs5
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11Ffs5(Float t3B11Ffs5) {
        this.t3B11Ffs5 = t3B11Ffs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_ffs6
     *
     * @return the value of HF_hy_06.t3_b1_1_ffs6
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11Ffs6() {
        return t3B11Ffs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_ffs6
     *
     * @param t3B11Ffs6 the value for HF_hy_06.t3_b1_1_ffs6
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11Ffs6(Float t3B11Ffs6) {
        this.t3B11Ffs6 = t3B11Ffs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_pfk
     *
     * @return the value of HF_hy_06.t3_b1_1_pfk
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11Pfk() {
        return t3B11Pfk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_pfk
     *
     * @param t3B11Pfk the value for HF_hy_06.t3_b1_1_pfk
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11Pfk(Float t3B11Pfk) {
        this.t3B11Pfk = t3B11Pfk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_pfg
     *
     * @return the value of HF_hy_06.t3_b1_1_pfg
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11Pfg() {
        return t3B11Pfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_pfg
     *
     * @param t3B11Pfg the value for HF_hy_06.t3_b1_1_pfg
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11Pfg(Float t3B11Pfg) {
        this.t3B11Pfg = t3B11Pfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_hfs5
     *
     * @return the value of HF_hy_06.t3_b1_1_hfs5
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11Hfs5() {
        return t3B11Hfs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_hfs5
     *
     * @param t3B11Hfs5 the value for HF_hy_06.t3_b1_1_hfs5
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11Hfs5(Float t3B11Hfs5) {
        this.t3B11Hfs5 = t3B11Hfs5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_hfs6
     *
     * @return the value of HF_hy_06.t3_b1_1_hfs6
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11Hfs6() {
        return t3B11Hfs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_hfs6
     *
     * @param t3B11Hfs6 the value for HF_hy_06.t3_b1_1_hfs6
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11Hfs6(Float t3B11Hfs6) {
        this.t3B11Hfs6 = t3B11Hfs6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_sf5
     *
     * @return the value of HF_hy_06.t3_b1_1_sf5
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11Sf5() {
        return t3B11Sf5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_sf5
     *
     * @param t3B11Sf5 the value for HF_hy_06.t3_b1_1_sf5
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11Sf5(Float t3B11Sf5) {
        this.t3B11Sf5 = t3B11Sf5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_sf6
     *
     * @return the value of HF_hy_06.t3_b1_1_sf6
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11Sf6() {
        return t3B11Sf6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_sf6
     *
     * @param t3B11Sf6 the value for HF_hy_06.t3_b1_1_sf6
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11Sf6(Float t3B11Sf6) {
        this.t3B11Sf6 = t3B11Sf6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_js2
     *
     * @return the value of HF_hy_06.t3_b1_1_js2
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11Js2() {
        return t3B11Js2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_js2
     *
     * @param t3B11Js2 the value for HF_hy_06.t3_b1_1_js2
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11Js2(Float t3B11Js2) {
        this.t3B11Js2 = t3B11Js2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_s1
     *
     * @return the value of HF_hy_06.t3_b1_1_s1
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11S1() {
        return t3B11S1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_s1
     *
     * @param t3B11S1 the value for HF_hy_06.t3_b1_1_s1
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11S1(Float t3B11S1) {
        this.t3B11S1 = t3B11S1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_s2
     *
     * @return the value of HF_hy_06.t3_b1_1_s2
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11S2() {
        return t3B11S2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_s2
     *
     * @param t3B11S2 the value for HF_hy_06.t3_b1_1_s2
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11S2(Float t3B11S2) {
        this.t3B11S2 = t3B11S2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_s3
     *
     * @return the value of HF_hy_06.t3_b1_1_s3
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11S3() {
        return t3B11S3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_s3
     *
     * @param t3B11S3 the value for HF_hy_06.t3_b1_1_s3
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11S3(Float t3B11S3) {
        this.t3B11S3 = t3B11S3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_s4
     *
     * @return the value of HF_hy_06.t3_b1_1_s4
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11S4() {
        return t3B11S4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_s4
     *
     * @param t3B11S4 the value for HF_hy_06.t3_b1_1_s4
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11S4(Float t3B11S4) {
        this.t3B11S4 = t3B11S4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_p1
     *
     * @return the value of HF_hy_06.t3_b1_1_p1
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11P1() {
        return t3B11P1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_p1
     *
     * @param t3B11P1 the value for HF_hy_06.t3_b1_1_p1
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11P1(Float t3B11P1) {
        this.t3B11P1 = t3B11P1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_p2
     *
     * @return the value of HF_hy_06.t3_b1_1_p2
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11P2() {
        return t3B11P2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_p2
     *
     * @param t3B11P2 the value for HF_hy_06.t3_b1_1_p2
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11P2(Float t3B11P2) {
        this.t3B11P2 = t3B11P2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_p3
     *
     * @return the value of HF_hy_06.t3_b1_1_p3
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11P3() {
        return t3B11P3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_p3
     *
     * @param t3B11P3 the value for HF_hy_06.t3_b1_1_p3
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11P3(Float t3B11P3) {
        this.t3B11P3 = t3B11P3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_p4
     *
     * @return the value of HF_hy_06.t3_b1_1_p4
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11P4() {
        return t3B11P4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_p4
     *
     * @param t3B11P4 the value for HF_hy_06.t3_b1_1_p4
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11P4(Float t3B11P4) {
        this.t3B11P4 = t3B11P4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_pg
     *
     * @return the value of HF_hy_06.t3_b1_1_pg
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11Pg() {
        return t3B11Pg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_pg
     *
     * @param t3B11Pg the value for HF_hy_06.t3_b1_1_pg
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11Pg(Float t3B11Pg) {
        this.t3B11Pg = t3B11Pg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_fmax
     *
     * @return the value of HF_hy_06.t3_b1_1_fmax
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11Fmax() {
        return t3B11Fmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_fmax
     *
     * @param t3B11Fmax the value for HF_hy_06.t3_b1_1_fmax
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11Fmax(Float t3B11Fmax) {
        this.t3B11Fmax = t3B11Fmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_fmin
     *
     * @return the value of HF_hy_06.t3_b1_1_fmin
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11Fmin() {
        return t3B11Fmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_fmin
     *
     * @param t3B11Fmin the value for HF_hy_06.t3_b1_1_fmin
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11Fmin(Float t3B11Fmin) {
        this.t3B11Fmin = t3B11Fmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_jssx
     *
     * @return the value of HF_hy_06.t3_b1_1_jssx
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11Jssx() {
        return t3B11Jssx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_jssx
     *
     * @param t3B11Jssx the value for HF_hy_06.t3_b1_1_jssx
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11Jssx(Float t3B11Jssx) {
        this.t3B11Jssx = t3B11Jssx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_jsxx
     *
     * @return the value of HF_hy_06.t3_b1_1_jsxx
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11Jsxx() {
        return t3B11Jsxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_jsxx
     *
     * @param t3B11Jsxx the value for HF_hy_06.t3_b1_1_jsxx
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11Jsxx(Float t3B11Jsxx) {
        this.t3B11Jsxx = t3B11Jsxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_xfmax
     *
     * @return the value of HF_hy_06.t3_b1_1_xfmax
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11Xfmax() {
        return t3B11Xfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_xfmax
     *
     * @param t3B11Xfmax the value for HF_hy_06.t3_b1_1_xfmax
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11Xfmax(Float t3B11Xfmax) {
        this.t3B11Xfmax = t3B11Xfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_xfmin
     *
     * @return the value of HF_hy_06.t3_b1_1_xfmin
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11Xfmin() {
        return t3B11Xfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_xfmin
     *
     * @param t3B11Xfmin the value for HF_hy_06.t3_b1_1_xfmin
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11Xfmin(Float t3B11Xfmin) {
        this.t3B11Xfmin = t3B11Xfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_hfmax
     *
     * @return the value of HF_hy_06.t3_b1_1_hfmax
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11Hfmax() {
        return t3B11Hfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_hfmax
     *
     * @param t3B11Hfmax the value for HF_hy_06.t3_b1_1_hfmax
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11Hfmax(Float t3B11Hfmax) {
        this.t3B11Hfmax = t3B11Hfmax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_hfmin
     *
     * @return the value of HF_hy_06.t3_b1_1_hfmin
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11Hfmin() {
        return t3B11Hfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_hfmin
     *
     * @param t3B11Hfmin the value for HF_hy_06.t3_b1_1_hfmin
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11Hfmin(Float t3B11Hfmin) {
        this.t3B11Hfmin = t3B11Hfmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_sfsd
     *
     * @return the value of HF_hy_06.t3_b1_1_sfsd
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11Sfsd() {
        return t3B11Sfsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_sfsd
     *
     * @param t3B11Sfsd the value for HF_hy_06.t3_b1_1_sfsd
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11Sfsd(Float t3B11Sfsd) {
        this.t3B11Sfsd = t3B11Sfsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_p
     *
     * @return the value of HF_hy_06.t3_b1_1_p
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11P() {
        return t3B11P;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_p
     *
     * @param t3B11P the value for HF_hy_06.t3_b1_1_p
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11P(Float t3B11P) {
        this.t3B11P = t3B11P;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_i
     *
     * @return the value of HF_hy_06.t3_b1_1_i
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11I() {
        return t3B11I;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_i
     *
     * @param t3B11I the value for HF_hy_06.t3_b1_1_i
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11I(Float t3B11I) {
        this.t3B11I = t3B11I;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_d
     *
     * @return the value of HF_hy_06.t3_b1_1_d
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11D() {
        return t3B11D;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_d
     *
     * @param t3B11D the value for HF_hy_06.t3_b1_1_d
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11D(Float t3B11D) {
        this.t3B11D = t3B11D;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_co2_sd
     *
     * @return the value of HF_hy_06.t3_b1_1_co2_sd
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11Co2Sd() {
        return t3B11Co2Sd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_co2_sd
     *
     * @param t3B11Co2Sd the value for HF_hy_06.t3_b1_1_co2_sd
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11Co2Sd(Float t3B11Co2Sd) {
        this.t3B11Co2Sd = t3B11Co2Sd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_1p
     *
     * @return the value of HF_hy_06.t3_b1_1_1p
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B111p() {
        return t3B111p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_1p
     *
     * @param t3B111p the value for HF_hy_06.t3_b1_1_1p
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B111p(Float t3B111p) {
        this.t3B111p = t3B111p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_1i
     *
     * @return the value of HF_hy_06.t3_b1_1_1i
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B111i() {
        return t3B111i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_1i
     *
     * @param t3B111i the value for HF_hy_06.t3_b1_1_1i
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B111i(Float t3B111i) {
        this.t3B111i = t3B111i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_1d
     *
     * @return the value of HF_hy_06.t3_b1_1_1d
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B111d() {
        return t3B111d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_1d
     *
     * @param t3B111d the value for HF_hy_06.t3_b1_1_1d
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B111d(Float t3B111d) {
        this.t3B111d = t3B111d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_hfts
     *
     * @return the value of HF_hy_06.t3_b1_1_hfts
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11Hfts() {
        return t3B11Hfts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_hfts
     *
     * @param t3B11Hfts the value for HF_hy_06.t3_b1_1_hfts
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11Hfts(Float t3B11Hfts) {
        this.t3B11Hfts = t3B11Hfts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_2p
     *
     * @return the value of HF_hy_06.t3_b1_1_2p
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B112p() {
        return t3B112p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_2p
     *
     * @param t3B112p the value for HF_hy_06.t3_b1_1_2p
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B112p(Float t3B112p) {
        this.t3B112p = t3B112p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_2i
     *
     * @return the value of HF_hy_06.t3_b1_1_2i
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B112i() {
        return t3B112i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_2i
     *
     * @param t3B112i the value for HF_hy_06.t3_b1_1_2i
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B112i(Float t3B112i) {
        this.t3B112i = t3B112i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1_2d
     *
     * @return the value of HF_hy_06.t3_b1_1_2d
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B112d() {
        return t3B112d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1_2d
     *
     * @param t3B112d the value for HF_hy_06.t3_b1_1_2d
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B112d(Float t3B112d) {
        this.t3B112d = t3B112d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1jsqdt
     *
     * @return the value of HF_hy_06.t3_b1_1jsqdt
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11jsqdt() {
        return t3B11jsqdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1jsqdt
     *
     * @param t3B11jsqdt the value for HF_hy_06.t3_b1_1jsqdt
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11jsqdt(Float t3B11jsqdt) {
        this.t3B11jsqdt = t3B11jsqdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1jstzt
     *
     * @return the value of HF_hy_06.t3_b1_1jstzt
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11jstzt() {
        return t3B11jstzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1jstzt
     *
     * @param t3B11jstzt the value for HF_hy_06.t3_b1_1jstzt
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11jstzt(Float t3B11jstzt) {
        this.t3B11jstzt = t3B11jstzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1zlzr_am
     *
     * @return the value of HF_hy_06.t3_b1_1zlzr_am
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11zlzrAm() {
        return t3B11zlzrAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1zlzr_am
     *
     * @param t3B11zlzrAm the value for HF_hy_06.t3_b1_1zlzr_am
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11zlzrAm(Float t3B11zlzrAm) {
        this.t3B11zlzrAm = t3B11zlzrAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1ys_am
     *
     * @return the value of HF_hy_06.t3_b1_1ys_am
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11ysAm() {
        return t3B11ysAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1ys_am
     *
     * @param t3B11ysAm the value for HF_hy_06.t3_b1_1ys_am
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11ysAm(Float t3B11ysAm) {
        this.t3B11ysAm = t3B11ysAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1ddf_am
     *
     * @return the value of HF_hy_06.t3_b1_1ddf_am
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11ddfAm() {
        return t3B11ddfAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1ddf_am
     *
     * @param t3B11ddfAm the value for HF_hy_06.t3_b1_1ddf_am
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11ddfAm(Float t3B11ddfAm) {
        this.t3B11ddfAm = t3B11ddfAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1sjam
     *
     * @return the value of HF_hy_06.t3_b1_1sjam
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11sjam() {
        return t3B11sjam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1sjam
     *
     * @param t3B11sjam the value for HF_hy_06.t3_b1_1sjam
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11sjam(Float t3B11sjam) {
        this.t3B11sjam = t3B11sjam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1djam
     *
     * @return the value of HF_hy_06.t3_b1_1djam
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11djam() {
        return t3B11djam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1djam
     *
     * @param t3B11djam the value for HF_hy_06.t3_b1_1djam
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11djam(Float t3B11djam) {
        this.t3B11djam = t3B11djam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1xff_am
     *
     * @return the value of HF_hy_06.t3_b1_1xff_am
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11xffAm() {
        return t3B11xffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1xff_am
     *
     * @param t3B11xffAm the value for HF_hy_06.t3_b1_1xff_am
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11xffAm(Float t3B11xffAm) {
        this.t3B11xffAm = t3B11xffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1hff_am
     *
     * @return the value of HF_hy_06.t3_b1_1hff_am
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11hffAm() {
        return t3B11hffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1hff_am
     *
     * @param t3B11hffAm the value for HF_hy_06.t3_b1_1hff_am
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11hffAm(Float t3B11hffAm) {
        this.t3B11hffAm = t3B11hffAm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_06.t3_b1_1jst_s
     *
     * @return the value of HF_hy_06.t3_b1_1jst_s
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public Float getT3B11jstS() {
        return t3B11jstS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_06.t3_b1_1jst_s
     *
     * @param t3B11jstS the value for HF_hy_06.t3_b1_1jst_s
     *
     * @mbg.generated Wed Oct 11 14:16:32 CST 2017
     */
    public void setT3B11jstS(Float t3B11jstS) {
        this.t3B11jstS = t3B11jstS;
    }

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getTimeNew() {
		return timeNew;
	}

	public void setTimeNew(String timeNew) {
		this.timeNew = timeNew;
	}
    
    
    
}