package com.firstCapacity.business.HeFeiPower.entity;

import java.io.Serializable;
import java.util.Date;

public class HF_hy_29 implements Serializable{
	
	private static final long serialVersionUID = 1L;
	
	
    private String startTime;
    
    private String endTime;
    
    private String timeNew;
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.Time
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.c_t_sp_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float ctSp4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.h_t_sp_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float htSp4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.cool_lwt_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float coolLwt4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.cool_ewt_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float coolEwt4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.cond_lwt_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float condLwt4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.cond_ewt_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float condEwt4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.high_p_t1_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float highPT14;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.high_p_t2_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float highPT24;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.high_p_t3_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float highPT34;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.high_p_t4_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float highPT44;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.low_p_t1_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float lowPT14;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.low_p_t2_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float lowPT24;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.low_p_t3_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float lowPT34;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.low_p_t4_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float lowPT44;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.cpt_1_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float cpt14;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.cpt_2_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float cpt24;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.cpt_3_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float cpt34;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.cpt_4_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float cpt44;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.ncircuits_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float ncircuits4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.ncompressors_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float ncompressors4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.typeofcp_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float typeofcp4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.unit_status_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float unitStatus4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.unit_t_status_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float unitTStatus4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.operatingmode_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float operatingmode4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.cpofforon_1_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float cpofforon14;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.cpchiler_1_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float cpchiler14;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.cpheatpump_1_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float cpheatpump14;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.cpofforon_2_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float cpofforon24;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.cpchiler_2_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float cpchiler24;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.cpheatpump_2_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float cpheatpump24;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.cpofforon_3_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float cpofforon34;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.cpchiler_3_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float cpchiler34;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.cpheatpump_3_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float cpheatpump34;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.cpofforon_4_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float cpofforon44;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.cpchiler_4_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float cpchiler44;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.cpheatpump_4_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float cpheatpump44;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.ahcp_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float ahcp4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.c_t_d_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float ctD4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.apofct_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float apofct4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.apofct_h_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float apofctH4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.hptd_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float hptd4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.apofhpt_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float apofhpt4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.apofhpt_h_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float apofhptH4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.tlincm_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float tlincm4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_29.tlinhpm_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    private Float tlinhpm4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.Time
     *
     * @return the value of HF_hy_29.Time
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.Time
     *
     * @param time the value for HF_hy_29.Time
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }


    public Float getCtSp4() {
		return ctSp4;
	}

	public void setCtSp4(Float ctSp4) {
		this.ctSp4 = ctSp4;
	}

	public Float getHtSp4() {
		return htSp4;
	}

	public void setHtSp4(Float htSp4) {
		this.htSp4 = htSp4;
	}

	public Float getCtD4() {
		return ctD4;
	}

	public void setCtD4(Float ctD4) {
		this.ctD4 = ctD4;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.cool_lwt_4
     *
     * @return the value of HF_hy_29.cool_lwt_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getCoolLwt4() {
        return coolLwt4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.cool_lwt_4
     *
     * @param coolLwt4 the value for HF_hy_29.cool_lwt_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setCoolLwt4(Float coolLwt4) {
        this.coolLwt4 = coolLwt4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.cool_ewt_4
     *
     * @return the value of HF_hy_29.cool_ewt_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getCoolEwt4() {
        return coolEwt4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.cool_ewt_4
     *
     * @param coolEwt4 the value for HF_hy_29.cool_ewt_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setCoolEwt4(Float coolEwt4) {
        this.coolEwt4 = coolEwt4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.cond_lwt_4
     *
     * @return the value of HF_hy_29.cond_lwt_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getCondLwt4() {
        return condLwt4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.cond_lwt_4
     *
     * @param condLwt4 the value for HF_hy_29.cond_lwt_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setCondLwt4(Float condLwt4) {
        this.condLwt4 = condLwt4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.cond_ewt_4
     *
     * @return the value of HF_hy_29.cond_ewt_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getCondEwt4() {
        return condEwt4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.cond_ewt_4
     *
     * @param condEwt4 the value for HF_hy_29.cond_ewt_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setCondEwt4(Float condEwt4) {
        this.condEwt4 = condEwt4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.high_p_t1_4
     *
     * @return the value of HF_hy_29.high_p_t1_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getHighPT14() {
        return highPT14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.high_p_t1_4
     *
     * @param highPT14 the value for HF_hy_29.high_p_t1_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setHighPT14(Float highPT14) {
        this.highPT14 = highPT14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.high_p_t2_4
     *
     * @return the value of HF_hy_29.high_p_t2_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getHighPT24() {
        return highPT24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.high_p_t2_4
     *
     * @param highPT24 the value for HF_hy_29.high_p_t2_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setHighPT24(Float highPT24) {
        this.highPT24 = highPT24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.high_p_t3_4
     *
     * @return the value of HF_hy_29.high_p_t3_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getHighPT34() {
        return highPT34;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.high_p_t3_4
     *
     * @param highPT34 the value for HF_hy_29.high_p_t3_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setHighPT34(Float highPT34) {
        this.highPT34 = highPT34;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.high_p_t4_4
     *
     * @return the value of HF_hy_29.high_p_t4_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getHighPT44() {
        return highPT44;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.high_p_t4_4
     *
     * @param highPT44 the value for HF_hy_29.high_p_t4_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setHighPT44(Float highPT44) {
        this.highPT44 = highPT44;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.low_p_t1_4
     *
     * @return the value of HF_hy_29.low_p_t1_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getLowPT14() {
        return lowPT14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.low_p_t1_4
     *
     * @param lowPT14 the value for HF_hy_29.low_p_t1_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setLowPT14(Float lowPT14) {
        this.lowPT14 = lowPT14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.low_p_t2_4
     *
     * @return the value of HF_hy_29.low_p_t2_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getLowPT24() {
        return lowPT24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.low_p_t2_4
     *
     * @param lowPT24 the value for HF_hy_29.low_p_t2_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setLowPT24(Float lowPT24) {
        this.lowPT24 = lowPT24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.low_p_t3_4
     *
     * @return the value of HF_hy_29.low_p_t3_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getLowPT34() {
        return lowPT34;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.low_p_t3_4
     *
     * @param lowPT34 the value for HF_hy_29.low_p_t3_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setLowPT34(Float lowPT34) {
        this.lowPT34 = lowPT34;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.low_p_t4_4
     *
     * @return the value of HF_hy_29.low_p_t4_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getLowPT44() {
        return lowPT44;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.low_p_t4_4
     *
     * @param lowPT44 the value for HF_hy_29.low_p_t4_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setLowPT44(Float lowPT44) {
        this.lowPT44 = lowPT44;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.cpt_1_4
     *
     * @return the value of HF_hy_29.cpt_1_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getCpt14() {
        return cpt14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.cpt_1_4
     *
     * @param cpt14 the value for HF_hy_29.cpt_1_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setCpt14(Float cpt14) {
        this.cpt14 = cpt14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.cpt_2_4
     *
     * @return the value of HF_hy_29.cpt_2_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getCpt24() {
        return cpt24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.cpt_2_4
     *
     * @param cpt24 the value for HF_hy_29.cpt_2_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setCpt24(Float cpt24) {
        this.cpt24 = cpt24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.cpt_3_4
     *
     * @return the value of HF_hy_29.cpt_3_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getCpt34() {
        return cpt34;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.cpt_3_4
     *
     * @param cpt34 the value for HF_hy_29.cpt_3_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setCpt34(Float cpt34) {
        this.cpt34 = cpt34;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.cpt_4_4
     *
     * @return the value of HF_hy_29.cpt_4_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getCpt44() {
        return cpt44;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.cpt_4_4
     *
     * @param cpt44 the value for HF_hy_29.cpt_4_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setCpt44(Float cpt44) {
        this.cpt44 = cpt44;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.ncircuits_4
     *
     * @return the value of HF_hy_29.ncircuits_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getNcircuits4() {
        return ncircuits4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.ncircuits_4
     *
     * @param ncircuits4 the value for HF_hy_29.ncircuits_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setNcircuits4(Float ncircuits4) {
        this.ncircuits4 = ncircuits4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.ncompressors_4
     *
     * @return the value of HF_hy_29.ncompressors_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getNcompressors4() {
        return ncompressors4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.ncompressors_4
     *
     * @param ncompressors4 the value for HF_hy_29.ncompressors_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setNcompressors4(Float ncompressors4) {
        this.ncompressors4 = ncompressors4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.typeofcp_4
     *
     * @return the value of HF_hy_29.typeofcp_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getTypeofcp4() {
        return typeofcp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.typeofcp_4
     *
     * @param typeofcp4 the value for HF_hy_29.typeofcp_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setTypeofcp4(Float typeofcp4) {
        this.typeofcp4 = typeofcp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.unit_status_4
     *
     * @return the value of HF_hy_29.unit_status_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getUnitStatus4() {
        return unitStatus4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.unit_status_4
     *
     * @param unitStatus4 the value for HF_hy_29.unit_status_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setUnitStatus4(Float unitStatus4) {
        this.unitStatus4 = unitStatus4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.unit_t_status_4
     *
     * @return the value of HF_hy_29.unit_t_status_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getUnitTStatus4() {
        return unitTStatus4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.unit_t_status_4
     *
     * @param unitTStatus4 the value for HF_hy_29.unit_t_status_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setUnitTStatus4(Float unitTStatus4) {
        this.unitTStatus4 = unitTStatus4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.operatingmode_4
     *
     * @return the value of HF_hy_29.operatingmode_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getOperatingmode4() {
        return operatingmode4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.operatingmode_4
     *
     * @param operatingmode4 the value for HF_hy_29.operatingmode_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setOperatingmode4(Float operatingmode4) {
        this.operatingmode4 = operatingmode4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.cpofforon_1_4
     *
     * @return the value of HF_hy_29.cpofforon_1_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getCpofforon14() {
        return cpofforon14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.cpofforon_1_4
     *
     * @param cpofforon14 the value for HF_hy_29.cpofforon_1_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setCpofforon14(Float cpofforon14) {
        this.cpofforon14 = cpofforon14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.cpchiler_1_4
     *
     * @return the value of HF_hy_29.cpchiler_1_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getCpchiler14() {
        return cpchiler14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.cpchiler_1_4
     *
     * @param cpchiler14 the value for HF_hy_29.cpchiler_1_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setCpchiler14(Float cpchiler14) {
        this.cpchiler14 = cpchiler14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.cpheatpump_1_4
     *
     * @return the value of HF_hy_29.cpheatpump_1_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getCpheatpump14() {
        return cpheatpump14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.cpheatpump_1_4
     *
     * @param cpheatpump14 the value for HF_hy_29.cpheatpump_1_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setCpheatpump14(Float cpheatpump14) {
        this.cpheatpump14 = cpheatpump14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.cpofforon_2_4
     *
     * @return the value of HF_hy_29.cpofforon_2_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getCpofforon24() {
        return cpofforon24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.cpofforon_2_4
     *
     * @param cpofforon24 the value for HF_hy_29.cpofforon_2_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setCpofforon24(Float cpofforon24) {
        this.cpofforon24 = cpofforon24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.cpchiler_2_4
     *
     * @return the value of HF_hy_29.cpchiler_2_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getCpchiler24() {
        return cpchiler24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.cpchiler_2_4
     *
     * @param cpchiler24 the value for HF_hy_29.cpchiler_2_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setCpchiler24(Float cpchiler24) {
        this.cpchiler24 = cpchiler24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.cpheatpump_2_4
     *
     * @return the value of HF_hy_29.cpheatpump_2_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getCpheatpump24() {
        return cpheatpump24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.cpheatpump_2_4
     *
     * @param cpheatpump24 the value for HF_hy_29.cpheatpump_2_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setCpheatpump24(Float cpheatpump24) {
        this.cpheatpump24 = cpheatpump24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.cpofforon_3_4
     *
     * @return the value of HF_hy_29.cpofforon_3_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getCpofforon34() {
        return cpofforon34;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.cpofforon_3_4
     *
     * @param cpofforon34 the value for HF_hy_29.cpofforon_3_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setCpofforon34(Float cpofforon34) {
        this.cpofforon34 = cpofforon34;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.cpchiler_3_4
     *
     * @return the value of HF_hy_29.cpchiler_3_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getCpchiler34() {
        return cpchiler34;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.cpchiler_3_4
     *
     * @param cpchiler34 the value for HF_hy_29.cpchiler_3_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setCpchiler34(Float cpchiler34) {
        this.cpchiler34 = cpchiler34;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.cpheatpump_3_4
     *
     * @return the value of HF_hy_29.cpheatpump_3_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getCpheatpump34() {
        return cpheatpump34;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.cpheatpump_3_4
     *
     * @param cpheatpump34 the value for HF_hy_29.cpheatpump_3_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setCpheatpump34(Float cpheatpump34) {
        this.cpheatpump34 = cpheatpump34;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.cpofforon_4_4
     *
     * @return the value of HF_hy_29.cpofforon_4_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getCpofforon44() {
        return cpofforon44;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.cpofforon_4_4
     *
     * @param cpofforon44 the value for HF_hy_29.cpofforon_4_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setCpofforon44(Float cpofforon44) {
        this.cpofforon44 = cpofforon44;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.cpchiler_4_4
     *
     * @return the value of HF_hy_29.cpchiler_4_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getCpchiler44() {
        return cpchiler44;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.cpchiler_4_4
     *
     * @param cpchiler44 the value for HF_hy_29.cpchiler_4_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setCpchiler44(Float cpchiler44) {
        this.cpchiler44 = cpchiler44;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.cpheatpump_4_4
     *
     * @return the value of HF_hy_29.cpheatpump_4_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getCpheatpump44() {
        return cpheatpump44;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.cpheatpump_4_4
     *
     * @param cpheatpump44 the value for HF_hy_29.cpheatpump_4_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setCpheatpump44(Float cpheatpump44) {
        this.cpheatpump44 = cpheatpump44;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.ahcp_4
     *
     * @return the value of HF_hy_29.ahcp_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getAhcp4() {
        return ahcp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.ahcp_4
     *
     * @param ahcp4 the value for HF_hy_29.ahcp_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setAhcp4(Float ahcp4) {
        this.ahcp4 = ahcp4;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.apofct_4
     *
     * @return the value of HF_hy_29.apofct_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getApofct4() {
        return apofct4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.apofct_4
     *
     * @param apofct4 the value for HF_hy_29.apofct_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setApofct4(Float apofct4) {
        this.apofct4 = apofct4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.apofct_h_4
     *
     * @return the value of HF_hy_29.apofct_h_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getApofctH4() {
        return apofctH4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.apofct_h_4
     *
     * @param apofctH4 the value for HF_hy_29.apofct_h_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setApofctH4(Float apofctH4) {
        this.apofctH4 = apofctH4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.hptd_4
     *
     * @return the value of HF_hy_29.hptd_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getHptd4() {
        return hptd4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.hptd_4
     *
     * @param hptd4 the value for HF_hy_29.hptd_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setHptd4(Float hptd4) {
        this.hptd4 = hptd4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.apofhpt_4
     *
     * @return the value of HF_hy_29.apofhpt_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getApofhpt4() {
        return apofhpt4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.apofhpt_4
     *
     * @param apofhpt4 the value for HF_hy_29.apofhpt_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setApofhpt4(Float apofhpt4) {
        this.apofhpt4 = apofhpt4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.apofhpt_h_4
     *
     * @return the value of HF_hy_29.apofhpt_h_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getApofhptH4() {
        return apofhptH4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.apofhpt_h_4
     *
     * @param apofhptH4 the value for HF_hy_29.apofhpt_h_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setApofhptH4(Float apofhptH4) {
        this.apofhptH4 = apofhptH4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.tlincm_4
     *
     * @return the value of HF_hy_29.tlincm_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getTlincm4() {
        return tlincm4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.tlincm_4
     *
     * @param tlincm4 the value for HF_hy_29.tlincm_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setTlincm4(Float tlincm4) {
        this.tlincm4 = tlincm4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_29.tlinhpm_4
     *
     * @return the value of HF_hy_29.tlinhpm_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public Float getTlinhpm4() {
        return tlinhpm4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_29.tlinhpm_4
     *
     * @param tlinhpm4 the value for HF_hy_29.tlinhpm_4
     *
     * @mbg.generated Wed Oct 11 14:24:24 CST 2017
     */
    public void setTlinhpm4(Float tlinhpm4) {
        this.tlinhpm4 = tlinhpm4;
    }

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getTimeNew() {
		return timeNew;
	}

	public void setTimeNew(String timeNew) {
		this.timeNew = timeNew;
	}
    
    
    
}