package com.firstCapacity.business.HeFeiPower.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * @author hexiangfeng
 *
 */
public class HF_hy_31 implements Serializable{
	
	private static final long serialVersionUID = 1L;
	

    private Date time;  //时间

    private Float l1FhDq;  //低区天棚负荷

    private Float l1FhXf;  //高区加新风负荷

    private Float cTSp1;  //低区1#热泵制冷温度设定

    private Float hTSp1; //低区1#热泵热泵温度设定

    private Float cTSp2;  //低区2#热泵制冷温度设定

    private Float hTSp2;  //低区2#热泵热泵温度设定

    private Float cTSp3;  //高区1#热泵制冷温度设定

    private Float hTSp3;  //高区1#热泵热泵温度设定

    private Float cTSp4;  //高区冷水机组制冷温度设定

    private Float cTSp5;  //高区海尔磁悬浮制冷温度设定

    private Float hTSp5;  //高区海尔磁悬浮热泵温度设定

    private Float cpofforon11;  //低区1#热泵一号压缩机开关

    private Float cpofforon21;  //低区1#热泵二号压缩机开关

    private Float cpofforon31;  //低区1#热泵三号压缩机开关
 
    private Float cpofforon41;  //低区1#热泵四号压缩机开关

    private Float cpofforon12;  //低区2#热泵一号压缩机开关

    private Float cpofforon22;  //低区2#热泵二号压缩机开关

    private Float cpofforon32;  //低区2#热泵三号压缩机开关

    private Float cpofforon42;  //低区2#热泵四号压缩机开关

    private Float cpofforon13;  //高区1#热泵一号压缩机开关

    private Float cpofforon23;  //高区1#热泵二号压缩机开关

    private Float cpofforon33;  //高区1#热泵三号压缩机开关

    private Float cpofforon43;  //高区1#热泵四号压缩机开关

    private Float cpofforon14;  //高区冷水机组一号压缩机开关

    private Float cpofforon24;  //高区冷水机组二号压缩机开关

    private Float cpofforon34;  //高区冷水机组三号压缩机开关

    private Float cpofforon44;  //高区冷水机组四号压缩机开关

    private Float jzqt5;  //高区海尔磁悬浮机组启停
    
  //虚拟字段
    private Float loadTotal;  //系统总负荷
    
    private String timeGo;  //格式化日期
    
    private String time1;  //传入时间1
    
    private String time2;  //传入时间2
    
    //设备调节记录返回实体
    private Float ctSp1d ;
    private Float ctSp2d ;
    private Float ctSp3d ;
    private Float ctSp4d ;
    private Float ctSp5d ;
    private Float thTSp1d ;
    private Float thTSp2d ;
    private Float thTSp3d ;
    private Float thTSp5d ;
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    

	public Float getCtSp1d() {
		return ctSp1d;
	}

	public void setCtSp1d(Float ctSp1d) {
		this.ctSp1d = ctSp1d;
	}

	public Float getCtSp2d() {
		return ctSp2d;
	}

	public void setCtSp2d(Float ctSp2d) {
		this.ctSp2d = ctSp2d;
	}

	public Float getCtSp3d() {
		return ctSp3d;
	}

	public void setCtSp3d(Float ctSp3d) {
		this.ctSp3d = ctSp3d;
	}

	public Float getCtSp4d() {
		return ctSp4d;
	}

	public void setCtSp4d(Float ctSp4d) {
		this.ctSp4d = ctSp4d;
	}

	public Float getCtSp5d() {
		return ctSp5d;
	}

	public void setCtSp5d(Float ctSp5d) {
		this.ctSp5d = ctSp5d;
	}

	public Float getThTSp1d() {
		return thTSp1d;
	}

	public void setThTSp1d(Float thTSp1d) {
		this.thTSp1d = thTSp1d;
	}

	public Float getThTSp2d() {
		return thTSp2d;
	}

	public void setThTSp2d(Float thTSp2d) {
		this.thTSp2d = thTSp2d;
	}

	public Float getThTSp3d() {
		return thTSp3d;
	}

	public void setThTSp3d(Float thTSp3d) {
		this.thTSp3d = thTSp3d;
	}

	public Float getThTSp5d() {
		return thTSp5d;
	}

	public void setThTSp5d(Float thTSp5d) {
		this.thTSp5d = thTSp5d;
	}

	public Float getLoadTotal() {
		return loadTotal;
	}

	public void setLoadTotal(Float loadTotal) {
		this.loadTotal = loadTotal;
	}

	public String getTimeGo() {
		return timeGo;
	}

	public void setTimeGo(String timeGo) {
		this.timeGo = timeGo;
	}

	public String getTime1() {
		return time1;
	}

	public void setTime1(String time1) {
		this.time1 = time1;
	}

	public String getTime2() {
		return time2;
	}

	public void setTime2(String time2) {
		this.time2 = time2;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_31.Time
     *
     * @return the value of HF_hy_31.Time
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_31.Time
     *
     * @param time the value for HF_hy_31.Time
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_31.l1_fh_dq
     *
     * @return the value of HF_hy_31.l1_fh_dq
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public Float getL1FhDq() {
        return l1FhDq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_31.l1_fh_dq
     *
     * @param l1FhDq the value for HF_hy_31.l1_fh_dq
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public void setL1FhDq(Float l1FhDq) {
        this.l1FhDq = l1FhDq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_31.l1_fh_xf
     *
     * @return the value of HF_hy_31.l1_fh_xf
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public Float getL1FhXf() {
        return l1FhXf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_31.l1_fh_xf
     *
     * @param l1FhXf the value for HF_hy_31.l1_fh_xf
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public void setL1FhXf(Float l1FhXf) {
        this.l1FhXf = l1FhXf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_31.c_t_sp_1
     *
     * @return the value of HF_hy_31.c_t_sp_1
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public Float getcTSp1() {
        return cTSp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_31.c_t_sp_1
     *
     * @param cTSp1 the value for HF_hy_31.c_t_sp_1
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public void setcTSp1(Float cTSp1) {
        this.cTSp1 = cTSp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_31.h_t_sp_1
     *
     * @return the value of HF_hy_31.h_t_sp_1
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public Float gethTSp1() {
        return hTSp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_31.h_t_sp_1
     *
     * @param hTSp1 the value for HF_hy_31.h_t_sp_1
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public void sethTSp1(Float hTSp1) {
        this.hTSp1 = hTSp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_31.c_t_sp_2
     *
     * @return the value of HF_hy_31.c_t_sp_2
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public Float getcTSp2() {
        return cTSp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_31.c_t_sp_2
     *
     * @param cTSp2 the value for HF_hy_31.c_t_sp_2
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public void setcTSp2(Float cTSp2) {
        this.cTSp2 = cTSp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_31.h_t_sp_2
     *
     * @return the value of HF_hy_31.h_t_sp_2
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public Float gethTSp2() {
        return hTSp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_31.h_t_sp_2
     *
     * @param hTSp2 the value for HF_hy_31.h_t_sp_2
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public void sethTSp2(Float hTSp2) {
        this.hTSp2 = hTSp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_31.c_t_sp_3
     *
     * @return the value of HF_hy_31.c_t_sp_3
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public Float getcTSp3() {
        return cTSp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_31.c_t_sp_3
     *
     * @param cTSp3 the value for HF_hy_31.c_t_sp_3
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public void setcTSp3(Float cTSp3) {
        this.cTSp3 = cTSp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_31.h_t_sp_3
     *
     * @return the value of HF_hy_31.h_t_sp_3
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public Float gethTSp3() {
        return hTSp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_31.h_t_sp_3
     *
     * @param hTSp3 the value for HF_hy_31.h_t_sp_3
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public void sethTSp3(Float hTSp3) {
        this.hTSp3 = hTSp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_31.c_t_sp_4
     *
     * @return the value of HF_hy_31.c_t_sp_4
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public Float getcTSp4() {
        return cTSp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_31.c_t_sp_4
     *
     * @param cTSp4 the value for HF_hy_31.c_t_sp_4
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public void setcTSp4(Float cTSp4) {
        this.cTSp4 = cTSp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_31.c_t_sp_5
     *
     * @return the value of HF_hy_31.c_t_sp_5
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public Float getcTSp5() {
        return cTSp5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_31.c_t_sp_5
     *
     * @param cTSp5 the value for HF_hy_31.c_t_sp_5
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public void setcTSp5(Float cTSp5) {
        this.cTSp5 = cTSp5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_31.h_t_sp_5
     *
     * @return the value of HF_hy_31.h_t_sp_5
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public Float gethTSp5() {
        return hTSp5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_31.h_t_sp_5
     *
     * @param hTSp5 the value for HF_hy_31.h_t_sp_5
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public void sethTSp5(Float hTSp5) {
        this.hTSp5 = hTSp5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_31.cpofforon_1_1
     *
     * @return the value of HF_hy_31.cpofforon_1_1
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public Float getCpofforon11() {
        return cpofforon11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_31.cpofforon_1_1
     *
     * @param cpofforon11 the value for HF_hy_31.cpofforon_1_1
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public void setCpofforon11(Float cpofforon11) {
        this.cpofforon11 = cpofforon11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_31.cpofforon_2_1
     *
     * @return the value of HF_hy_31.cpofforon_2_1
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public Float getCpofforon21() {
        return cpofforon21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_31.cpofforon_2_1
     *
     * @param cpofforon21 the value for HF_hy_31.cpofforon_2_1
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public void setCpofforon21(Float cpofforon21) {
        this.cpofforon21 = cpofforon21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_31.cpofforon_3_1
     *
     * @return the value of HF_hy_31.cpofforon_3_1
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public Float getCpofforon31() {
        return cpofforon31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_31.cpofforon_3_1
     *
     * @param cpofforon31 the value for HF_hy_31.cpofforon_3_1
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public void setCpofforon31(Float cpofforon31) {
        this.cpofforon31 = cpofforon31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_31.cpofforon_4_1
     *
     * @return the value of HF_hy_31.cpofforon_4_1
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public Float getCpofforon41() {
        return cpofforon41;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_31.cpofforon_4_1
     *
     * @param cpofforon41 the value for HF_hy_31.cpofforon_4_1
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public void setCpofforon41(Float cpofforon41) {
        this.cpofforon41 = cpofforon41;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_31.cpofforon_1_2
     *
     * @return the value of HF_hy_31.cpofforon_1_2
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public Float getCpofforon12() {
        return cpofforon12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_31.cpofforon_1_2
     *
     * @param cpofforon12 the value for HF_hy_31.cpofforon_1_2
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public void setCpofforon12(Float cpofforon12) {
        this.cpofforon12 = cpofforon12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_31.cpofforon_2_2
     *
     * @return the value of HF_hy_31.cpofforon_2_2
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public Float getCpofforon22() {
        return cpofforon22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_31.cpofforon_2_2
     *
     * @param cpofforon22 the value for HF_hy_31.cpofforon_2_2
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public void setCpofforon22(Float cpofforon22) {
        this.cpofforon22 = cpofforon22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_31.cpofforon_3_2
     *
     * @return the value of HF_hy_31.cpofforon_3_2
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public Float getCpofforon32() {
        return cpofforon32;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_31.cpofforon_3_2
     *
     * @param cpofforon32 the value for HF_hy_31.cpofforon_3_2
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public void setCpofforon32(Float cpofforon32) {
        this.cpofforon32 = cpofforon32;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_31.cpofforon_4_2
     *
     * @return the value of HF_hy_31.cpofforon_4_2
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public Float getCpofforon42() {
        return cpofforon42;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_31.cpofforon_4_2
     *
     * @param cpofforon42 the value for HF_hy_31.cpofforon_4_2
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public void setCpofforon42(Float cpofforon42) {
        this.cpofforon42 = cpofforon42;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_31.cpofforon_1_3
     *
     * @return the value of HF_hy_31.cpofforon_1_3
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public Float getCpofforon13() {
        return cpofforon13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_31.cpofforon_1_3
     *
     * @param cpofforon13 the value for HF_hy_31.cpofforon_1_3
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public void setCpofforon13(Float cpofforon13) {
        this.cpofforon13 = cpofforon13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_31.cpofforon_2_3
     *
     * @return the value of HF_hy_31.cpofforon_2_3
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public Float getCpofforon23() {
        return cpofforon23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_31.cpofforon_2_3
     *
     * @param cpofforon23 the value for HF_hy_31.cpofforon_2_3
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public void setCpofforon23(Float cpofforon23) {
        this.cpofforon23 = cpofforon23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_31.cpofforon_3_3
     *
     * @return the value of HF_hy_31.cpofforon_3_3
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public Float getCpofforon33() {
        return cpofforon33;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_31.cpofforon_3_3
     *
     * @param cpofforon33 the value for HF_hy_31.cpofforon_3_3
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public void setCpofforon33(Float cpofforon33) {
        this.cpofforon33 = cpofforon33;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_31.cpofforon_4_3
     *
     * @return the value of HF_hy_31.cpofforon_4_3
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public Float getCpofforon43() {
        return cpofforon43;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_31.cpofforon_4_3
     *
     * @param cpofforon43 the value for HF_hy_31.cpofforon_4_3
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public void setCpofforon43(Float cpofforon43) {
        this.cpofforon43 = cpofforon43;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_31.cpofforon_1_4
     *
     * @return the value of HF_hy_31.cpofforon_1_4
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public Float getCpofforon14() {
        return cpofforon14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_31.cpofforon_1_4
     *
     * @param cpofforon14 the value for HF_hy_31.cpofforon_1_4
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public void setCpofforon14(Float cpofforon14) {
        this.cpofforon14 = cpofforon14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_31.cpofforon_2_4
     *
     * @return the value of HF_hy_31.cpofforon_2_4
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public Float getCpofforon24() {
        return cpofforon24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_31.cpofforon_2_4
     *
     * @param cpofforon24 the value for HF_hy_31.cpofforon_2_4
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public void setCpofforon24(Float cpofforon24) {
        this.cpofforon24 = cpofforon24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_31.cpofforon_3_4
     *
     * @return the value of HF_hy_31.cpofforon_3_4
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public Float getCpofforon34() {
        return cpofforon34;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_31.cpofforon_3_4
     *
     * @param cpofforon34 the value for HF_hy_31.cpofforon_3_4
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public void setCpofforon34(Float cpofforon34) {
        this.cpofforon34 = cpofforon34;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_31.cpofforon_4_4
     *
     * @return the value of HF_hy_31.cpofforon_4_4
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public Float getCpofforon44() {
        return cpofforon44;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_31.cpofforon_4_4
     *
     * @param cpofforon44 the value for HF_hy_31.cpofforon_4_4
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public void setCpofforon44(Float cpofforon44) {
        this.cpofforon44 = cpofforon44;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_31.jzqt_5
     *
     * @return the value of HF_hy_31.jzqt_5
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public Float getJzqt5() {
        return jzqt5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_31.jzqt_5
     *
     * @param jzqt5 the value for HF_hy_31.jzqt_5
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    public void setJzqt5(Float jzqt5) {
        this.jzqt5 = jzqt5;
    }
}