package com.firstCapacity.business.powerLink.mapper;

import java.util.List;

import com.firstCapacity.business.powerLink.entity.PowerLink;
import com.firstCapacity.business.powerLink.entity.suoyouAll;
import com.firstCapacity.util.aop.DataSource;

public interface PowerLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hefei
     *
     * @mbg.generated Wed Nov 08 22:08:09 CST 2017
     */
    int deleteByPrimaryKey(Integer hefeiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hefei
     *
     * @mbg.generated Wed Nov 08 22:08:09 CST 2017
     */
    int insert(PowerLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hefei
     *
     * @mbg.generated Wed Nov 08 22:08:09 CST 2017
     */
    int insertSelective(PowerLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hefei
     *
     * @mbg.generated Wed Nov 08 22:08:09 CST 2017
     */
    PowerLink selectByPrimaryKey(Integer hefeiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hefei
     *
     * @mbg.generated Wed Nov 08 22:08:09 CST 2017
     */
    int updateByPrimaryKeySelective(PowerLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hefei
     *
     * @mbg.generated Wed Nov 08 22:08:09 CST 2017
     */
    int updateByPrimaryKey(PowerLink record);
    
    
    //根据项目id查询连接+模糊性查询
    @DataSource("A")
    public List<PowerLink> selectLinkByProjectId(PowerLink powerLink);
    
    @DataSource("B")
    public List<suoyouAll> test();
    
}