package com.firstCapacity.business.equipmentIedger.entity;

import java.io.Serializable;
import java.util.Date;

import org.springframework.web.multipart.MultipartFile;

public class EquipmentIedger implements Serializable {

	private static final long serialVersionUID = 1L;
	
    private String equipmentIedgerId;  //主键

    private String equipmentName;  //设备名称

    private String regionId;  //区域ID

    private String projectId;  //项目ID

    private String equipmentTypeId;  //设备类型ID

    private String installationAddress;  //安装地址

    private String manufacturer;  //生产厂家

    private String gomanufacturerAddress;  //生产厂家地址

    private String contactNumber;  //联系电话

    private String unitModel;  //机组型号

    private Integer loopNumber;  //回路数

    private String factoryNumber;  //出厂编号

    private String temperatureRestriction;  //温度限制℃

    private String power;  //功率kW

    private Double capacity;  //容量m3

    private Integer voltage;  //电压V

    private Double electricCurrent;   //电流A

    private Integer weight;  //重量kg

    private Integer lift;  //扬程m

    private Integer speed;  //转速r/min

    private Integer flow;  //流量m3/h

    private String remarks;  //备注

    private String ifEasyUse;  //是否使用

    private String ifIntact;  //是否完好

    private String usingState;  //设备使用状态

    private String intactState;  //设备完好状态

    private String installationUnit;  //安装单位

    private String installContacts;  //安装联系人

    private String contactInformation;  //联系方式

    private String warrantyTermination;  //保修终止日

    private String installTime;  //安装日期

    private String enableTime;  //启用日期

    private String handoverTimeType;  //交接时运行状态

    private String regionName;  //区域名称

    private String projectName;  //项目名称

    private String equipmentTypeName;  //设备类型
 
    private Date createTime;  //创建时间

    private Date updateTime;  //修改时间
    
    
    private MultipartFile upFiles;  //文件
    
    

    
    
    
    public MultipartFile getUpFiles() {
		return upFiles;
	}

	public void setUpFiles(MultipartFile upFiles) {
		this.upFiles = upFiles;
	}

	public String getEquipmentIedgerId() {
        return equipmentIedgerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.equipment_iedger_id
     *
     * @param equipmentIedgerId the value for equipment_iedger.equipment_iedger_id
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setEquipmentIedgerId(String equipmentIedgerId) {
        this.equipmentIedgerId = equipmentIedgerId == null ? null : equipmentIedgerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.equipment_name
     *
     * @return the value of equipment_iedger.equipment_name
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public String getEquipmentName() {
        return equipmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.equipment_name
     *
     * @param equipmentName the value for equipment_iedger.equipment_name
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setEquipmentName(String equipmentName) {
        this.equipmentName = equipmentName == null ? null : equipmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.region_id
     *
     * @return the value of equipment_iedger.region_id
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.region_id
     *
     * @param regionId the value for equipment_iedger.region_id
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId == null ? null : regionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.project_id
     *
     * @return the value of equipment_iedger.project_id
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.project_id
     *
     * @param projectId the value for equipment_iedger.project_id
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.equipment_type_id
     *
     * @return the value of equipment_iedger.equipment_type_id
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public String getEquipmentTypeId() {
        return equipmentTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.equipment_type_id
     *
     * @param equipmentTypeId the value for equipment_iedger.equipment_type_id
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setEquipmentTypeId(String equipmentTypeId) {
        this.equipmentTypeId = equipmentTypeId == null ? null : equipmentTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.installation_address
     *
     * @return the value of equipment_iedger.installation_address
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public String getInstallationAddress() {
        return installationAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.installation_address
     *
     * @param installationAddress the value for equipment_iedger.installation_address
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setInstallationAddress(String installationAddress) {
        this.installationAddress = installationAddress == null ? null : installationAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.manufacturer
     *
     * @return the value of equipment_iedger.manufacturer
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.manufacturer
     *
     * @param manufacturer the value for equipment_iedger.manufacturer
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer == null ? null : manufacturer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.manufacturer_address
     *
     * @return the value of equipment_iedger.manufacturer_address
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */

    public String getGomanufacturerAddress() {
		return gomanufacturerAddress;
	}

	public void setGomanufacturerAddress(String gomanufacturerAddress) {
		this.gomanufacturerAddress = gomanufacturerAddress;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.contact_number
     *
     * @return the value of equipment_iedger.contact_number
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public String getContactNumber() {
        return contactNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.contact_number
     *
     * @param contactNumber the value for equipment_iedger.contact_number
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber == null ? null : contactNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.unit_model
     *
     * @return the value of equipment_iedger.unit_model
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public String getUnitModel() {
        return unitModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.unit_model
     *
     * @param unitModel the value for equipment_iedger.unit_model
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setUnitModel(String unitModel) {
        this.unitModel = unitModel == null ? null : unitModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.loop_number
     *
     * @return the value of equipment_iedger.loop_number
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public Integer getLoopNumber() {
        return loopNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.loop_number
     *
     * @param loopNumber the value for equipment_iedger.loop_number
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setLoopNumber(Integer loopNumber) {
        this.loopNumber = loopNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.factory_number
     *
     * @return the value of equipment_iedger.factory_number
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public String getFactoryNumber() {
        return factoryNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.factory_number
     *
     * @param factoryNumber the value for equipment_iedger.factory_number
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setFactoryNumber(String factoryNumber) {
        this.factoryNumber = factoryNumber == null ? null : factoryNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.temperature_restriction
     *
     * @return the value of equipment_iedger.temperature_restriction
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public String getTemperatureRestriction() {
        return temperatureRestriction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.temperature_restriction
     *
     * @param temperatureRestriction the value for equipment_iedger.temperature_restriction
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setTemperatureRestriction(String temperatureRestriction) {
        this.temperatureRestriction = temperatureRestriction == null ? null : temperatureRestriction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.power
     *
     * @return the value of equipment_iedger.power
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public String getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.power
     *
     * @param power the value for equipment_iedger.power
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setPower(String power) {
        this.power = power == null ? null : power.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.capacity
     *
     * @return the value of equipment_iedger.capacity
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public Double getCapacity() {
        return capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.capacity
     *
     * @param capacity the value for equipment_iedger.capacity
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setCapacity(Double capacity) {
        this.capacity = capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.voltage
     *
     * @return the value of equipment_iedger.voltage
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public Integer getVoltage() {
        return voltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.voltage
     *
     * @param voltage the value for equipment_iedger.voltage
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setVoltage(Integer voltage) {
        this.voltage = voltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.electric_current
     *
     * @return the value of equipment_iedger.electric_current
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public Double getElectricCurrent() {
        return electricCurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.electric_current
     *
     * @param electricCurrent the value for equipment_iedger.electric_current
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setElectricCurrent(Double electricCurrent) {
        this.electricCurrent = electricCurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.weight
     *
     * @return the value of equipment_iedger.weight
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.weight
     *
     * @param weight the value for equipment_iedger.weight
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.lift
     *
     * @return the value of equipment_iedger.lift
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public Integer getLift() {
        return lift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.lift
     *
     * @param lift the value for equipment_iedger.lift
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setLift(Integer lift) {
        this.lift = lift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.speed
     *
     * @return the value of equipment_iedger.speed
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public Integer getSpeed() {
        return speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.speed
     *
     * @param speed the value for equipment_iedger.speed
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setSpeed(Integer speed) {
        this.speed = speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.flow
     *
     * @return the value of equipment_iedger.flow
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public Integer getFlow() {
        return flow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.flow
     *
     * @param flow the value for equipment_iedger.flow
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setFlow(Integer flow) {
        this.flow = flow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.remarks
     *
     * @return the value of equipment_iedger.remarks
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.remarks
     *
     * @param remarks the value for equipment_iedger.remarks
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.if_easy_use
     *
     * @return the value of equipment_iedger.if_easy_use
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public String getIfEasyUse() {
        return ifEasyUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.if_easy_use
     *
     * @param ifEasyUse the value for equipment_iedger.if_easy_use
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setIfEasyUse(String ifEasyUse) {
        this.ifEasyUse = ifEasyUse == null ? null : ifEasyUse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.if_intact
     *
     * @return the value of equipment_iedger.if_intact
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public String getIfIntact() {
        return ifIntact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.if_intact
     *
     * @param ifIntact the value for equipment_iedger.if_intact
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setIfIntact(String ifIntact) {
        this.ifIntact = ifIntact == null ? null : ifIntact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.using_state
     *
     * @return the value of equipment_iedger.using_state
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public String getUsingState() {
        return usingState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.using_state
     *
     * @param usingState the value for equipment_iedger.using_state
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setUsingState(String usingState) {
        this.usingState = usingState == null ? null : usingState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.intact_state
     *
     * @return the value of equipment_iedger.intact_state
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public String getIntactState() {
        return intactState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.intact_state
     *
     * @param intactState the value for equipment_iedger.intact_state
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setIntactState(String intactState) {
        this.intactState = intactState == null ? null : intactState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.installation_unit
     *
     * @return the value of equipment_iedger.installation_unit
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public String getInstallationUnit() {
        return installationUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.installation_unit
     *
     * @param installationUnit the value for equipment_iedger.installation_unit
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setInstallationUnit(String installationUnit) {
        this.installationUnit = installationUnit == null ? null : installationUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.install_contacts
     *
     * @return the value of equipment_iedger.install_contacts
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public String getInstallContacts() {
        return installContacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.install_contacts
     *
     * @param installContacts the value for equipment_iedger.install_contacts
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setInstallContacts(String installContacts) {
        this.installContacts = installContacts == null ? null : installContacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.contact_information
     *
     * @return the value of equipment_iedger.contact_information
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public String getContactInformation() {
        return contactInformation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.contact_information
     *
     * @param contactInformation the value for equipment_iedger.contact_information
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setContactInformation(String contactInformation) {
        this.contactInformation = contactInformation == null ? null : contactInformation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.warranty_termination
     *
     * @return the value of equipment_iedger.warranty_termination
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public String getWarrantyTermination() {
        return warrantyTermination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.warranty_termination
     *
     * @param warrantyTermination the value for equipment_iedger.warranty_termination
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setWarrantyTermination(String warrantyTermination) {
        this.warrantyTermination = warrantyTermination == null ? null : warrantyTermination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.install_time
     *
     * @return the value of equipment_iedger.install_time
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public String getInstallTime() {
        return installTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.install_time
     *
     * @param installTime the value for equipment_iedger.install_time
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setInstallTime(String installTime) {
        this.installTime = installTime == null ? null : installTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.enable_time
     *
     * @return the value of equipment_iedger.enable_time
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public String getEnableTime() {
        return enableTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.enable_time
     *
     * @param enableTime the value for equipment_iedger.enable_time
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setEnableTime(String enableTime) {
        this.enableTime = enableTime == null ? null : enableTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.handover_time_type
     *
     * @return the value of equipment_iedger.handover_time_type
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public String getHandoverTimeType() {
        return handoverTimeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.handover_time_type
     *
     * @param handoverTimeType the value for equipment_iedger.handover_time_type
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setHandoverTimeType(String handoverTimeType) {
        this.handoverTimeType = handoverTimeType == null ? null : handoverTimeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.region_name
     *
     * @return the value of equipment_iedger.region_name
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.region_name
     *
     * @param regionName the value for equipment_iedger.region_name
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName == null ? null : regionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.project_name
     *
     * @return the value of equipment_iedger.project_name
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.project_name
     *
     * @param projectName the value for equipment_iedger.project_name
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.equipment_type_name
     *
     * @return the value of equipment_iedger.equipment_type_name
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public String getEquipmentTypeName() {
        return equipmentTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.equipment_type_name
     *
     * @param equipmentTypeName the value for equipment_iedger.equipment_type_name
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setEquipmentTypeName(String equipmentTypeName) {
        this.equipmentTypeName = equipmentTypeName == null ? null : equipmentTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.create_time
     *
     * @return the value of equipment_iedger.create_time
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.create_time
     *
     * @param createTime the value for equipment_iedger.create_time
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_iedger.update_time
     *
     * @return the value of equipment_iedger.update_time
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_iedger.update_time
     *
     * @param updateTime the value for equipment_iedger.update_time
     *
     * @mbg.generated Mon Oct 23 14:08:36 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}