package com.firstCapacity.business.equipmentType.mapper;

import java.util.List;

import com.firstCapacity.business.equipmentType.entity.EquipmentType;

public interface EquipmentTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_type
     *
     * @mbg.generated Mon Oct 23 14:10:54 CST 2017
     */
    int deleteByPrimaryKey(String equipmentTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_type
     *
     * @mbg.generated Mon Oct 23 14:10:54 CST 2017
     */
    int insert(EquipmentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_type
     *
     * @mbg.generated Mon Oct 23 14:10:54 CST 2017
     */
    int insertSelective(EquipmentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_type
     *
     * @mbg.generated Mon Oct 23 14:10:54 CST 2017
     */
    EquipmentType selectByPrimaryKey(String equipmentTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_type
     *
     * @mbg.generated Mon Oct 23 14:10:54 CST 2017
     */
    int updateByPrimaryKeySelective(EquipmentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equipment_type
     *
     * @mbg.generated Mon Oct 23 14:10:54 CST 2017
     */
    int updateByPrimaryKey(EquipmentType record);
    
    
    //查询所有项目类型
    public List<EquipmentType> selectAll();
    
    //校验名称是否已存在
    public List<EquipmentType> chickName(String equipmentTypeName);
    
}