package com.firstCapacity.business.powerProject.entity;

public class HFHySQL {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_SQL.point
     *
     * @mbg.generated Mon Nov 20 14:25:39 CST 2017
     */
    private String point;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_SQL.point_name
     *
     * @mbg.generated Mon Nov 20 14:25:39 CST 2017
     */
    private String pointName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_SQL.table
     *
     * @mbg.generated Mon Nov 20 14:25:39 CST 2017
     */
    private String table;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HF_hy_SQL.table_name
     *
     * @mbg.generated Mon Nov 20 14:25:39 CST 2017
     */
    private String tableName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_SQL.point
     *
     * @return the value of HF_hy_SQL.point
     *
     * @mbg.generated Mon Nov 20 14:25:39 CST 2017
     */
    public String getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_SQL.point
     *
     * @param point the value for HF_hy_SQL.point
     *
     * @mbg.generated Mon Nov 20 14:25:39 CST 2017
     */
    public void setPoint(String point) {
        this.point = point == null ? null : point.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_SQL.point_name
     *
     * @return the value of HF_hy_SQL.point_name
     *
     * @mbg.generated Mon Nov 20 14:25:39 CST 2017
     */
    public String getPointName() {
        return pointName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_SQL.point_name
     *
     * @param pointName the value for HF_hy_SQL.point_name
     *
     * @mbg.generated Mon Nov 20 14:25:39 CST 2017
     */
    public void setPointName(String pointName) {
        this.pointName = pointName == null ? null : pointName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_SQL.table
     *
     * @return the value of HF_hy_SQL.table
     *
     * @mbg.generated Mon Nov 20 14:25:39 CST 2017
     */
    public String getTable() {
        return table;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_SQL.table
     *
     * @param table the value for HF_hy_SQL.table
     *
     * @mbg.generated Mon Nov 20 14:25:39 CST 2017
     */
    public void setTable(String table) {
        this.table = table == null ? null : table.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HF_hy_SQL.table_name
     *
     * @return the value of HF_hy_SQL.table_name
     *
     * @mbg.generated Mon Nov 20 14:25:39 CST 2017
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HF_hy_SQL.table_name
     *
     * @param tableName the value for HF_hy_SQL.table_name
     *
     * @mbg.generated Mon Nov 20 14:25:39 CST 2017
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }
}