package com.firstCapacity.business.powerProject.entity;

import java.io.Serializable;

public class power implements Serializable{
	
	private static final long serialVersionUID = 1L;

    private Integer id;

    private String projectId;

    private Float loadTotal;

    private Float loaddqtp;

    private Float loadgqxf;

    private Double areahvac;

    private Float loadavg;

    private String time;
    
    private String timeTwo;
    
    
    
    
    
    
    
    
    
    
    public String getTimeTwo() {
		return timeTwo;
	}

	public void setTimeTwo(String timeTwo) {
		this.timeTwo = timeTwo;
	}

	public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power.id
     *
     * @param id the value for power.id
     *
     * @mbg.generated Tue Nov 14 15:41:21 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power.project_id
     *
     * @return the value of power.project_id
     *
     * @mbg.generated Tue Nov 14 15:41:21 CST 2017
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power.project_id
     *
     * @param projectId the value for power.project_id
     *
     * @mbg.generated Tue Nov 14 15:41:21 CST 2017
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power.load_total
     *
     * @return the value of power.load_total
     *
     * @mbg.generated Tue Nov 14 15:41:21 CST 2017
     */
    public Float getLoadTotal() {
        return loadTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power.load_total
     *
     * @param loadTotal the value for power.load_total
     *
     * @mbg.generated Tue Nov 14 15:41:21 CST 2017
     */
    public void setLoadTotal(Float loadTotal) {
        this.loadTotal = loadTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power.loadDQTP
     *
     * @return the value of power.loadDQTP
     *
     * @mbg.generated Tue Nov 14 15:41:21 CST 2017
     */
    public Float getLoaddqtp() {
        return loaddqtp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power.loadDQTP
     *
     * @param loaddqtp the value for power.loadDQTP
     *
     * @mbg.generated Tue Nov 14 15:41:21 CST 2017
     */
    public void setLoaddqtp(Float loaddqtp) {
        this.loaddqtp = loaddqtp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power.loadGQXF
     *
     * @return the value of power.loadGQXF
     *
     * @mbg.generated Tue Nov 14 15:41:21 CST 2017
     */
    public Float getLoadgqxf() {
        return loadgqxf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power.loadGQXF
     *
     * @param loadgqxf the value for power.loadGQXF
     *
     * @mbg.generated Tue Nov 14 15:41:21 CST 2017
     */
    public void setLoadgqxf(Float loadgqxf) {
        this.loadgqxf = loadgqxf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power.areaHVAC
     *
     * @return the value of power.areaHVAC
     *
     * @mbg.generated Tue Nov 14 15:41:21 CST 2017
     */
    public Double getAreahvac() {
        return areahvac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power.areaHVAC
     *
     * @param areahvac the value for power.areaHVAC
     *
     * @mbg.generated Tue Nov 14 15:41:21 CST 2017
     */
    public void setAreahvac(Double areahvac) {
        this.areahvac = areahvac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power.loadAvg
     *
     * @return the value of power.loadAvg
     *
     * @mbg.generated Tue Nov 14 15:41:21 CST 2017
     */
    public Float getLoadavg() {
        return loadavg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power.loadAvg
     *
     * @param loadavg the value for power.loadAvg
     *
     * @mbg.generated Tue Nov 14 15:41:21 CST 2017
     */
    public void setLoadavg(Float loadavg) {
        this.loadavg = loadavg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power.time
     *
     * @return the value of power.time
     *
     * @mbg.generated Tue Nov 14 15:41:21 CST 2017
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power.time
     *
     * @param time the value for power.time
     *
     * @mbg.generated Tue Nov 14 15:41:21 CST 2017
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }
}