package com.firstCapacity.business.powerProject.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import org.springframework.web.multipart.MultipartFile;

import com.firstCapacity.business.powerType.entity.powerType;

public class powerProject implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
    private String projectId;  //主键

    private String runningTime; //运行时间
    
    private String projectName;  //项目名称

    private String projectImage;  //项目图片

    private String projectAddress;  //项目地址

    private String projectType;  //项目类型

    private String contractCustomer;  //签约客户

    private Double energyPrice;  //能源费定价/元/㎡

    private Double chargingArea;  //收费面积/万平米

    private Double projectArea;  //建筑面积/万平米

    private String contractLife;  //合同年限

    private String trusteeshipTime;  //托管日期

    private String expireTime;  //到期日期

    private Double designCoolingLoad;  //设计冷负荷

    private Double designHeatingLoad; //设计热负荷

    private Double companyCoolingLoad;  //单位冷负荷kW/m2

    private Double companyHeatingLoad;  //单位热负荷kW/m2

    private String hostOnly;  //主机形式

    private Double electricPrice;   //电单价/元/kW·h

    private Double waterPrice;  //水单价/元/吨

    private Double gasPrice;  //气单价/元/Nm³

    private Integer type;  //状态（0:顶级区域；1:区域；2:项目）

    private String projectPid; //父节点ID

    private String projectRegion;  //现做备用字段处理

    private String conditionerArea;  //现做备用字段处理

    private Date createTime;  //创建时间

    private Date updateTime;  //修改时间
    
    private String proName;  //上级名称（虚拟字段）

    private String projectIntroduce;  //项目简介
    
    private MultipartFile upFiles; //项目接收的图片
    
	private List<powerProject> quyu; //区域
	
	private List<powerType> leibie;  //类别
	
	private Integer orderType;  //排序规则
	
	private String tianqi;  //天气返回
	
    private String tableName;  //远程数据库表名称
    
    
	
	
	
    
    


	public String getRunningTime() {
		return runningTime;
	}

	public void setRunningTime(String runningTime) {
		this.runningTime = runningTime;
	}

	public String getTableName() {
		return tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public String getTianqi() {
		return tianqi;
	}

	public void setTianqi(String tianqi) {
		this.tianqi = tianqi;
	}

	public Integer getOrderType() {
		return orderType;
	}

	public void setOrderType(Integer orderType) {
		this.orderType = orderType;
	}

	public String getProName() {
		return proName;
	}

	public void setProName(String proName) {
		this.proName = proName;
	}

	public List<powerProject> getQuyu() {
		return quyu;
	}

	public void setQuyu(List<powerProject> quyu) {
		this.quyu = quyu;
	}

	public List<powerType> getLeibie() {
		return leibie;
	}

	public void setLeibie(List<powerType> leibie) {
		this.leibie = leibie;
	}

	public MultipartFile getUpFiles() {
		return upFiles;
	}

	public void setUpFiles(MultipartFile upFiles) {
		this.upFiles = upFiles;
	}

	public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_project.project_id
     *
     * @param projectId the value for power_project.project_id
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_project.project_name
     *
     * @return the value of power_project.project_name
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_project.project_name
     *
     * @param projectName the value for power_project.project_name
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_project.project_image
     *
     * @return the value of power_project.project_image
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public String getProjectImage() {
        return projectImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_project.project_image
     *
     * @param projectImage the value for power_project.project_image
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public void setProjectImage(String projectImage) {
        this.projectImage = projectImage == null ? null : projectImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_project.project_address
     *
     * @return the value of power_project.project_address
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public String getProjectAddress() {
        return projectAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_project.project_address
     *
     * @param projectAddress the value for power_project.project_address
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public void setProjectAddress(String projectAddress) {
        this.projectAddress = projectAddress == null ? null : projectAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_project.project_type
     *
     * @return the value of power_project.project_type
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public String getProjectType() {
        return projectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_project.project_type
     *
     * @param projectType the value for power_project.project_type
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public void setProjectType(String projectType) {
        this.projectType = projectType == null ? null : projectType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_project.contract_customer
     *
     * @return the value of power_project.contract_customer
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public String getContractCustomer() {
        return contractCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_project.contract_customer
     *
     * @param contractCustomer the value for power_project.contract_customer
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public void setContractCustomer(String contractCustomer) {
        this.contractCustomer = contractCustomer == null ? null : contractCustomer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_project.energy_price
     *
     * @return the value of power_project.energy_price
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public Double getEnergyPrice() {
        return energyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_project.energy_price
     *
     * @param energyPrice the value for power_project.energy_price
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public void setEnergyPrice(Double energyPrice) {
        this.energyPrice = energyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_project.charging_area
     *
     * @return the value of power_project.charging_area
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public Double getChargingArea() {
        return chargingArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_project.charging_area
     *
     * @param chargingArea the value for power_project.charging_area
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public void setChargingArea(Double chargingArea) {
        this.chargingArea = chargingArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_project.project_area
     *
     * @return the value of power_project.project_area
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public Double getProjectArea() {
        return projectArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_project.project_area
     *
     * @param projectArea the value for power_project.project_area
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public void setProjectArea(Double projectArea) {
        this.projectArea = projectArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_project.contract_life
     *
     * @return the value of power_project.contract_life
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public String getContractLife() {
        return contractLife;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_project.contract_life
     *
     * @param contractLife the value for power_project.contract_life
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public void setContractLife(String contractLife) {
        this.contractLife = contractLife == null ? null : contractLife.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_project.trusteeship_time
     *
     * @return the value of power_project.trusteeship_time
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public String getTrusteeshipTime() {
        return trusteeshipTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_project.trusteeship_time
     *
     * @param trusteeshipTime the value for power_project.trusteeship_time
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public void setTrusteeshipTime(String trusteeshipTime) {
        this.trusteeshipTime = trusteeshipTime == null ? null : trusteeshipTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_project.expire_time
     *
     * @return the value of power_project.expire_time
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public String getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_project.expire_time
     *
     * @param expireTime the value for power_project.expire_time
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public void setExpireTime(String expireTime) {
        this.expireTime = expireTime == null ? null : expireTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_project.design_cooling_load
     *
     * @return the value of power_project.design_cooling_load
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public Double getDesignCoolingLoad() {
        return designCoolingLoad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_project.design_cooling_load
     *
     * @param designCoolingLoad the value for power_project.design_cooling_load
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public void setDesignCoolingLoad(Double designCoolingLoad) {
        this.designCoolingLoad = designCoolingLoad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_project.design_heating_load
     *
     * @return the value of power_project.design_heating_load
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public Double getDesignHeatingLoad() {
        return designHeatingLoad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_project.design_heating_load
     *
     * @param designHeatingLoad the value for power_project.design_heating_load
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public void setDesignHeatingLoad(Double designHeatingLoad) {
        this.designHeatingLoad = designHeatingLoad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_project.company_cooling_load
     *
     * @return the value of power_project.company_cooling_load
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public Double getCompanyCoolingLoad() {
        return companyCoolingLoad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_project.company_cooling_load
     *
     * @param companyCoolingLoad the value for power_project.company_cooling_load
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public void setCompanyCoolingLoad(Double companyCoolingLoad) {
        this.companyCoolingLoad = companyCoolingLoad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_project.company_heating_load
     *
     * @return the value of power_project.company_heating_load
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public Double getCompanyHeatingLoad() {
        return companyHeatingLoad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_project.company_heating_load
     *
     * @param companyHeatingLoad the value for power_project.company_heating_load
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public void setCompanyHeatingLoad(Double companyHeatingLoad) {
        this.companyHeatingLoad = companyHeatingLoad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_project.host_only
     *
     * @return the value of power_project.host_only
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public String getHostOnly() {
        return hostOnly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_project.host_only
     *
     * @param hostOnly the value for power_project.host_only
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public void setHostOnly(String hostOnly) {
        this.hostOnly = hostOnly == null ? null : hostOnly.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_project.electric_price
     *
     * @return the value of power_project.electric_price
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public Double getElectricPrice() {
        return electricPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_project.electric_price
     *
     * @param electricPrice the value for power_project.electric_price
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public void setElectricPrice(Double electricPrice) {
        this.electricPrice = electricPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_project.water_price
     *
     * @return the value of power_project.water_price
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public Double getWaterPrice() {
        return waterPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_project.water_price
     *
     * @param waterPrice the value for power_project.water_price
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public void setWaterPrice(Double waterPrice) {
        this.waterPrice = waterPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_project.gas_price
     *
     * @return the value of power_project.gas_price
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public Double getGasPrice() {
        return gasPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_project.gas_price
     *
     * @param gasPrice the value for power_project.gas_price
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public void setGasPrice(Double gasPrice) {
        this.gasPrice = gasPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_project.type
     *
     * @return the value of power_project.type
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_project.type
     *
     * @param type the value for power_project.type
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_project.project_pid
     *
     * @return the value of power_project.project_pid
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public String getProjectPid() {
        return projectPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_project.project_pid
     *
     * @param projectPid the value for power_project.project_pid
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public void setProjectPid(String projectPid) {
        this.projectPid = projectPid == null ? null : projectPid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_project.project_region
     *
     * @return the value of power_project.project_region
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public String getProjectRegion() {
        return projectRegion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_project.project_region
     *
     * @param projectRegion the value for power_project.project_region
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public void setProjectRegion(String projectRegion) {
        this.projectRegion = projectRegion == null ? null : projectRegion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_project.conditioner_area
     *
     * @return the value of power_project.conditioner_area
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public String getConditionerArea() {
        return conditionerArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_project.conditioner_area
     *
     * @param conditionerArea the value for power_project.conditioner_area
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public void setConditionerArea(String conditionerArea) {
        this.conditionerArea = conditionerArea == null ? null : conditionerArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_project.create_time
     *
     * @return the value of power_project.create_time
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_project.create_time
     *
     * @param createTime the value for power_project.create_time
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_project.update_time
     *
     * @return the value of power_project.update_time
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_project.update_time
     *
     * @param updateTime the value for power_project.update_time
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_project.project_introduce
     *
     * @return the value of power_project.project_introduce
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public String getProjectIntroduce() {
        return projectIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_project.project_introduce
     *
     * @param projectIntroduce the value for power_project.project_introduce
     *
     * @mbg.generated Fri Oct 20 10:24:47 CST 2017
     */
    public void setProjectIntroduce(String projectIntroduce) {
        this.projectIntroduce = projectIntroduce == null ? null : projectIntroduce.trim();
    }

	@Override
	public String toString() {
		return "powerProject [projectId=" + projectId + ", projectName=" + projectName + ", projectImage="
				+ projectImage + ", projectAddress=" + projectAddress + ", projectType=" + projectType
				+ ", contractCustomer=" + contractCustomer + ", energyPrice=" + energyPrice + ", chargingArea="
				+ chargingArea + ", projectArea=" + projectArea + ", contractLife=" + contractLife
				+ ", trusteeshipTime=" + trusteeshipTime + ", expireTime=" + expireTime + ", designCoolingLoad="
				+ designCoolingLoad + ", designHeatingLoad=" + designHeatingLoad + ", companyCoolingLoad="
				+ companyCoolingLoad + ", companyHeatingLoad=" + companyHeatingLoad + ", hostOnly=" + hostOnly
				+ ", electricPrice=" + electricPrice + ", waterPrice=" + waterPrice + ", gasPrice=" + gasPrice
				+ ", type=" + type + ", projectPid=" + projectPid + ", projectRegion=" + projectRegion
				+ ", conditionerArea=" + conditionerArea + ", createTime=" + createTime + ", updateTime=" + updateTime
				+ ", proName=" + proName + ", projectIntroduce=" + projectIntroduce + ", upFiles=" + upFiles + ", quyu="
				+ quyu + ", leibie=" + leibie + ", orderType=" + orderType + "]";
	}
    
    
    
    
}