package com.firstCapacity.business.StaffInformation.entity;

import java.io.Serializable;
import java.util.Date;

public class StaffInformation implements Serializable{
	
	private static final long serialVersionUID = 1L;
	
	private String staffId;  //主键

    private String staffName;  //职员姓名

    private String projectId;  //项目ID

    private String regionId;  //区域ID

    private String age;  //年龄

    private String position;  //职位

    private String contactInformation;  //联系方式

    private String projectName;  //项目名称

    private String regionName;  //区域名称

    private Date createTime;  //创建时间

    private Date updateTime;  //修改时间


    
    
    
    
    
    
    public String getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_information.staff_id
     *
     * @param staffId the value for staff_information.staff_id
     *
     * @mbg.generated Wed Nov 01 15:54:59 CST 2017
     */
    public void setStaffId(String staffId) {
        this.staffId = staffId == null ? null : staffId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_information.staff_name
     *
     * @return the value of staff_information.staff_name
     *
     * @mbg.generated Wed Nov 01 15:54:59 CST 2017
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_information.staff_name
     *
     * @param staffName the value for staff_information.staff_name
     *
     * @mbg.generated Wed Nov 01 15:54:59 CST 2017
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName == null ? null : staffName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_information.project_id
     *
     * @return the value of staff_information.project_id
     *
     * @mbg.generated Wed Nov 01 15:54:59 CST 2017
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_information.project_id
     *
     * @param projectId the value for staff_information.project_id
     *
     * @mbg.generated Wed Nov 01 15:54:59 CST 2017
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_information.region_id
     *
     * @return the value of staff_information.region_id
     *
     * @mbg.generated Wed Nov 01 15:54:59 CST 2017
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_information.region_id
     *
     * @param regionId the value for staff_information.region_id
     *
     * @mbg.generated Wed Nov 01 15:54:59 CST 2017
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId == null ? null : regionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_information.age
     *
     * @return the value of staff_information.age
     *
     * @mbg.generated Wed Nov 01 15:54:59 CST 2017
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_information.age
     *
     * @param age the value for staff_information.age
     *
     * @mbg.generated Wed Nov 01 15:54:59 CST 2017
     */
    public void setAge(String age) {
        this.age = age == null ? null : age.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_information.position
     *
     * @return the value of staff_information.position
     *
     * @mbg.generated Wed Nov 01 15:54:59 CST 2017
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_information.position
     *
     * @param position the value for staff_information.position
     *
     * @mbg.generated Wed Nov 01 15:54:59 CST 2017
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_information.contact_information
     *
     * @return the value of staff_information.contact_information
     *
     * @mbg.generated Wed Nov 01 15:54:59 CST 2017
     */
    public String getContactInformation() {
        return contactInformation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_information.contact_information
     *
     * @param contactInformation the value for staff_information.contact_information
     *
     * @mbg.generated Wed Nov 01 15:54:59 CST 2017
     */
    public void setContactInformation(String contactInformation) {
        this.contactInformation = contactInformation == null ? null : contactInformation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_information.project_name
     *
     * @return the value of staff_information.project_name
     *
     * @mbg.generated Wed Nov 01 15:54:59 CST 2017
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_information.project_name
     *
     * @param projectName the value for staff_information.project_name
     *
     * @mbg.generated Wed Nov 01 15:54:59 CST 2017
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_information.region_name
     *
     * @return the value of staff_information.region_name
     *
     * @mbg.generated Wed Nov 01 15:54:59 CST 2017
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_information.region_name
     *
     * @param regionName the value for staff_information.region_name
     *
     * @mbg.generated Wed Nov 01 15:54:59 CST 2017
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName == null ? null : regionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_information.create_time
     *
     * @return the value of staff_information.create_time
     *
     * @mbg.generated Wed Nov 01 15:54:59 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_information.create_time
     *
     * @param createTime the value for staff_information.create_time
     *
     * @mbg.generated Wed Nov 01 15:54:59 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_information.update_time
     *
     * @return the value of staff_information.update_time
     *
     * @mbg.generated Wed Nov 01 15:54:59 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_information.update_time
     *
     * @param updateTime the value for staff_information.update_time
     *
     * @mbg.generated Wed Nov 01 15:54:59 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}