package com.firstCapacity.business.powerNengHao.entity;

import java.io.Serializable;
import java.util.Date;

public class powerHistory implements Serializable{
	
	private static final long serialVersionUID = 1L;

    private String id;  //主键

    private Date timeNow;  //时间

    private Double tableBase;  //表底数

    private Integer consumption;  //耗量

    private Integer rate;  //倍率

    private String crewName;  //机组名

    private String projectId;  //项目ID

    private String regionId;  //区域ID

    private String projectName;  //项目名称

    private String regionName;  //区域名称

    private String test1;  //备用字段1

    private String test2;  //备用字段2
    
    
    
    
    
    
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_history.id
     *
     * @return the value of power_history.id
     *
     * @mbg.generated Wed Nov 15 14:49:44 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_history.id
     *
     * @param id the value for power_history.id
     *
     * @mbg.generated Wed Nov 15 14:49:44 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_history.time_now
     *
     * @return the value of power_history.time_now
     *
     * @mbg.generated Wed Nov 15 14:49:44 CST 2017
     */
    public Date getTimeNow() {
        return timeNow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_history.time_now
     *
     * @param timeNow the value for power_history.time_now
     *
     * @mbg.generated Wed Nov 15 14:49:44 CST 2017
     */
    public void setTimeNow(Date timeNow) {
        this.timeNow = timeNow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_history.table_base
     *
     * @return the value of power_history.table_base
     *
     * @mbg.generated Wed Nov 15 14:49:44 CST 2017
     */
    public Double getTableBase() {
        return tableBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_history.table_base
     *
     * @param tableBase the value for power_history.table_base
     *
     * @mbg.generated Wed Nov 15 14:49:44 CST 2017
     */
    public void setTableBase(Double tableBase) {
        this.tableBase = tableBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_history.consumption
     *
     * @return the value of power_history.consumption
     *
     * @mbg.generated Wed Nov 15 14:49:44 CST 2017
     */
    public Integer getConsumption() {
        return consumption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_history.consumption
     *
     * @param consumption the value for power_history.consumption
     *
     * @mbg.generated Wed Nov 15 14:49:44 CST 2017
     */
    public void setConsumption(Integer consumption) {
        this.consumption = consumption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_history.rate
     *
     * @return the value of power_history.rate
     *
     * @mbg.generated Wed Nov 15 14:49:44 CST 2017
     */
    public Integer getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_history.rate
     *
     * @param rate the value for power_history.rate
     *
     * @mbg.generated Wed Nov 15 14:49:44 CST 2017
     */
    public void setRate(Integer rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_history.crew_name
     *
     * @return the value of power_history.crew_name
     *
     * @mbg.generated Wed Nov 15 14:49:44 CST 2017
     */
    public String getCrewName() {
        return crewName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_history.crew_name
     *
     * @param crewName the value for power_history.crew_name
     *
     * @mbg.generated Wed Nov 15 14:49:44 CST 2017
     */
    public void setCrewName(String crewName) {
        this.crewName = crewName == null ? null : crewName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_history.project_id
     *
     * @return the value of power_history.project_id
     *
     * @mbg.generated Wed Nov 15 14:49:44 CST 2017
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_history.project_id
     *
     * @param projectId the value for power_history.project_id
     *
     * @mbg.generated Wed Nov 15 14:49:44 CST 2017
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_history.region_id
     *
     * @return the value of power_history.region_id
     *
     * @mbg.generated Wed Nov 15 14:49:44 CST 2017
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_history.region_id
     *
     * @param regionId the value for power_history.region_id
     *
     * @mbg.generated Wed Nov 15 14:49:44 CST 2017
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId == null ? null : regionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_history.project_name
     *
     * @return the value of power_history.project_name
     *
     * @mbg.generated Wed Nov 15 14:49:44 CST 2017
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_history.project_name
     *
     * @param projectName the value for power_history.project_name
     *
     * @mbg.generated Wed Nov 15 14:49:44 CST 2017
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_history.region_name
     *
     * @return the value of power_history.region_name
     *
     * @mbg.generated Wed Nov 15 14:49:44 CST 2017
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_history.region_name
     *
     * @param regionName the value for power_history.region_name
     *
     * @mbg.generated Wed Nov 15 14:49:44 CST 2017
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName == null ? null : regionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_history.test1
     *
     * @return the value of power_history.test1
     *
     * @mbg.generated Wed Nov 15 14:49:44 CST 2017
     */
    public String getTest1() {
        return test1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_history.test1
     *
     * @param test1 the value for power_history.test1
     *
     * @mbg.generated Wed Nov 15 14:49:44 CST 2017
     */
    public void setTest1(String test1) {
        this.test1 = test1 == null ? null : test1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_history.test2
     *
     * @return the value of power_history.test2
     *
     * @mbg.generated Wed Nov 15 14:49:44 CST 2017
     */
    public String getTest2() {
        return test2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_history.test2
     *
     * @param test2 the value for power_history.test2
     *
     * @mbg.generated Wed Nov 15 14:49:44 CST 2017
     */
    public void setTest2(String test2) {
        this.test2 = test2 == null ? null : test2.trim();
    }
}