package com.firstCapacity.business.test_automation.mapper;

import com.firstCapacity.business.test_automation.entity.automationUser;

public interface automationUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Sep 12 09:58:28 CST 2017
     */
    int insert(automationUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Sep 12 09:58:28 CST 2017
     */
    int insertSelective(automationUser record);
}