package com.firstCapacity.business.equipmentType.entity;

import java.io.Serializable;
import java.util.Date;

public class EquipmentType implements Serializable{
	
	private static final long serialVersionUID = 1L;
	
    private String equipmentTypeId;  //主键

    private String equipmentTypeName;  //设备类型名称

    private Date createTime;  //创建时间

    private Date updateTime;  //修改时间

    public String getEquipmentTypeId() {
        return equipmentTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_type.equipment_type_id
     *
     * @param equipmentTypeId the value for equipment_type.equipment_type_id
     *
     * @mbg.generated Mon Oct 23 14:10:54 CST 2017
     */
    public void setEquipmentTypeId(String equipmentTypeId) {
        this.equipmentTypeId = equipmentTypeId == null ? null : equipmentTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_type.equipment_type_name
     *
     * @return the value of equipment_type.equipment_type_name
     *
     * @mbg.generated Mon Oct 23 14:10:54 CST 2017
     */
    public String getEquipmentTypeName() {
        return equipmentTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_type.equipment_type_name
     *
     * @param equipmentTypeName the value for equipment_type.equipment_type_name
     *
     * @mbg.generated Mon Oct 23 14:10:54 CST 2017
     */
    public void setEquipmentTypeName(String equipmentTypeName) {
        this.equipmentTypeName = equipmentTypeName == null ? null : equipmentTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_type.create_time
     *
     * @return the value of equipment_type.create_time
     *
     * @mbg.generated Mon Oct 23 14:10:54 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_type.create_time
     *
     * @param createTime the value for equipment_type.create_time
     *
     * @mbg.generated Mon Oct 23 14:10:54 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column equipment_type.update_time
     *
     * @return the value of equipment_type.update_time
     *
     * @mbg.generated Mon Oct 23 14:10:54 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column equipment_type.update_time
     *
     * @param updateTime the value for equipment_type.update_time
     *
     * @mbg.generated Mon Oct 23 14:10:54 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}