package com.firstCapacity.business.HeFeiPower.mapper;

import java.util.List;

import com.firstCapacity.business.HeFeiPower.entity.HF_hy_31;
import com.firstCapacity.util.aop.DataSource;

public interface HF_hy_31Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HF_hy_31
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    int insert(HF_hy_31 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HF_hy_31
     *
     * @mbg.generated Thu Nov 16 16:18:53 CST 2017
     */
    int insertSelective(HF_hy_31 record);
    
    
    //查询3天系统总能耗记录
    @DataSource("B")
    public List<HF_hy_31> selectListZong(HF_hy_31 record);
    
    //查询3天设备调节记录
    @DataSource("B")
    public List<HF_hy_31> selectListShebei(HF_hy_31 record);
    
    //查询最新的3条记录
    @DataSource("B")
    public List<HF_hy_31> selectOne3();
}