package com.firstCapacity.business.TypesettingRecord.entity;

import java.io.Serializable;
import java.util.Date;

import org.springframework.web.multipart.MultipartFile;

public class TypesettingRecord implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
    
    private String typesettingId;  //记录id

    private String regionId;  //区域ID

    private String projectId;  // 项目ID
 
    private String fileName;  //文件名称

    private String filePath;  //文件路径

    private String userId;  //用户ID

    private String userName;  //用户名称

    private Date createTime;  //创建时间
    
    private String createTimeNew;  //格式化创建时间
    
    private MultipartFile upFiles;  //文件


    
    
    
    
    public MultipartFile getUpFiles() {
		return upFiles;
	}

	public void setUpFiles(MultipartFile upFiles) {
		this.upFiles = upFiles;
	}

	public String getCreateTimeNew() {
		return createTimeNew;
	}

	public void setCreateTimeNew(String createTimeNew) {
		this.createTimeNew = createTimeNew;
	}

	public String getTypesettingId() {
        return typesettingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typesetting_record.typesetting_id
     *
     * @param typesettingId the value for typesetting_record.typesetting_id
     *
     * @mbg.generated Wed Nov 01 15:56:09 CST 2017
     */
    public void setTypesettingId(String typesettingId) {
        this.typesettingId = typesettingId == null ? null : typesettingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typesetting_record.region_id
     *
     * @return the value of typesetting_record.region_id
     *
     * @mbg.generated Wed Nov 01 15:56:09 CST 2017
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typesetting_record.region_id
     *
     * @param regionId the value for typesetting_record.region_id
     *
     * @mbg.generated Wed Nov 01 15:56:09 CST 2017
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId == null ? null : regionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typesetting_record.project_id
     *
     * @return the value of typesetting_record.project_id
     *
     * @mbg.generated Wed Nov 01 15:56:09 CST 2017
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typesetting_record.project_id
     *
     * @param projectId the value for typesetting_record.project_id
     *
     * @mbg.generated Wed Nov 01 15:56:09 CST 2017
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typesetting_record.file_name
     *
     * @return the value of typesetting_record.file_name
     *
     * @mbg.generated Wed Nov 01 15:56:09 CST 2017
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typesetting_record.file_name
     *
     * @param fileName the value for typesetting_record.file_name
     *
     * @mbg.generated Wed Nov 01 15:56:09 CST 2017
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typesetting_record.file_path
     *
     * @return the value of typesetting_record.file_path
     *
     * @mbg.generated Wed Nov 01 15:56:09 CST 2017
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typesetting_record.file_path
     *
     * @param filePath the value for typesetting_record.file_path
     *
     * @mbg.generated Wed Nov 01 15:56:09 CST 2017
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typesetting_record.user_id
     *
     * @return the value of typesetting_record.user_id
     *
     * @mbg.generated Wed Nov 01 15:56:09 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typesetting_record.user_id
     *
     * @param userId the value for typesetting_record.user_id
     *
     * @mbg.generated Wed Nov 01 15:56:09 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typesetting_record.user_name
     *
     * @return the value of typesetting_record.user_name
     *
     * @mbg.generated Wed Nov 01 15:56:09 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typesetting_record.user_name
     *
     * @param userName the value for typesetting_record.user_name
     *
     * @mbg.generated Wed Nov 01 15:56:09 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column typesetting_record.create_time
     *
     * @return the value of typesetting_record.create_time
     *
     * @mbg.generated Wed Nov 01 15:56:09 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column typesetting_record.create_time
     *
     * @param createTime the value for typesetting_record.create_time
     *
     * @mbg.generated Wed Nov 01 15:56:09 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}