package com.firstCapacity.business.user.entity;

import java.io.Serializable;

public class Roles implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.id
     *
     * @mbg.generated Thu Sep 14 09:23:31 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.roles
     *
     * @mbg.generated Thu Sep 14 09:23:31 CST 2017
     */
    private String roles;
    
    
    private String userId;  //虚拟是体
    
    
    

    public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.id
     *
     * @return the value of roles.id
     *
     * @mbg.generated Thu Sep 14 09:23:31 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.id
     *
     * @param id the value for roles.id
     *
     * @mbg.generated Thu Sep 14 09:23:31 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.roles
     *
     * @return the value of roles.roles
     *
     * @mbg.generated Thu Sep 14 09:23:31 CST 2017
     */
    public String getRoles() {
        return roles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.roles
     *
     * @param roles the value for roles.roles
     *
     * @mbg.generated Thu Sep 14 09:23:31 CST 2017
     */
    public void setRoles(String roles) {
        this.roles = roles == null ? null : roles.trim();
    }
}