package com.firstCapacity.business.user.entity;

import java.io.Serializable;

public class userRoles implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.user_id
     *
     * @mbg.generated Thu Sep 14 09:25:09 CST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_roles.roles_id
     *
     * @mbg.generated Thu Sep 14 09:25:09 CST 2017
     */
    private String rolesId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.user_id
     *
     * @return the value of user_roles.user_id
     *
     * @mbg.generated Thu Sep 14 09:25:09 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.user_id
     *
     * @param userId the value for user_roles.user_id
     *
     * @mbg.generated Thu Sep 14 09:25:09 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_roles.roles_id
     *
     * @return the value of user_roles.roles_id
     *
     * @mbg.generated Thu Sep 14 09:25:09 CST 2017
     */
    public String getRolesId() {
        return rolesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_roles.roles_id
     *
     * @param rolesId the value for user_roles.roles_id
     *
     * @mbg.generated Thu Sep 14 09:25:09 CST 2017
     */
    public void setRolesId(String rolesId) {
        this.rolesId = rolesId == null ? null : rolesId.trim();
    }
}