package com.firstCapacity.business.user.mapper;

import com.firstCapacity.business.user.entity.userRoles;

public interface userRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Thu Sep 14 09:25:09 CST 2017
     */
    int insert(userRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_roles
     *
     * @mbg.generated Thu Sep 14 09:25:09 CST 2017
     */
    int insertSelective(userRoles record);
    
    //删除关联
    public void deleteGuanlian(String userId);
}